// Ficheiro gerado a partir do JSON de inscrições recebido em 30/08/2026.
// Para regenerar: node scripts/generate-official-squads.mjs <entrada.json> <este-ficheiro>

export const OFFICIAL_SQUADS_2026_27 = [
  {
    "sourceName": "1º de Maio de Benguela",
    "teamId": "primeiromaio",
    "club": "Estrela 1.º de Maio",
    "players": [
      {
        "name": "DIMONIQUENE KAPEMBE SEGUNDA BONGUE",
        "fullName": "DIMONIQUENE KAPEMBE SEGUNDA BONGUE",
        "popularName": "",
        "maId": "000568M00",
        "fifaId": "1JXIB83",
        "gender": "MALE",
        "birthDate": "19/04/2000",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "13"
      },
      {
        "name": "Deco",
        "fullName": "MOISÉS ALBERTO CALEPI",
        "popularName": "Deco",
        "maId": "000457M96",
        "fifaId": "1JSRCP9",
        "gender": "MALE",
        "birthDate": "31/12/1996",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "9"
      },
      {
        "name": "DANIEL CHACULEMBA",
        "fullName": "DANIEL CHACULEMBA",
        "popularName": "",
        "maId": "002433M96",
        "fifaId": "1LSUTX8",
        "gender": "MALE",
        "birthDate": "25/07/1996",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "28"
      },
      {
        "name": "Muila Lengo Congolo",
        "fullName": "Muila Lengo Congolo",
        "popularName": "",
        "maId": "001067M01",
        "fifaId": "1K2PEY7",
        "gender": "MALE",
        "birthDate": "25/04/2001",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "16"
      },
      {
        "name": "Miguel Agostinho Dey",
        "fullName": "Miguel Agostinho Dey",
        "popularName": "",
        "maId": "002775M03",
        "fifaId": "1M9IBY1",
        "gender": "MALE",
        "birthDate": "25/08/2003",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "2"
      },
      {
        "name": "MOISES MBUTA DOMINGOS",
        "fullName": "MOISES MBUTA DOMINGOS",
        "popularName": "",
        "maId": "000873M02",
        "fifaId": "1K1HKV2",
        "gender": "MALE",
        "birthDate": "18/07/2002",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "5"
      },
      {
        "name": "VICENTE DOMINGOS",
        "fullName": "VICENTE DOMINGOS",
        "popularName": "",
        "maId": "002898M04",
        "fifaId": "1MALEZ5",
        "gender": "MALE",
        "birthDate": "20/01/2004",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "34"
      },
      {
        "name": "Fernando Mateus Duarte Duarte",
        "fullName": "Fernando Mateus Duarte Duarte",
        "popularName": "",
        "maId": "002162M00",
        "fifaId": "1LJH1X4",
        "gender": "MALE",
        "birthDate": "28/02/2000",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "20"
      },
      {
        "name": "Luis Simoes Escovalo",
        "fullName": "Luis Simoes Escovalo",
        "popularName": "",
        "maId": "001258M01",
        "fifaId": "1KZTK20",
        "gender": "MALE",
        "birthDate": "06/02/2001",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "19"
      },
      {
        "name": "SIMÃO CULECA GONGA",
        "fullName": "SIMÃO CULECA GONGA",
        "popularName": "",
        "maId": "003470M02",
        "fifaId": "1NB4BP9",
        "gender": "MALE",
        "birthDate": "16/01/2002",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "22"
      },
      {
        "name": "TADEU NUMBI DA SILVA JAKE",
        "fullName": "TADEU NUMBI DA SILVA JAKE",
        "popularName": "",
        "maId": "003465M99",
        "fifaId": "1NAVZJ4",
        "gender": "MALE",
        "birthDate": "31/05/1999",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "3"
      },
      {
        "name": "Odenir Tavares Pereira Jorge",
        "fullName": "Odenir Tavares Pereira Jorge",
        "popularName": "",
        "maId": "003082M02",
        "fifaId": "1MQVBD5",
        "gender": "MALE",
        "birthDate": "06/06/2002",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "14"
      },
      {
        "name": "Avelino Mussili Kassanhica",
        "fullName": "Avelino Mussili Kassanhica",
        "popularName": "",
        "maId": "001177M03",
        "fifaId": "1KF4F49",
        "gender": "MALE",
        "birthDate": "21/05/2004",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "29"
      },
      {
        "name": "MÁRCIO ARMANDO GONÇALVES LUVAMBO",
        "fullName": "MÁRCIO ARMANDO GONÇALVES LUVAMBO",
        "popularName": "",
        "maId": "000629M86",
        "fifaId": "1JYN4K6",
        "gender": "MALE",
        "birthDate": "04/03/1986",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "7"
      },
      {
        "name": "Rodrigues Muehombo",
        "fullName": "Rodrigues Muehombo",
        "popularName": "",
        "maId": "000848M96",
        "fifaId": "1K176E0",
        "gender": "MALE",
        "birthDate": "13/05/1996",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "8"
      },
      {
        "name": "PAULO BALACA MUTOSSI",
        "fullName": "PAULO BALACA MUTOSSI",
        "popularName": "",
        "maId": "000644M00",
        "fifaId": "1JZ4J23",
        "gender": "MALE",
        "birthDate": "19/02/2000",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "24"
      },
      {
        "name": "ANTÓNIO PASCOAL",
        "fullName": "ANTÓNIO PASCOAL",
        "popularName": "",
        "maId": "000942M00",
        "fifaId": "1K1SG53",
        "gender": "MALE",
        "birthDate": "15/04/2000",
        "nationality": "Angola",
        "position": "GK",
        "jerseyNumber": "1"
      },
      {
        "name": "ANTÓNIO LUCAMBA PESSELA",
        "fullName": "ANTÓNIO LUCAMBA PESSELA",
        "popularName": "",
        "maId": "000642M97",
        "fifaId": "1JZ4FG4",
        "gender": "MALE",
        "birthDate": "18/03/1997",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "26"
      },
      {
        "name": "ANTONIO LENDE TCHIMUKU",
        "fullName": "ANTONIO LENDE TCHIMUKU",
        "popularName": "",
        "maId": "001589M99",
        "fifaId": "1L96AR2",
        "gender": "MALE",
        "birthDate": "02/02/1999",
        "nationality": "Angola",
        "position": "GK",
        "jerseyNumber": "99"
      },
      {
        "name": "JOAQUIM KANHIHI TCHINGOMBE",
        "fullName": "JOAQUIM KANHIHI TCHINGOMBE",
        "popularName": "",
        "maId": "003471M02",
        "fifaId": "1NB4DQ1",
        "gender": "MALE",
        "birthDate": "02/02/2002",
        "nationality": "Angola",
        "position": "GK",
        "jerseyNumber": "56"
      },
      {
        "name": "FRANCISCO NGALANGUI TCHITANE",
        "fullName": "FRANCISCO NGALANGUI TCHITANE",
        "popularName": "",
        "maId": "003468M02",
        "fifaId": "1NB49X0",
        "gender": "MALE",
        "birthDate": "20/07/2002",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "33"
      },
      {
        "name": "JOSE MARCOS PEREIRA TCHIVINGA",
        "fullName": "JOSE MARCOS PEREIRA TCHIVINGA",
        "popularName": "",
        "maId": "000747M00",
        "fifaId": "1K0C7S4",
        "gender": "MALE",
        "birthDate": "03/03/2000",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "15"
      },
      {
        "name": "GELSON TELES",
        "fullName": "GELSON TELES",
        "popularName": "",
        "maId": "000676M91",
        "fifaId": "1JZJEU2",
        "gender": "MALE",
        "birthDate": "23/07/1991",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "18"
      },
      {
        "name": "ELISEU ANTÓNIO BORGES VARELA",
        "fullName": "ELISEU ANTÓNIO BORGES VARELA",
        "popularName": "",
        "maId": "000565M01",
        "fifaId": "1JXHXL1",
        "gender": "MALE",
        "birthDate": "27/07/2001",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "6"
      },
      {
        "name": "Moises Maquico Lua",
        "fullName": "Moises Maquico Lua",
        "popularName": "",
        "maId": "001189M03",
        "fifaId": "1KF4IX9",
        "gender": "MALE",
        "birthDate": "24/01/2003",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "37"
      },
      {
        "name": "DAMIÃO RAIMUNDO NICOLAU",
        "fullName": "DAMIÃO RAIMUNDO NICOLAU",
        "popularName": "",
        "maId": "005558M04",
        "fifaId": "1QF49D2",
        "gender": "MALE",
        "birthDate": "10/05/2004",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "4"
      },
      {
        "name": "KIJUNGU KITUMBA FRANCISCO",
        "fullName": "KIJUNGU KITUMBA FRANCISCO",
        "popularName": "",
        "maId": "003535M02",
        "fifaId": "1ND4NN2",
        "gender": "MALE",
        "birthDate": "17/05/2002",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "25"
      },
      {
        "name": "MALEBANI RABBY",
        "fullName": "MALEBANI RABBY",
        "popularName": "",
        "maId": "000923M00",
        "fifaId": "1K1M4E0",
        "gender": "MALE",
        "birthDate": "26/07/2000",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "31"
      }
    ],
    "staff": [
      {
        "name": "Igor Joaquim Da Cotsa Cordeiro",
        "fullName": "Igor Joaquim Da Cotsa Cordeiro",
        "popularName": "",
        "maId": "003006M82",
        "fifaId": "1MK97N8",
        "gender": "MALE",
        "role": "PHYS",
        "nationality": "Angola"
      },
      {
        "name": "Ludivaldo Fonseca Lutukuta",
        "fullName": "Ludivaldo Fonseca Lutukuta",
        "popularName": "",
        "maId": "007272M96",
        "fifaId": "1SR6E42",
        "gender": "MALE",
        "role": "TSTF",
        "nationality": "Angola"
      },
      {
        "name": "António Manuel Dos Santos TS",
        "fullName": "António Manuel Dos Santos TS",
        "popularName": "",
        "maId": "006249M87",
        "fifaId": "1QWA4G9",
        "gender": "MALE",
        "role": "TSTF",
        "nationality": "Angola"
      },
      {
        "name": "FRANCISCO SACHINGOMBE CASIMIRO CASSOMA",
        "fullName": "FRANCISCO SACHINGOMBE CASIMIRO CASSOMA",
        "popularName": "",
        "maId": "003515M75",
        "fifaId": "1NC2UJ5",
        "gender": "MALE",
        "role": "TMED",
        "nationality": "Angola"
      },
      {
        "name": "FERNANDO FITA ANTÓNIO FRANCISCO",
        "fullName": "FERNANDO FITA ANTÓNIO FRANCISCO",
        "popularName": "",
        "maId": "001820M86",
        "fifaId": "1LDITX7",
        "gender": "MALE",
        "role": "TSTF",
        "nationality": "Angola"
      },
      {
        "name": "FUSO NKOSI",
        "fullName": "FUSO NKOSI",
        "popularName": "",
        "maId": "003513M56",
        "fifaId": "1NC2UD8",
        "gender": "MALE",
        "role": "TCSC",
        "nationality": "Angola"
      },
      {
        "name": "José Nguli Nahenda",
        "fullName": "José Nguli Nahenda",
        "popularName": "",
        "maId": "001229M84",
        "fifaId": "1KZG174",
        "gender": "MALE",
        "role": "GKCH",
        "nationality": "Angola"
      },
      {
        "name": "MANUEL SILVA",
        "fullName": "MANUEL SILVA",
        "popularName": "",
        "maId": "003846M63",
        "fifaId": "1NWV3Z3",
        "gender": "MALE",
        "role": "KMGR",
        "nationality": "Angola"
      },
      {
        "name": "Adirio Francisco Simoes",
        "fullName": "Adirio Francisco Simoes",
        "popularName": "",
        "maId": "003010M86",
        "fifaId": "1MK9CA3",
        "gender": "MALE",
        "role": "PTNR",
        "nationality": "Angola"
      },
      {
        "name": "Águas Da Silva",
        "fullName": "Águas Da Silva",
        "popularName": "",
        "maId": "000796M73",
        "fifaId": "1K0SAP5",
        "gender": "MALE",
        "role": "HDCH",
        "nationality": "Angola"
      },
      {
        "name": "JOÃO FORTUNA",
        "fullName": "JOÃO FORTUNA",
        "popularName": "",
        "maId": "000497M85",
        "fifaId": "1JULVL6",
        "gender": "MALE",
        "role": "AMGR",
        "nationality": "Angola"
      },
      {
        "name": "WILSON QUIZANGA ESTEVES",
        "fullName": "WILSON QUIZANGA ESTEVES",
        "popularName": "",
        "maId": "005770M75",
        "fifaId": "1QHT4H3",
        "gender": "MALE",
        "role": "TMGR",
        "nationality": "Angola"
      },
      {
        "name": "Hermino Nunes",
        "fullName": "Hermino Nunes",
        "popularName": "",
        "maId": "009006M83",
        "fifaId": "1V1TKH6",
        "gender": "MALE",
        "role": "",
        "nationality": "Angola"
      },
      {
        "name": "Zamba Victor",
        "fullName": "Zamba Victor",
        "popularName": "",
        "maId": "002185M83",
        "fifaId": "1LJU067",
        "gender": "MALE",
        "role": "GKCH",
        "nationality": "Angola"
      }
    ]
  },
  {
    "sourceName": "Wiliete",
    "teamId": "wiliete",
    "club": "Wiliete de Benguela",
    "players": [
      {
        "name": "JOÃO VALONGA BASILIO BARROS",
        "fullName": "JOÃO VALONGA BASILIO BARROS",
        "popularName": "",
        "maId": "000647M02",
        "fifaId": "1JZ4N21",
        "gender": "MALE",
        "birthDate": "21/02/2002",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "26"
      },
      {
        "name": "AUGUSTO MANUEL BALSA",
        "fullName": "AUGUSTO MANUEL BALSA",
        "popularName": "",
        "maId": "000320M00",
        "fifaId": "1JJFIJ0",
        "gender": "MALE",
        "birthDate": "06/05/2000",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "15"
      },
      {
        "name": "SILVA HINÁRIO ANTÓNIO",
        "fullName": "SILVA HINÁRIO ANTÓNIO",
        "popularName": "",
        "maId": "002281M98",
        "fifaId": "1LJZ6E0",
        "gender": "MALE",
        "birthDate": "10/02/1998",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "3"
      },
      {
        "name": "Lukman Idowu Bello",
        "fullName": "Lukman Idowu Bello",
        "popularName": "",
        "maId": "007235M02",
        "fifaId": "1SN8AC3",
        "gender": "MALE",
        "birthDate": "03/10/2002",
        "nationality": "Democratic Republic of the Congo",
        "position": "FWD",
        "jerseyNumber": "18"
      },
      {
        "name": "ARMINDO GONÇALVES CANJI",
        "fullName": "ARMINDO GONÇALVES CANJI",
        "popularName": "",
        "maId": "000401M04",
        "fifaId": "1JRU7C5",
        "gender": "MALE",
        "birthDate": "18/10/2004",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "10"
      },
      {
        "name": "Carlos Cassissi",
        "fullName": "Carlos Cassissi",
        "popularName": "",
        "maId": "008144M06",
        "fifaId": "1UQNV32",
        "gender": "MALE",
        "birthDate": "03/05/2006",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "24"
      },
      {
        "name": "GIOVANI CHIPOPOLO",
        "fullName": "GIOVANI CHIPOPOLO",
        "popularName": "",
        "maId": "000544M99",
        "fifaId": "1JWU6Z0",
        "gender": "MALE",
        "birthDate": "03/10/1999",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "17"
      },
      {
        "name": "ANTÓNIO MULE CHITONGO",
        "fullName": "ANTÓNIO MULE CHITONGO",
        "popularName": "",
        "maId": "001123M99",
        "fifaId": "1K39NK6",
        "gender": "MALE",
        "birthDate": "08/06/1999",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "8"
      },
      {
        "name": "Francisco Cubuema Matoco",
        "fullName": "Francisco Cubuema Matoco",
        "popularName": "",
        "maId": "000888M00",
        "fifaId": "1K1JSJ8",
        "gender": "MALE",
        "birthDate": "14/02/2000",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "16"
      },
      {
        "name": "ELBER DELGADO",
        "fullName": "ELBER DELGADO",
        "popularName": "",
        "maId": "000325M91",
        "fifaId": "1JM7Y97",
        "gender": "MALE",
        "birthDate": "24/06/1991",
        "nationality": "Cabo Verde",
        "position": "GK",
        "jerseyNumber": "31"
      },
      {
        "name": "FILOMENO PINHEIRO ALBERTO GILOSO",
        "fullName": "FILOMENO PINHEIRO ALBERTO GILOSO",
        "popularName": "",
        "maId": "003650M05",
        "fifaId": "1NI87H8",
        "gender": "MALE",
        "birthDate": "27/07/2005",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "21"
      },
      {
        "name": "Nayan Gomes",
        "fullName": "Nayan Gomes",
        "popularName": "",
        "maId": "004505M99",
        "fifaId": "1PKWT84",
        "gender": "MALE",
        "birthDate": "11/12/1999",
        "nationality": "Brazil",
        "position": "GK",
        "jerseyNumber": "1"
      },
      {
        "name": "Cesar Cangui Uvi Jeremias",
        "fullName": "Cesar Cangui Uvi Jeremias",
        "popularName": "",
        "maId": "001110M03",
        "fifaId": "1K36HF0",
        "gender": "MALE",
        "birthDate": "03/05/2003",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "34"
      },
      {
        "name": "RODINO DUMBO JOSE",
        "fullName": "RODINO DUMBO JOSE",
        "popularName": "",
        "maId": "000540M95",
        "fifaId": "1JWU0L8",
        "gender": "MALE",
        "birthDate": "20/09/1995",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "25"
      },
      {
        "name": "Emanoel Júnior",
        "fullName": "Emanoel Júnior",
        "popularName": "",
        "maId": "004709M98",
        "fifaId": "1PNMJ53",
        "gender": "MALE",
        "birthDate": "14/03/1998",
        "nationality": "Brazil",
        "position": "DF",
        "jerseyNumber": "27"
      },
      {
        "name": "DANIEL ARTUR KAKA",
        "fullName": "DANIEL ARTUR KAKA",
        "popularName": "",
        "maId": "001293M03",
        "fifaId": "1L05V38",
        "gender": "MALE",
        "birthDate": "11/09/2003",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "19"
      },
      {
        "name": "António Manuel Victorino Kulica",
        "fullName": "António Manuel Victorino Kulica",
        "popularName": "",
        "maId": "006986M07",
        "fifaId": "1SCQY89",
        "gender": "MALE",
        "birthDate": "21/05/2007",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "20"
      },
      {
        "name": "ARÃO MANUEL LOLOGI",
        "fullName": "ARÃO MANUEL LOLOGI",
        "popularName": "",
        "maId": "000461M93",
        "fifaId": "1JSRPL0",
        "gender": "MALE",
        "birthDate": "06/09/1993",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "5"
      },
      {
        "name": "ZEFERINO VENANCIO LUSSATI",
        "fullName": "ZEFERINO VENANCIO LUSSATI",
        "popularName": "",
        "maId": "001233M99",
        "fifaId": "1KZR1V5",
        "gender": "MALE",
        "birthDate": "26/06/1999",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "33"
      },
      {
        "name": "VALTER MANUEL MONTEIRO",
        "fullName": "VALTER MANUEL MONTEIRO",
        "popularName": "",
        "maId": "000412M05",
        "fifaId": "1JRV1H9",
        "gender": "MALE",
        "birthDate": "31/12/2005",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "35"
      },
      {
        "name": "Guilherme Neto",
        "fullName": "Guilherme Neto",
        "popularName": "",
        "maId": "005349M93",
        "fifaId": "1PU18X2",
        "gender": "MALE",
        "birthDate": "09/10/1993",
        "nationality": "Brazil",
        "position": "DF",
        "jerseyNumber": "4"
      },
      {
        "name": "Camilo Mbule Ngongue",
        "fullName": "Camilo Mbule Ngongue",
        "popularName": "",
        "maId": "000417M01",
        "fifaId": "1JRXS05",
        "gender": "MALE",
        "birthDate": "07/12/2001",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "28"
      },
      {
        "name": "Cristovão Paciência",
        "fullName": "Cristovão Paciência",
        "popularName": "",
        "maId": "008897M92",
        "fifaId": "1UXFL56",
        "gender": "MALE",
        "birthDate": "01/06/1992",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "9"
      },
      {
        "name": "JORGE MENDES CORTE REAL CARNEIRO",
        "fullName": "JORGE MENDES CORTE REAL CARNEIRO",
        "popularName": "",
        "maId": "000448M92",
        "fifaId": "1JSJBH0",
        "gender": "MALE",
        "birthDate": "19/02/1992",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "7"
      },
      {
        "name": "TEODORO EDVALDO RITA TCHISSINGUI",
        "fullName": "TEODORO EDVALDO RITA TCHISSINGUI",
        "popularName": "",
        "maId": "000391M00",
        "fifaId": "1JRTUE9",
        "gender": "MALE",
        "birthDate": "20/02/2000",
        "nationality": "Angola",
        "position": "GK",
        "jerseyNumber": "12"
      },
      {
        "name": "Bocar Sidibé",
        "fullName": "Bocar Sidibé",
        "popularName": "",
        "maId": "006176M04",
        "fifaId": "1QVFJM7",
        "gender": "MALE",
        "birthDate": "26/01/2004",
        "nationality": "Mali",
        "position": "MF",
        "jerseyNumber": "30"
      },
      {
        "name": "Adenilson Paulo Tchingando",
        "fullName": "Adenilson Paulo Tchingando",
        "popularName": "",
        "maId": "008139M08",
        "fifaId": "1UQNTJ4",
        "gender": "MALE",
        "birthDate": "05/02/2008",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "36"
      },
      {
        "name": "Adriano Watchilala Tchombe",
        "fullName": "Adriano Watchilala Tchombe",
        "popularName": "",
        "maId": "005385M06",
        "fifaId": "1PVXHT8",
        "gender": "MALE",
        "birthDate": "22/03/2006",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "13"
      },
      {
        "name": "DEIVI MIGUEL VIEIRA",
        "fullName": "DEIVI MIGUEL VIEIRA",
        "popularName": "",
        "maId": "000445M01",
        "fifaId": "1JSJ8T3",
        "gender": "MALE",
        "birthDate": "10/03/2001",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "11"
      },
      {
        "name": "CELIO ALBERTO JUNQUEIRA ZUA",
        "fullName": "CELIO ALBERTO JUNQUEIRA ZUA",
        "popularName": "",
        "maId": "002755M03",
        "fifaId": "1M95S64",
        "gender": "MALE",
        "birthDate": "15/07/2003",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "32"
      },
      {
        "name": "Abel Samandi Mbambi",
        "fullName": "Abel Samandi Mbambi",
        "popularName": "",
        "maId": "008136M07",
        "fifaId": "1UQNSL6",
        "gender": "MALE",
        "birthDate": "26/07/2007",
        "nationality": "Angola",
        "position": "GK",
        "jerseyNumber": "40"
      },
      {
        "name": "Eduardo António Henrique capingana",
        "fullName": "Eduardo António Henrique capingana",
        "popularName": "",
        "maId": "003548M98",
        "fifaId": "1NDEMR2",
        "gender": "MALE",
        "birthDate": "15/07/1998",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "2"
      }
    ],
    "staff": [
      {
        "name": "DILSON MACUVA ALFREDO",
        "fullName": "DILSON MACUVA ALFREDO",
        "popularName": "",
        "maId": "000546M85",
        "fifaId": "1JWUI26",
        "gender": "MALE",
        "role": "",
        "nationality": "Angola"
      },
      {
        "name": "Antonio Victorino Baptista",
        "fullName": "Antonio Victorino Baptista",
        "popularName": "",
        "maId": "003004M94",
        "fifaId": "1MK97B6",
        "gender": "MALE",
        "role": "",
        "nationality": "Angola"
      },
      {
        "name": "ANTONIO BENTO",
        "fullName": "ANTONIO BENTO",
        "popularName": "",
        "maId": "000549M52",
        "fifaId": "1JWUIF1",
        "gender": "MALE",
        "role": "TMED",
        "nationality": "Angola"
      },
      {
        "name": "ABEL CASSINDA",
        "fullName": "ABEL CASSINDA",
        "popularName": "",
        "maId": "000555M86",
        "fifaId": "1JWUJX1",
        "gender": "MALE",
        "role": "KMGR",
        "nationality": "Angola"
      },
      {
        "name": "WILSON FERNANDO FARIA",
        "fullName": "WILSON FERNANDO FARIA",
        "popularName": "",
        "maId": "000556M85",
        "fifaId": "1JWUJZ5",
        "gender": "MALE",
        "role": "",
        "nationality": "Angola"
      },
      {
        "name": "Evaristo Gomes",
        "fullName": "Evaristo Gomes",
        "popularName": "",
        "maId": "003005M03",
        "fifaId": "1MK97J1",
        "gender": "MALE",
        "role": "",
        "nationality": "Angola"
      },
      {
        "name": "FELICIANO FELISBERTO JAVELA",
        "fullName": "FELICIANO FELISBERTO JAVELA",
        "popularName": "",
        "maId": "000535M89",
        "fifaId": "1JWTP61",
        "gender": "MALE",
        "role": "TMGR",
        "nationality": "Angola"
      },
      {
        "name": "Promise Mandidzidze",
        "fullName": "Promise Mandidzidze",
        "popularName": "",
        "maId": "007514M86",
        "fifaId": "1T8TKA5",
        "gender": "MALE",
        "role": "TMGR",
        "nationality": "Zimbabwe"
      },
      {
        "name": "Issac bambi Moandjambi",
        "fullName": "Issac bambi Moandjambi",
        "popularName": "",
        "maId": "007258M80",
        "fifaId": "1SQ9Y45",
        "gender": "MALE",
        "role": "PHYS",
        "nationality": "Angola"
      },
      {
        "name": "Francisco Junior Paulino",
        "fullName": "Francisco Junior Paulino",
        "popularName": "",
        "maId": "002979M67",
        "fifaId": "1MHN3M9",
        "gender": "MALE",
        "role": "",
        "nationality": "Angola"
      },
      {
        "name": "Roberto Luiz Pelliser Bianchi",
        "fullName": "Roberto Luiz Pelliser Bianchi",
        "popularName": "",
        "maId": "008405M66",
        "fifaId": "",
        "gender": "MALE",
        "role": "",
        "nationality": "Spain"
      },
      {
        "name": "BAPTISTA SABALO",
        "fullName": "BAPTISTA SABALO",
        "popularName": "",
        "maId": "000553M83",
        "fifaId": "1JWUJI1",
        "gender": "MALE",
        "role": "KMGR",
        "nationality": "Angola"
      },
      {
        "name": "Maurício Adriano Sapalo",
        "fullName": "Maurício Adriano Sapalo",
        "popularName": "",
        "maId": "008201M99",
        "fifaId": "1UR28E3",
        "gender": "MALE",
        "role": "TMGR",
        "nationality": "Angola"
      },
      {
        "name": "Pedro Fernando Sapi",
        "fullName": "Pedro Fernando Sapi",
        "popularName": "",
        "maId": "008203M73",
        "fifaId": "1UR29B0",
        "gender": "MALE",
        "role": "TMGR",
        "nationality": "Angola"
      },
      {
        "name": "AGOSTINHO SOMA",
        "fullName": "AGOSTINHO SOMA",
        "popularName": "",
        "maId": "000550M65",
        "fifaId": "1JWUII0",
        "gender": "MALE",
        "role": "PHYS",
        "nationality": "Angola"
      },
      {
        "name": "VICTORINO LUNGA VISELE",
        "fullName": "VICTORINO LUNGA VISELE",
        "popularName": "",
        "maId": "000547M84",
        "fifaId": "1JWUI52",
        "gender": "MALE",
        "role": "",
        "nationality": "Angola"
      },
      {
        "name": "CLAUDIO GRACIANO EZEQUIEL ZALA",
        "fullName": "CLAUDIO GRACIANO EZEQUIEL ZALA",
        "popularName": "",
        "maId": "000548M89",
        "fifaId": "1JWUI94",
        "gender": "MALE",
        "role": "",
        "nationality": "Angola"
      },
      {
        "name": "Artur Jaime Vilinga",
        "fullName": "Artur Jaime Vilinga",
        "popularName": "",
        "maId": "007257M86",
        "fifaId": "1SQ9Y00",
        "gender": "MALE",
        "role": "TMGR",
        "nationality": "Angola"
      },
      {
        "name": "JOAQUIM JOSE PEDRO",
        "fullName": "JOAQUIM JOSE PEDRO",
        "popularName": "",
        "maId": "000514M74",
        "fifaId": "1JV1CG5",
        "gender": "MALE",
        "role": "GKCH",
        "nationality": "Angola"
      },
      {
        "name": "Jorge Manuel Faial Delgado",
        "fullName": "Jorge Manuel Faial Delgado",
        "popularName": "",
        "maId": "003009M63",
        "fifaId": "1MK9BR4",
        "gender": "MALE",
        "role": "",
        "nationality": "Angola"
      }
    ]
  },
  {
    "sourceName": "CD Huíla",
    "teamId": "desphuila",
    "club": "Desportivo da Huíla",
    "players": [
      {
        "name": "Cristóvão Simão",
        "fullName": "Cristóvão Simão",
        "popularName": "",
        "maId": "000960M96",
        "fifaId": "1K1TTD1",
        "gender": "MALE",
        "birthDate": "01/06/1996",
        "nationality": "Angola",
        "position": "GK",
        "jerseyNumber": "1"
      },
      {
        "name": "Adilson Manuel",
        "fullName": "Adilson Manuel",
        "popularName": "",
        "maId": "000765M89",
        "fifaId": "1K0RBE1",
        "gender": "MALE",
        "birthDate": "10/03/1989",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "3"
      },
      {
        "name": "Dos Santos",
        "fullName": "ANTONIO DOS SANTOS FUTILA KINANGA",
        "popularName": "Dos Santos",
        "maId": "003460M04",
        "fifaId": "1NAKGC8",
        "gender": "MALE",
        "birthDate": "09/03/2004",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "4"
      },
      {
        "name": "Jo",
        "fullName": "JOÃO MILAGRE CHIVA SIMÕES",
        "popularName": "Jo",
        "maId": "001232M98",
        "fifaId": "1KZR148",
        "gender": "MALE",
        "birthDate": "23/03/1998",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "6"
      },
      {
        "name": "Cabibi",
        "fullName": "LEONARDO MANUEL ISOLA RAMOS",
        "popularName": "Cabibi",
        "maId": "000447M92",
        "fifaId": "1JSJ9J7",
        "gender": "MALE",
        "birthDate": "23/12/1992",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "7"
      },
      {
        "name": "Mauricio Pedro",
        "fullName": "Mauricio Pedro",
        "popularName": "",
        "maId": "000822M02",
        "fifaId": "1K15AH5",
        "gender": "MALE",
        "birthDate": "20/03/2002",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "8"
      },
      {
        "name": "José Mendes",
        "fullName": "José Mendes",
        "popularName": "",
        "maId": "000846M96",
        "fifaId": "1K175G9",
        "gender": "MALE",
        "birthDate": "12/10/1996",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "10"
      },
      {
        "name": "Emanuel Laurindo",
        "fullName": "Emanuel Laurindo",
        "popularName": "",
        "maId": "000817M01",
        "fifaId": "1K13ZM9",
        "gender": "MALE",
        "birthDate": "08/01/2001",
        "nationality": "Angola",
        "position": "GK",
        "jerseyNumber": "12"
      },
      {
        "name": "Ludy",
        "fullName": "LUCAS ELIAS ANTONIO PAULO",
        "popularName": "Ludy",
        "maId": "001158M05",
        "fifaId": "1K5T6S7",
        "gender": "MALE",
        "birthDate": "15/06/2005",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "13"
      },
      {
        "name": "Elias Daniel",
        "fullName": "Elias Daniel",
        "popularName": "",
        "maId": "000844M92",
        "fifaId": "1K173B5",
        "gender": "MALE",
        "birthDate": "11/07/1992",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "15"
      },
      {
        "name": "Milton",
        "fullName": "MILTON ALBERTO DE OLIVEIRA SUCA",
        "popularName": "Milton",
        "maId": "000458M96",
        "fifaId": "1JSRFA8",
        "gender": "MALE",
        "birthDate": "23/03/1996",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "18"
      },
      {
        "name": "Alegria Feliciano Safewange",
        "fullName": "Alegria Feliciano Safewange",
        "popularName": "",
        "maId": "002101M03",
        "fifaId": "1LIYL15",
        "gender": "MALE",
        "birthDate": "09/01/2003",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "19"
      },
      {
        "name": "Duarte Kapoela",
        "fullName": "Duarte Kapoela",
        "popularName": "",
        "maId": "000819M00",
        "fifaId": "1K141M2",
        "gender": "MALE",
        "birthDate": "25/11/2000",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "20"
      },
      {
        "name": "Jenivaldo Afonso",
        "fullName": "Jenivaldo Afonso",
        "popularName": "",
        "maId": "002620M06",
        "fifaId": "1M7IBH3",
        "gender": "MALE",
        "birthDate": "26/12/2006",
        "nationality": "Angola",
        "position": "GK",
        "jerseyNumber": "22"
      },
      {
        "name": "Florentino António",
        "fullName": "Florentino António",
        "popularName": "",
        "maId": "000849M90",
        "fifaId": "1K176V9",
        "gender": "MALE",
        "birthDate": "16/10/1990",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "23"
      },
      {
        "name": "Isidro Chingango",
        "fullName": "Isidro Chingango",
        "popularName": "",
        "maId": "000818M00",
        "fifaId": "1K140K2",
        "gender": "MALE",
        "birthDate": "08/03/2000",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "24"
      },
      {
        "name": "Milagre Carlos Simba",
        "fullName": "Milagre Carlos Simba",
        "popularName": "",
        "maId": "006020M95",
        "fifaId": "1QSTPV6",
        "gender": "MALE",
        "birthDate": "29/07/1995",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "25"
      },
      {
        "name": "Jeremias Pedro",
        "fullName": "Jeremias Pedro",
        "popularName": "",
        "maId": "000823M02",
        "fifaId": "1K15G24",
        "gender": "MALE",
        "birthDate": "07/06/2002",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "26"
      },
      {
        "name": "Jose Augusto Camati",
        "fullName": "Jose Augusto Camati",
        "popularName": "",
        "maId": "005313M02",
        "fifaId": "1PQ2JF4",
        "gender": "MALE",
        "birthDate": "02/11/2002",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "28"
      },
      {
        "name": "Pequenino Castro",
        "fullName": "Pequenino Castro",
        "popularName": "",
        "maId": "000845M93",
        "fifaId": "1K174G0",
        "gender": "MALE",
        "birthDate": "24/09/1993",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "29"
      },
      {
        "name": "Diloy Cleberson Bernardo Valerio",
        "fullName": "Diloy Cleberson Bernardo Valerio",
        "popularName": "",
        "maId": "002964M02",
        "fifaId": "1MDNGV9",
        "gender": "MALE",
        "birthDate": "21/05/2002",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "31"
      },
      {
        "name": "Jorge Ismael Jose Jose",
        "fullName": "Jorge Ismael Jose Jose",
        "popularName": "",
        "maId": "002350M04",
        "fifaId": "1LNIYJ8",
        "gender": "MALE",
        "birthDate": "24/09/2004",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "33"
      },
      {
        "name": "João Baptista Ferraz Samazanga Juny",
        "fullName": "João Baptista Ferraz Samazanga Juny",
        "popularName": "",
        "maId": "006317M06",
        "fifaId": "1R3L049",
        "gender": "MALE",
        "birthDate": "31/01/2006",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "34"
      },
      {
        "name": "Mirovaldo da Silva vandunem",
        "fullName": "Mirovaldo da Silva vandunem",
        "popularName": "",
        "maId": "008904M03",
        "fifaId": "1UXRG98",
        "gender": "MALE",
        "birthDate": "16/08/2003",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "35"
      },
      {
        "name": "Constantino Tchicundico Cassoma Tchitunda",
        "fullName": "Constantino Tchicundico Cassoma Tchitunda",
        "popularName": "",
        "maId": "001412M02",
        "fifaId": "1L3KX90",
        "gender": "MALE",
        "birthDate": "12/03/2002",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "32"
      },
      {
        "name": "António Pena",
        "fullName": "António Pena",
        "popularName": "",
        "maId": "000959M96",
        "fifaId": "1K1TSN8",
        "gender": "MALE",
        "birthDate": "14/01/1996",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "27"
      },
      {
        "name": "Angelo Cangu",
        "fullName": "Angelo Cangu",
        "popularName": "",
        "maId": "000853M98",
        "fifaId": "1K17IS6",
        "gender": "MALE",
        "birthDate": "07/12/1998",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "21"
      },
      {
        "name": "NSAMBO KATENDI",
        "fullName": "NSAMBO KATENDI",
        "popularName": "",
        "maId": "000940M04",
        "fifaId": "1K1SFM9",
        "gender": "MALE",
        "birthDate": "18/02/2004",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "2"
      }
    ],
    "staff": [
      {
        "name": "Jojo",
        "fullName": "João António",
        "popularName": "Jojo",
        "maId": "000831M67",
        "fifaId": "1K15PL1",
        "gender": "MALE",
        "role": "PHYS",
        "nationality": "Angola"
      },
      {
        "name": "Luis Borge",
        "fullName": "José Borges",
        "popularName": "Luis Borge",
        "maId": "000858M63",
        "fifaId": "1K1EWX7",
        "gender": "MALE",
        "role": "PTNR",
        "nationality": "Angola"
      },
      {
        "name": "Alfredo Calunganga",
        "fullName": "Alfredo Calunganga",
        "popularName": "",
        "maId": "000850M86",
        "fifaId": "1K177K5",
        "gender": "MALE",
        "role": "",
        "nationality": "Angola"
      },
      {
        "name": "Sidney",
        "fullName": "Sidney Candeias",
        "popularName": "Sidney",
        "maId": "000847M87",
        "fifaId": "1K17646",
        "gender": "MALE",
        "role": "",
        "nationality": "Angola"
      },
      {
        "name": "Luis",
        "fullName": "Luis Tchilamba Daniel",
        "popularName": "Luis",
        "maId": "003172M87",
        "fifaId": "1MVM2R1",
        "gender": "MALE",
        "role": "TCSC",
        "nationality": "Angola"
      },
      {
        "name": "Ezequias",
        "fullName": "Ezequias Domingos",
        "popularName": "Ezequias",
        "maId": "000828M64",
        "fifaId": "1K15KV6",
        "gender": "MALE",
        "role": "",
        "nationality": "Angola"
      },
      {
        "name": "Zela Barroso Emanuel",
        "fullName": "Zela Barroso Emanuel",
        "popularName": "",
        "maId": "002968M71",
        "fifaId": "1ME3PE8",
        "gender": "MALE",
        "role": "",
        "nationality": "Angola"
      },
      {
        "name": "Neto",
        "fullName": "Joao Capitao Gomes",
        "popularName": "Neto",
        "maId": "004750M84",
        "fifaId": "1PNMUF7",
        "gender": "MALE",
        "role": "TMED",
        "nationality": "Angola"
      },
      {
        "name": "Victor Tembo Memo",
        "fullName": "Victor Tembo Memo",
        "popularName": "",
        "maId": "007731M98",
        "fifaId": "1TFVGY8",
        "gender": "MALE",
        "role": "DOCT",
        "nationality": "Angola"
      },
      {
        "name": "Man-moi",
        "fullName": "Avelino Moises",
        "popularName": "Man-moi",
        "maId": "000500M67",
        "fifaId": "1JUMIC4",
        "gender": "MALE",
        "role": "KMGR",
        "nationality": "Angola"
      },
      {
        "name": "Santos",
        "fullName": "David Santos",
        "popularName": "Santos",
        "maId": "000832M66",
        "fifaId": "1K15PX7",
        "gender": "MALE",
        "role": "TMED",
        "nationality": "Angola"
      },
      {
        "name": "Luis Sipilante",
        "fullName": "Luis Sipilante",
        "popularName": "",
        "maId": "000826M79",
        "fifaId": "1K15JH1",
        "gender": "MALE",
        "role": "TMED",
        "nationality": "Angola"
      },
      {
        "name": "Bebe",
        "fullName": "António Tchimbungo",
        "popularName": "Bebe",
        "maId": "000829M69",
        "fifaId": "1K15NN8",
        "gender": "MALE",
        "role": "TMGR",
        "nationality": "Angola"
      },
      {
        "name": "Paulo Torres",
        "fullName": "Paulo Torres",
        "popularName": "Paulo Torres",
        "maId": "000857M71",
        "fifaId": "1K1ETK8",
        "gender": "MALE",
        "role": "HDCH",
        "nationality": "Portugal"
      }
    ]
  },
  {
    "sourceName": "1º de Agosto",
    "teamId": "dago",
    "club": "CD 1.º de Agosto",
    "players": [
      {
        "name": "Axel Gaudêncio Mabaqui de Sousa Axel",
        "fullName": "Axel Gaudêncio Mabaqui de Sousa Axel",
        "popularName": "",
        "maId": "002187M03",
        "fifaId": "1LJU8Q3",
        "gender": "MALE",
        "birthDate": "05/05/2003",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "8"
      },
      {
        "name": "Bonifacio Francisco Caetano",
        "fullName": "Bonifacio Francisco Caetano",
        "popularName": "",
        "maId": "000423M93",
        "fifaId": "1JRYBB6",
        "gender": "MALE",
        "birthDate": "09/06/1993",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "5"
      },
      {
        "name": "MILTON ANTONIO CANDIDO",
        "fullName": "MILTON ANTONIO CANDIDO",
        "popularName": "",
        "maId": "005431M03",
        "fifaId": "1PXU6F2",
        "gender": "MALE",
        "birthDate": "05/01/2003",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "2"
      },
      {
        "name": "Felisberto Kanjeque Lourenço Carvalho",
        "fullName": "Felisberto Kanjeque Lourenço Carvalho",
        "popularName": "",
        "maId": "004958M08",
        "fifaId": "1PNY6E7",
        "gender": "MALE",
        "birthDate": "30/10/2008",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": ""
      },
      {
        "name": "Francisco Carlos Chilumbo",
        "fullName": "Francisco Carlos Chilumbo",
        "popularName": "",
        "maId": "001234M00",
        "fifaId": "1KZR6C1",
        "gender": "MALE",
        "birthDate": "25/12/2000",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "20"
      },
      {
        "name": "Samu Tshibamba Dago",
        "fullName": "Samu Tshibamba Dago",
        "popularName": "",
        "maId": "000441M97",
        "fifaId": "1JSJ4J2",
        "gender": "MALE",
        "birthDate": "03/09/1997",
        "nationality": "Republic of the Congo",
        "position": "",
        "jerseyNumber": "17"
      },
      {
        "name": "FERNANDO LOPES DE ALMEIDA",
        "fullName": "FERNANDO LOPES DE ALMEIDA",
        "popularName": "",
        "maId": "000634M01",
        "fifaId": "1JZ3MQ2",
        "gender": "MALE",
        "birthDate": "09/01/2001",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "1"
      },
      {
        "name": "ERIQUE JOAQUIM MANUEL DE JESUS",
        "fullName": "ERIQUE JOAQUIM MANUEL DE JESUS",
        "popularName": "",
        "maId": "005437M98",
        "fifaId": "1PXWMN6",
        "gender": "MALE",
        "birthDate": "18/02/1998",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "24"
      },
      {
        "name": "Simao Dianzenza",
        "fullName": "Simao Dianzenza",
        "popularName": "",
        "maId": "000451M99",
        "fifaId": "1JSKTW9",
        "gender": "MALE",
        "birthDate": "30/12/1999",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "3"
      },
      {
        "name": "ANTONIO FRANCISCO DOMINGOS",
        "fullName": "ANTONIO FRANCISCO DOMINGOS",
        "popularName": "",
        "maId": "005428M02",
        "fifaId": "1PXS6R1",
        "gender": "MALE",
        "birthDate": "07/12/2002",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "7"
      },
      {
        "name": "Eliseu Sebastião Francisco ESCALÃO DE FORMAÇÃO",
        "fullName": "Eliseu Sebastião Francisco ESCALÃO DE FORMAÇÃO",
        "popularName": "",
        "maId": "004967M09",
        "fifaId": "1PNY6S0",
        "gender": "MALE",
        "birthDate": "07/02/2009",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": ""
      },
      {
        "name": "Jose Macaia ganga",
        "fullName": "Jose Macaia ganga",
        "popularName": "",
        "maId": "001997M94",
        "fifaId": "1JP2N29",
        "gender": "MALE",
        "birthDate": "24/03/1994",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "16"
      },
      {
        "name": "Enoque José Kabesa",
        "fullName": "Enoque José Kabesa",
        "popularName": "",
        "maId": "005394M01",
        "fifaId": "1PWAAY2",
        "gender": "MALE",
        "birthDate": "26/05/2001",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "23"
      },
      {
        "name": "Venancio Landu kukula",
        "fullName": "Venancio Landu kukula",
        "popularName": "",
        "maId": "000436M95",
        "fifaId": "1JSF794",
        "gender": "MALE",
        "birthDate": "11/06/1995",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "15"
      },
      {
        "name": "Florindo Machado",
        "fullName": "Florindo Machado",
        "popularName": "",
        "maId": "000843M94",
        "fifaId": "1K16NJ0",
        "gender": "MALE",
        "birthDate": "04/08/1994",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "9"
      },
      {
        "name": "Bruno de Jesus Manuel",
        "fullName": "Bruno de Jesus Manuel",
        "popularName": "",
        "maId": "000437M95",
        "fifaId": "1JSF904",
        "gender": "MALE",
        "birthDate": "25/09/1995",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "6"
      },
      {
        "name": "ANSELMO MWENI",
        "fullName": "ANSELMO MWENI",
        "popularName": "",
        "maId": "001210M98",
        "fifaId": "1KYQMU3",
        "gender": "MALE",
        "birthDate": "05/01/1998",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "22"
      },
      {
        "name": "BENÇÃO NBONGO EVARISTO NZINGA",
        "fullName": "BENÇÃO NBONGO EVARISTO NZINGA",
        "popularName": "",
        "maId": "005429M03",
        "fifaId": "1PXS7W4",
        "gender": "MALE",
        "birthDate": "05/12/2003",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "36"
      },
      {
        "name": "Obed Mayamb Mukokiani Obed",
        "fullName": "Obed Mayamb Mukokiani Obed",
        "popularName": "",
        "maId": "003026M94",
        "fifaId": "1ML75M8",
        "gender": "MALE",
        "birthDate": "24/09/1994",
        "nationality": "Democratic Republic of the Congo",
        "position": "",
        "jerseyNumber": "14"
      },
      {
        "name": "AFONSO DOS SANTOS PAXE",
        "fullName": "AFONSO DOS SANTOS PAXE",
        "popularName": "",
        "maId": "005430M03",
        "fifaId": "1PXU511",
        "gender": "MALE",
        "birthDate": "24/04/2003",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "19"
      },
      {
        "name": "Carvalho dos Santos",
        "fullName": "Carvalho dos Santos",
        "popularName": "",
        "maId": "000978M01",
        "fifaId": "1K26F45",
        "gender": "MALE",
        "birthDate": "09/08/2001",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "27"
      },
      {
        "name": "CALEBI YANDA",
        "fullName": "CALEBI YANDA",
        "popularName": "",
        "maId": "000327M99",
        "fifaId": "1JM8058",
        "gender": "MALE",
        "birthDate": "20/04/1999",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "10"
      },
      {
        "name": "Fernando Inácio Costa",
        "fullName": "Fernando Inácio Costa",
        "popularName": "",
        "maId": "004963M05",
        "fifaId": "1PNY6K8",
        "gender": "MALE",
        "birthDate": "07/07/2005",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "11"
      },
      {
        "name": "Cliver Camango Andre",
        "fullName": "Cliver Camango Andre",
        "popularName": "",
        "maId": "002767M04",
        "fifaId": "1M9F1P0",
        "gender": "MALE",
        "birthDate": "02/07/2004",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "18"
      },
      {
        "name": "Felix Bulaya",
        "fullName": "Felix Bulaya",
        "popularName": "",
        "maId": "007639M96",
        "fifaId": "1TDC7R7",
        "gender": "MALE",
        "birthDate": "18/12/1996",
        "nationality": "Zambia",
        "position": "",
        "jerseyNumber": "28"
      },
      {
        "name": "Luciano Manuel dos Santos",
        "fullName": "Luciano Manuel dos Santos",
        "popularName": "",
        "maId": "008964M02",
        "fifaId": "1V12EK6",
        "gender": "MALE",
        "birthDate": "08/08/2002",
        "nationality": "Angola",
        "position": "",
        "jerseyNumber": "25"
      }
    ],
    "staff": [
      {
        "name": "Antônio Filipe de Almeida",
        "fullName": "Antônio Filipe de Almeida",
        "popularName": "",
        "maId": "000965M83",
        "fifaId": "1K1V696",
        "gender": "MALE",
        "role": "PHYS",
        "nationality": "Angola"
      },
      {
        "name": "Gelson Inácio Mendes Antonio",
        "fullName": "Gelson Inácio Mendes Antonio",
        "popularName": "",
        "maId": "000968M92",
        "fifaId": "1K1VB66",
        "gender": "MALE",
        "role": "PHYS",
        "nationality": "Angola"
      },
      {
        "name": "Mario de Sousa Calado",
        "fullName": "Mario de Sousa Calado",
        "popularName": "",
        "maId": "007335M63",
        "fifaId": "1T0DJE3",
        "gender": "MALE",
        "role": "TMGR",
        "nationality": "Angola"
      },
      {
        "name": "Virgilio Paez Fernandez",
        "fullName": "Virgilio Paez Fernandez",
        "popularName": "",
        "maId": "000444M62",
        "fifaId": "1JSJ6H8",
        "gender": "MALE",
        "role": "DOCT",
        "nationality": "Cuba"
      },
      {
        "name": "Alejandro Janes Gutierrez",
        "fullName": "Alejandro Janes Gutierrez",
        "popularName": "",
        "maId": "000966M83",
        "fifaId": "1K1VAT2",
        "gender": "MALE",
        "role": "PHYS",
        "nationality": "Cuba"
      },
      {
        "name": "Edgar Jeronimo",
        "fullName": "Edgar Jeronimo",
        "popularName": "",
        "maId": "002965M79",
        "fifaId": "1MDZQU6",
        "gender": "MALE",
        "role": "AMGR",
        "nationality": "Angola"
      },
      {
        "name": "Feliciano Antonio Madalena",
        "fullName": "Feliciano Antonio Madalena",
        "popularName": "",
        "maId": "000967M61",
        "fifaId": "1K1VB02",
        "gender": "MALE",
        "role": "PHYS",
        "nationality": "Angola"
      },
      {
        "name": "Jose Manuel Marcelino",
        "fullName": "Jose Manuel Marcelino",
        "popularName": "",
        "maId": "000443M69",
        "fifaId": "1JSJ6F5",
        "gender": "MALE",
        "role": "TMGR",
        "nationality": "Angola"
      },
      {
        "name": "Andrade Jose Mendes",
        "fullName": "Andrade Jose Mendes",
        "popularName": "",
        "maId": "006498F69",
        "fifaId": "1S8UKT1",
        "gender": "FEMALE",
        "role": "PHYS",
        "nationality": "Angola"
      },
      {
        "name": "Filipe Nanza",
        "fullName": "Filipe Nanza",
        "popularName": "",
        "maId": "000439M69",
        "fifaId": "1JSFXH8",
        "gender": "MALE",
        "role": "HDCH",
        "nationality": "Angola"
      },
      {
        "name": "António Francisco Alves Pinto PREPARADOR FÍSICO",
        "fullName": "António Francisco Alves Pinto PREPARADOR FÍSICO",
        "popularName": "",
        "maId": "003234M87",
        "fifaId": "1MZIDU5",
        "gender": "MALE",
        "role": "PTNR",
        "nationality": "Angola"
      },
      {
        "name": "Mario Jorge da Silva Queiroz",
        "fullName": "Mario Jorge da Silva Queiroz",
        "popularName": "",
        "maId": "003387M82",
        "fifaId": "1N8QUB6",
        "gender": "MALE",
        "role": "TMGR",
        "nationality": "Angola"
      },
      {
        "name": "Untonesa Avelino Sampaio",
        "fullName": "Untonesa Avelino Sampaio",
        "popularName": "",
        "maId": "003031M77",
        "fifaId": "1MMQHJ4",
        "gender": "MALE",
        "role": "TMGR",
        "nationality": "Angola"
      },
      {
        "name": "Ivo Raimundo Traça",
        "fullName": "Ivo Raimundo Traça",
        "popularName": "",
        "maId": "000374M61",
        "fifaId": "1JRLEF7",
        "gender": "MALE",
        "role": "ASCH",
        "nationality": "Angola"
      },
      {
        "name": "Thomas Napoleão Cersar",
        "fullName": "Thomas Napoleão Cersar",
        "popularName": "",
        "maId": "007220M64",
        "fifaId": "1SL00E1",
        "gender": "MALE",
        "role": "GKCH",
        "nationality": "Angola"
      }
    ]
  },
  {
    "sourceName": "Kabuscorp",
    "teamId": "kabuscorp",
    "club": "Kabuscorp SC",
    "players": [
      {
        "name": "Mankoka Hegene Afonso",
        "fullName": "Mankoka Hegene Afonso",
        "popularName": "",
        "maId": "000371M01",
        "fifaId": "1JRKU39",
        "gender": "MALE",
        "birthDate": "25/01/2001",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "18"
      },
      {
        "name": "Saombe Sukuakueche Ángelo Jorge",
        "fullName": "Saombe Sukuakueche Ángelo Jorge",
        "popularName": "",
        "maId": "007238M00",
        "fifaId": "1SNB179",
        "gender": "MALE",
        "birthDate": "14/06/2000",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "5"
      },
      {
        "name": "Eliseu",
        "fullName": "ELISEU CABANGA",
        "popularName": "Eliseu",
        "maId": "000631M97",
        "fifaId": "1JYP8V8",
        "gender": "MALE",
        "birthDate": "13/02/1997",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "3"
      },
      {
        "name": "Aluízio Joel André Cacharamba",
        "fullName": "Aluízio Joel André Cacharamba",
        "popularName": "",
        "maId": "004835M05",
        "fifaId": "1PNR1R0",
        "gender": "MALE",
        "birthDate": "16/11/2005",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "27"
      },
      {
        "name": "TEODORO FERNANDES CORREIA",
        "fullName": "TEODORO FERNANDES CORREIA",
        "popularName": "",
        "maId": "001831M02",
        "fifaId": "1LGPB81",
        "gender": "MALE",
        "birthDate": "17/09/2002",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "11"
      },
      {
        "name": "JOÃO BAPTISTA MISSENGA DE NASCIMENTO",
        "fullName": "JOÃO BAPTISTA MISSENGA DE NASCIMENTO",
        "popularName": "",
        "maId": "000355M98",
        "fifaId": "1JRIUE5",
        "gender": "MALE",
        "birthDate": "07/10/1998",
        "nationality": "Angola",
        "position": "GK",
        "jerseyNumber": "12"
      },
      {
        "name": "ADAIR GARCIA DOMINGOS",
        "fullName": "ADAIR GARCIA DOMINGOS",
        "popularName": "",
        "maId": "001833M03",
        "fifaId": "1LGPGY7",
        "gender": "MALE",
        "birthDate": "12/11/2003",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "4"
      },
      {
        "name": "DIÓGENES CAPEMBA JOÃO",
        "fullName": "DIÓGENES CAPEMBA JOÃO",
        "popularName": "",
        "maId": "000395M97",
        "fifaId": "1JRTXH4",
        "gender": "MALE",
        "birthDate": "01/01/1997",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "32"
      },
      {
        "name": "DANIEL KILOLA",
        "fullName": "DANIEL KILOLA",
        "popularName": "",
        "maId": "000326M99",
        "fifaId": "1JM7ZR2",
        "gender": "MALE",
        "birthDate": "06/07/1999",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "15"
      },
      {
        "name": "Zamorano Lopes",
        "fullName": "Zamorano Lopes",
        "popularName": "",
        "maId": "001136M01",
        "fifaId": "1K4A836",
        "gender": "MALE",
        "birthDate": "18/08/2001",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "2"
      },
      {
        "name": "MONA MALECO",
        "fullName": "CELESTINO LUIS MALECO",
        "popularName": "MONA MALECO",
        "maId": "000576M03",
        "fifaId": "1JXICB5",
        "gender": "MALE",
        "birthDate": "04/11/2003",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "17"
      },
      {
        "name": "ARTUR MALUNGO",
        "fullName": "ARTUR MALUNGO",
        "popularName": "",
        "maId": "000936M98",
        "fifaId": "1K1SEN7",
        "gender": "MALE",
        "birthDate": "08/01/1998",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "14"
      },
      {
        "name": "Henock Mangindula",
        "fullName": "Henock Mangindula",
        "popularName": "",
        "maId": "003056M99",
        "fifaId": "1MPPSB5",
        "gender": "MALE",
        "birthDate": "20/11/1999",
        "nationality": "Democratic Republic of the Congo",
        "position": "DF",
        "jerseyNumber": "16"
      },
      {
        "name": "JORGE MANUEL PINTO",
        "fullName": "JORGE MANUEL PINTO",
        "popularName": "",
        "maId": "007766M08",
        "fifaId": "1TGWGG5",
        "gender": "MALE",
        "birthDate": "26/12/2008",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "35"
      },
      {
        "name": "MVEMBA MATONDO KUANZAMBI",
        "fullName": "MVEMBA MATONDO KUANZAMBI",
        "popularName": "",
        "maId": "006297M99",
        "fifaId": "1QXNL72",
        "gender": "MALE",
        "birthDate": "03/03/1999",
        "nationality": "Angola",
        "position": "DF",
        "jerseyNumber": "28"
      },
      {
        "name": "AUGUSTO MONTEIRO MUALUCANO",
        "fullName": "AUGUSTO MONTEIRO MUALUCANO",
        "popularName": "",
        "maId": "000392M98",
        "fifaId": "1JRTVA7",
        "gender": "MALE",
        "birthDate": "01/01/1998",
        "nationality": "Angola",
        "position": "GK",
        "jerseyNumber": "22"
      },
      {
        "name": "BAYALA NSIMBA",
        "fullName": "BAYALA NSIMBA",
        "popularName": "",
        "maId": "003262M05",
        "fifaId": "1N3UHM6",
        "gender": "MALE",
        "birthDate": "07/07/2005",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "7"
      },
      {
        "name": "JOAQUIM PACIENCIA",
        "fullName": "JOAQUIM PACIENCIA",
        "popularName": "",
        "maId": "000331M96",
        "fifaId": "1JM8HD7",
        "gender": "MALE",
        "birthDate": "07/07/1996",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "19"
      },
      {
        "name": "ENOQUE BENJAMIM TULA",
        "fullName": "ENOQUE BENJAMIM TULA",
        "popularName": "",
        "maId": "000536M02",
        "fifaId": "1JWTS88",
        "gender": "MALE",
        "birthDate": "01/07/2002",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "20"
      },
      {
        "name": "José Semedo Vunge",
        "fullName": "José Semedo Vunge",
        "popularName": "",
        "maId": "001072M96",
        "fifaId": "1K2PK58",
        "gender": "MALE",
        "birthDate": "23/08/1996",
        "nationality": "Angola",
        "position": "MF",
        "jerseyNumber": "10"
      },
      {
        "name": "Alberto Elizeu Xavier",
        "fullName": "Alberto Elizeu Xavier",
        "popularName": "",
        "maId": "000425M99",
        "fifaId": "1JS6M05",
        "gender": "MALE",
        "birthDate": "29/08/1999",
        "nationality": "Angola",
        "position": "FWD",
        "jerseyNumber": "29"
      },
      {
        "name": "MAZEBO MAVAMBO JOÃO",
        "fullName": "MAZEBO MAVAMBO JOÃO",
        "popularName": "",
        "maId": "002869M04",
        "fifaId": "1MA68G7",
        "gender": "MALE",
        "birthDate": "08/06/2006",
        "nationality": "Angola",
        "position": "GK",
        "jerseyNumber": "21"
      },
      {
        "name": "LIWANDA JOSLIN NDONGALA",
        "fullName": "LIWANDA JOSLIN NDONGALA",
        "popularName": "",
        "maId": "009045M02",
        "fifaId": "1V363C3",
        "gender": "MALE",
        "birthDate": "28/10/2002",
        "nationality": "Democratic Republic of the Congo",
        "position": "DF",
        "jerseyNumber": "13"
      },
      {
        "name": "Tresor Kuyu Nona",
        "fullName": "Tresor Kuyu Nona",
        "popularName": "",
        "maId": "007240M01",
        "fifaId": "1SNEZ57",
        "gender": "MALE",
        "birthDate": "29/08/2001",
        "nationality": "Democratic Republic of the Congo",
        "position": "FWD",
        "jerseyNumber": "25"
      },
      {
        "name": "MBALI MONGBONGO SEM",
        "fullName": "MBALI MONGBONGO SEM",
        "popularName": "",
        "maId": "009044M03",
        "fifaId": "1V363A9",
        "gender": "MALE",
        "birthDate": "04/08/2003",
        "nationality": "Democratic Republic of the Congo",
        "position": "MF",
        "jerseyNumber": "8"
      }
    ],
    "staff": [
      {
        "name": "JORGE DE ALMEIDA",
        "fullName": "JORGE DE ALMEIDA",
        "popularName": "",
        "maId": "001838M73",
        "fifaId": "1LGPM02",
        "gender": "MALE",
        "role": "TMED",
        "nationality": "Angola"
      },
      {
        "name": "MANUEL FRANCISCO ANDRÉ",
        "fullName": "MANUEL FRANCISCO ANDRÉ",
        "popularName": "",
        "maId": "001846M94",
        "fifaId": "1LGSZS7",
        "gender": "MALE",
        "role": "KMGR",
        "nationality": "Angola"
      },
      {
        "name": "Roberto Cambundo",
        "fullName": "Roberto Cambundo",
        "popularName": "",
        "maId": "002978M69",
        "fifaId": "1MHJ760",
        "gender": "MALE",
        "role": "TMGR",
        "nationality": "Angola"
      },
      {
        "name": "Olavo Patricio De Almeida Miguel",
        "fullName": "Olavo Patricio De Almeida Miguel",
        "popularName": "",
        "maId": "005444M86",
        "fifaId": "1PZDSY4",
        "gender": "MALE",
        "role": "TMED",
        "nationality": "Angola"
      },
      {
        "name": "JOSÉ DOMINGOS",
        "fullName": "JOSÉ DOMINGOS",
        "popularName": "",
        "maId": "001837M63",
        "fifaId": "1LGPLZ3",
        "gender": "MALE",
        "role": "",
        "nationality": "Angola"
      },
      {
        "name": "FILIPE DUCUL0",
        "fullName": "FILIPE DUCUL0",
        "popularName": "",
        "maId": "000948M90",
        "fifaId": "1K1SMR9",
        "gender": "MALE",
        "role": "TCSC",
        "nationality": "Angola"
      },
      {
        "name": "MARCELO VITOR FROEDER CHRISPINIANO",
        "fullName": "MARCELO VITOR FROEDER CHRISPINIANO",
        "popularName": "",
        "maId": "008244M84",
        "fifaId": "",
        "gender": "MALE",
        "role": "PTNR",
        "nationality": "Angola"
      },
      {
        "name": "Raul Mendonça Gaspar",
        "fullName": "Raul Mendonça Gaspar",
        "popularName": "",
        "maId": "003033M67",
        "fifaId": "1MMQI51",
        "gender": "MALE",
        "role": "TSTF",
        "nationality": "Angola"
      },
      {
        "name": "ADRIANO LANCETTA",
        "fullName": "ADRIANO LANCETTA",
        "popularName": "",
        "maId": "007965M73",
        "fifaId": "1TYZR92",
        "gender": "MALE",
        "role": "PTNR",
        "nationality": "Brazil"
      },
      {
        "name": "DANIEL MABATA",
        "fullName": "DANIEL MABATA",
        "popularName": "",
        "maId": "007732M86",
        "fifaId": "1TFVSW6",
        "gender": "MALE",
        "role": "TSTF",
        "nationality": "Angola"
      },
      {
        "name": "Salomão Pedro Manuel",
        "fullName": "Salomão Pedro Manuel",
        "popularName": "",
        "maId": "003110M81",
        "fifaId": "1MS2G50",
        "gender": "MALE",
        "role": "PHYS",
        "nationality": "Angola"
      },
      {
        "name": "INÁCIO SANDUNDU MANUEL",
        "fullName": "INÁCIO SANDUNDU MANUEL",
        "popularName": "",
        "maId": "001845M82",
        "fifaId": "1LGSZQ3",
        "gender": "MALE",
        "role": "KMGR",
        "nationality": "Angola"
      },
      {
        "name": "LEONARDO MARTINS NEIVA",
        "fullName": "LEONARDO MARTINS NEIVA",
        "popularName": "",
        "maId": "007949M77",
        "fifaId": "",
        "gender": "MALE",
        "role": "HDCH",
        "nationality": "Brazil"
      },
      {
        "name": "MARCELO MUNIZ MATOS",
        "fullName": "MARCELO MUNIZ MATOS",
        "popularName": "",
        "maId": "008260M81",
        "fifaId": "1URSHN9",
        "gender": "MALE",
        "role": "GKCH",
        "nationality": "Brazil"
      },
      {
        "name": "PEDRO DE OLIVEIRA",
        "fullName": "PEDRO DE OLIVEIRA",
        "popularName": "",
        "maId": "001839M65",
        "fifaId": "1LGPM15",
        "gender": "MALE",
        "role": "MASG",
        "nationality": "Angola"
      },
      {
        "name": "BENTO DOS SANTOS",
        "fullName": "BENTO DOS SANTOS",
        "popularName": "",
        "maId": "001836M65",
        "fifaId": "1LGPLY5",
        "gender": "MALE",
        "role": "TSTF",
        "nationality": "Angola"
      }
    ]
  }
] as const;
