// Calendário oficial publicado pelo gestor ANCAF.
// Sincronizado da API pública do ANCAF Calendar, campeonato n.º 1567.
// Esta cópia é o fallback fiel usado antes da resposta dinâmica da API.
import type { Match } from './data';

export const PUBLISHED_ANCAF_CALENDAR_SOURCE = {
  "system": "ANCAF_CALENDAR",
  "accessCode": "1567",
  "technicalSeed": "1567",
  "fingerprint": "653bdd95f7668734e77fc1005fa32455d1c5e5045e5c5a22b0972005e50b0039",
  "season": "2026/2027",
  "generatedAt": "2026-08-07T17:20:40.270394+00:00",
  "rounds": 30,
  "matches": 240
} as const;

export const PUBLISHED_MATCHES_2026_27: Match[] = [
  {
    "id": "m27-1-4",
    "round": 1,
    "homeTeamId": "lundasul",
    "awayTeamId": "petro",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-21T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-1-2",
    "round": 1,
    "homeTeamId": "bravos",
    "awayTeamId": "sagrada",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-22T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-1-3",
    "round": 1,
    "homeTeamId": "dago",
    "awayTeamId": "desphuila",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-22T15:00:00+01:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-1-7",
    "round": 1,
    "homeTeamId": "cabinda",
    "awayTeamId": "libolo",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-22T15:00:00+01:00",
    "stadium": "Estádio Vicy António - Uige",
    "status": "scheduled"
  },
  {
    "id": "m27-1-1",
    "round": 1,
    "homeTeamId": "fcluanda",
    "awayTeamId": "caala",
    "homeTeam": "FC Luanda",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-23T15:00:00+01:00",
    "stadium": "Campo França N´Dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-1-6",
    "round": 1,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-23T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled"
  },
  {
    "id": "m27-1-8",
    "round": 1,
    "homeTeamId": "saosalvador",
    "awayTeamId": "interclube",
    "homeTeam": "São Salvador",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-23T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled"
  },
  {
    "id": "m27-1-5",
    "round": 1,
    "homeTeamId": "wiliete",
    "awayTeamId": "lobito",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-23T17:30:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-2-3",
    "round": 2,
    "homeTeamId": "cabinda",
    "awayTeamId": "desphuila",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-26T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled"
  },
  {
    "id": "m27-2-1",
    "round": 2,
    "homeTeamId": "caala",
    "awayTeamId": "wiliete",
    "homeTeam": "CR Caála",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 1,
    "awayScore": 2,
    "date": "2026-08-27T16:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "finished",
    "halfTimeScore": "1-1"
  },
  {
    "id": "m27-2-7",
    "round": 2,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "dago",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 1,
    "awayScore": 2,
    "date": "2026-08-27T15:30:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "finished",
    "halfTimeScore": "0-1",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-2-2",
    "round": 2,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "lundasul",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 1,
    "awayScore": 1,
    "date": "2026-08-29T15:30:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "finished",
    "halfTimeScore": "1-0",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-2-4",
    "round": 2,
    "homeTeamId": "sagrada",
    "awayTeamId": "saosalvador",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "São Salvador",
    "homeScore": 3,
    "awayScore": 1,
    "date": "2026-08-29T15:00:00+01:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "finished",
    "halfTimeScore": "1-0"
  },
  {
    "id": "m27-2-5",
    "round": 2,
    "homeTeamId": "interclube",
    "awayTeamId": "fcluanda",
    "homeTeam": "GD Interclube",
    "awayTeam": "FC Luanda",
    "homeScore": 2,
    "awayScore": 1,
    "date": "2026-08-28T15:30:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "finished",
    "halfTimeScore": "0-0",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-2-6",
    "round": 2,
    "homeTeamId": "libolo",
    "awayTeamId": "bravos",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-31T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-2-8",
    "round": 2,
    "homeTeamId": "lobito",
    "awayTeamId": "petro",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 2,
    "halfTimeScore": "0-0",
    "date": "2026-08-30T15:30:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "finished",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-3-3",
    "round": 3,
    "homeTeamId": "sagrada",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-26T15:00:00+01:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-3-7",
    "round": 3,
    "homeTeamId": "petro",
    "awayTeamId": "libolo",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-26T16:30:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-3-2",
    "round": 3,
    "homeTeamId": "desphuila",
    "awayTeamId": "wiliete",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 1,
    "date": "2026-08-31T15:30:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "finished"
  },
  {
    "id": "m27-3-6",
    "round": 3,
    "homeTeamId": "dago",
    "awayTeamId": "interclube",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-02T15:30:00+01:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-3-1",
    "round": 3,
    "homeTeamId": "lundasul",
    "awayTeamId": "caala",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-05T15:00:00+01:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-3-8",
    "round": 3,
    "homeTeamId": "lobito",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-05T15:30:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-3-4",
    "round": 3,
    "homeTeamId": "fcluanda",
    "awayTeamId": "cabinda",
    "homeTeam": "FC Luanda",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-05T15:30:00+01:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-3-5",
    "round": 3,
    "homeTeamId": "bravos",
    "awayTeamId": "saosalvador",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "São Salvador",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-06T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-4-5",
    "round": 4,
    "homeTeamId": "cabinda",
    "awayTeamId": "dago",
    "homeTeam": "FC Cabinda",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-09T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-4-7",
    "round": 4,
    "homeTeamId": "interclube",
    "awayTeamId": "lobito",
    "homeTeam": "GD Interclube",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-10T15:30:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-4-8",
    "round": 4,
    "homeTeamId": "libolo",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-12T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-4-1",
    "round": 4,
    "homeTeamId": "caala",
    "awayTeamId": "desphuila",
    "homeTeam": "CR Caála",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-13T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled"
  },
  {
    "id": "m27-4-2",
    "round": 4,
    "homeTeamId": "lundasul",
    "awayTeamId": "sagrada",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-13T15:00:00+01:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-4-3",
    "round": 4,
    "homeTeamId": "wiliete",
    "awayTeamId": "fcluanda",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-13T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled"
  },
  {
    "id": "m27-4-4",
    "round": 4,
    "homeTeamId": "bravos",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-16T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-4-6",
    "round": 4,
    "homeTeamId": "saosalvador",
    "awayTeamId": "petro",
    "homeTeam": "São Salvador",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-16T15:30:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-5-1",
    "round": 5,
    "homeTeamId": "caala",
    "awayTeamId": "bravos",
    "homeTeam": "CR Caála",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-19T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled"
  },
  {
    "id": "m27-5-4",
    "round": 5,
    "homeTeamId": "desphuila",
    "awayTeamId": "lobito",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-19T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled"
  },
  {
    "id": "m27-5-2",
    "round": 5,
    "homeTeamId": "dago",
    "awayTeamId": "fcluanda",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-19T15:30:00+01:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-5-7",
    "round": 5,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "interclube",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-19T15:30:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-5-5",
    "round": 5,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "lundasul",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-20T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled"
  },
  {
    "id": "m27-5-6",
    "round": 5,
    "homeTeamId": "wiliete",
    "awayTeamId": "libolo",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-20T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled"
  },
  {
    "id": "m27-5-8",
    "round": 5,
    "homeTeamId": "saosalvador",
    "awayTeamId": "cabinda",
    "homeTeam": "São Salvador",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-20T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled"
  },
  {
    "id": "m27-5-3",
    "round": 5,
    "homeTeamId": "sagrada",
    "awayTeamId": "petro",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-20T15:30:00+01:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled",
    "broadcaster": "Zsports"
  },
  {
    "id": "m27-6-1",
    "round": 6,
    "homeTeamId": "petro",
    "awayTeamId": "caala",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T14:00:00+00:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled"
  },
  {
    "id": "m27-6-2",
    "round": 6,
    "homeTeamId": "lobito",
    "awayTeamId": "dago",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T14:00:00+00:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled"
  },
  {
    "id": "m27-6-3",
    "round": 6,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "bravos",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T14:00:00+00:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled"
  },
  {
    "id": "m27-6-4",
    "round": 6,
    "homeTeamId": "fcluanda",
    "awayTeamId": "libolo",
    "homeTeam": "FC Luanda",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-6-5",
    "round": 6,
    "homeTeamId": "interclube",
    "awayTeamId": "sagrada",
    "homeTeam": "GD Interclube",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T14:00:00+00:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled"
  },
  {
    "id": "m27-6-6",
    "round": 6,
    "homeTeamId": "desphuila",
    "awayTeamId": "saosalvador",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "São Salvador",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T14:00:00+00:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled"
  },
  {
    "id": "m27-6-7",
    "round": 6,
    "homeTeamId": "lundasul",
    "awayTeamId": "cabinda",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-6-8",
    "round": 6,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "wiliete",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-11T14:00:00+00:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled"
  },
  {
    "id": "m27-7-1",
    "round": 7,
    "homeTeamId": "sagrada",
    "awayTeamId": "caala",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-7-2",
    "round": 7,
    "homeTeamId": "fcluanda",
    "awayTeamId": "desphuila",
    "homeTeam": "FC Luanda",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-7-3",
    "round": 7,
    "homeTeamId": "bravos",
    "awayTeamId": "lundasul",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T14:00:00+00:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-7-4",
    "round": 7,
    "homeTeamId": "dago",
    "awayTeamId": "wiliete",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-7-5",
    "round": 7,
    "homeTeamId": "petro",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T14:00:00+00:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled"
  },
  {
    "id": "m27-7-6",
    "round": 7,
    "homeTeamId": "cabinda",
    "awayTeamId": "lobito",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T14:00:00+00:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled"
  },
  {
    "id": "m27-7-7",
    "round": 7,
    "homeTeamId": "saosalvador",
    "awayTeamId": "primeiromaio",
    "homeTeam": "São Salvador",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T14:00:00+00:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled"
  },
  {
    "id": "m27-7-8",
    "round": 7,
    "homeTeamId": "libolo",
    "awayTeamId": "interclube",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T14:00:00+00:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-8-1",
    "round": 8,
    "homeTeamId": "caala",
    "awayTeamId": "dago",
    "homeTeam": "CR Caála",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T14:00:00+00:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled"
  },
  {
    "id": "m27-8-2",
    "round": 8,
    "homeTeamId": "bravos",
    "awayTeamId": "petro",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T14:00:00+00:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-8-3",
    "round": 8,
    "homeTeamId": "lobito",
    "awayTeamId": "fcluanda",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T14:00:00+00:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled"
  },
  {
    "id": "m27-8-4",
    "round": 8,
    "homeTeamId": "sagrada",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-8-5",
    "round": 8,
    "homeTeamId": "desphuila",
    "awayTeamId": "libolo",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T14:00:00+00:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled"
  },
  {
    "id": "m27-8-6",
    "round": 8,
    "homeTeamId": "lundasul",
    "awayTeamId": "interclube",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-8-7",
    "round": 8,
    "homeTeamId": "wiliete",
    "awayTeamId": "saosalvador",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "São Salvador",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T14:00:00+00:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled"
  },
  {
    "id": "m27-8-8",
    "round": 8,
    "homeTeamId": "cabinda",
    "awayTeamId": "kabuscorp",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T14:00:00+00:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled"
  },
  {
    "id": "m27-9-1",
    "round": 9,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "caala",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T14:00:00+00:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled"
  },
  {
    "id": "m27-9-2",
    "round": 9,
    "homeTeamId": "wiliete",
    "awayTeamId": "cabinda",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T14:00:00+00:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled"
  },
  {
    "id": "m27-9-3",
    "round": 9,
    "homeTeamId": "saosalvador",
    "awayTeamId": "lundasul",
    "homeTeam": "São Salvador",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T14:00:00+00:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled"
  },
  {
    "id": "m27-9-4",
    "round": 9,
    "homeTeamId": "interclube",
    "awayTeamId": "desphuila",
    "homeTeam": "GD Interclube",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T14:00:00+00:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled"
  },
  {
    "id": "m27-9-5",
    "round": 9,
    "homeTeamId": "libolo",
    "awayTeamId": "sagrada",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T14:00:00+00:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-9-6",
    "round": 9,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "fcluanda",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T14:00:00+00:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled"
  },
  {
    "id": "m27-9-7",
    "round": 9,
    "homeTeamId": "lobito",
    "awayTeamId": "bravos",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T14:00:00+00:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled"
  },
  {
    "id": "m27-9-8",
    "round": 9,
    "homeTeamId": "dago",
    "awayTeamId": "petro",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-10-1",
    "round": 10,
    "homeTeamId": "caala",
    "awayTeamId": "lobito",
    "homeTeam": "CR Caála",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T14:00:00+00:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled"
  },
  {
    "id": "m27-10-2",
    "round": 10,
    "homeTeamId": "petro",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T14:00:00+00:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled"
  },
  {
    "id": "m27-10-3",
    "round": 10,
    "homeTeamId": "libolo",
    "awayTeamId": "dago",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T14:00:00+00:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-10-4",
    "round": 10,
    "homeTeamId": "bravos",
    "awayTeamId": "interclube",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T14:00:00+00:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-10-5",
    "round": 10,
    "homeTeamId": "fcluanda",
    "awayTeamId": "saosalvador",
    "homeTeam": "FC Luanda",
    "awayTeam": "São Salvador",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-10-6",
    "round": 10,
    "homeTeamId": "sagrada",
    "awayTeamId": "cabinda",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-10-7",
    "round": 10,
    "homeTeamId": "desphuila",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T14:00:00+00:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled"
  },
  {
    "id": "m27-10-8",
    "round": 10,
    "homeTeamId": "lundasul",
    "awayTeamId": "wiliete",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-11-1",
    "round": 11,
    "homeTeamId": "caala",
    "awayTeamId": "primeiromaio",
    "homeTeam": "CR Caála",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T14:00:00+00:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled"
  },
  {
    "id": "m27-11-2",
    "round": 11,
    "homeTeamId": "lobito",
    "awayTeamId": "libolo",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T14:00:00+00:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled"
  },
  {
    "id": "m27-11-3",
    "round": 11,
    "homeTeamId": "interclube",
    "awayTeamId": "petro",
    "homeTeam": "GD Interclube",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T14:00:00+00:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled"
  },
  {
    "id": "m27-11-4",
    "round": 11,
    "homeTeamId": "saosalvador",
    "awayTeamId": "dago",
    "homeTeam": "São Salvador",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T14:00:00+00:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled"
  },
  {
    "id": "m27-11-5",
    "round": 11,
    "homeTeamId": "cabinda",
    "awayTeamId": "bravos",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T14:00:00+00:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled"
  },
  {
    "id": "m27-11-6",
    "round": 11,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "fcluanda",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T14:00:00+00:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled"
  },
  {
    "id": "m27-11-7",
    "round": 11,
    "homeTeamId": "wiliete",
    "awayTeamId": "sagrada",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T14:00:00+00:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled"
  },
  {
    "id": "m27-11-8",
    "round": 11,
    "homeTeamId": "lundasul",
    "awayTeamId": "desphuila",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-12-1",
    "round": 12,
    "homeTeamId": "libolo",
    "awayTeamId": "caala",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T14:00:00+00:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-12-2",
    "round": 12,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "interclube",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T14:00:00+00:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled"
  },
  {
    "id": "m27-12-3",
    "round": 12,
    "homeTeamId": "lobito",
    "awayTeamId": "saosalvador",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "São Salvador",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T14:00:00+00:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled"
  },
  {
    "id": "m27-12-4",
    "round": 12,
    "homeTeamId": "petro",
    "awayTeamId": "cabinda",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T14:00:00+00:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled"
  },
  {
    "id": "m27-12-5",
    "round": 12,
    "homeTeamId": "dago",
    "awayTeamId": "kabuscorp",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-12-6",
    "round": 12,
    "homeTeamId": "bravos",
    "awayTeamId": "wiliete",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T14:00:00+00:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-12-7",
    "round": 12,
    "homeTeamId": "fcluanda",
    "awayTeamId": "lundasul",
    "homeTeam": "FC Luanda",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-12-8",
    "round": 12,
    "homeTeamId": "sagrada",
    "awayTeamId": "desphuila",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-13-1",
    "round": 13,
    "homeTeamId": "interclube",
    "awayTeamId": "caala",
    "homeTeam": "GD Interclube",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T14:00:00+00:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled"
  },
  {
    "id": "m27-13-2",
    "round": 13,
    "homeTeamId": "saosalvador",
    "awayTeamId": "libolo",
    "homeTeam": "São Salvador",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T14:00:00+00:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled"
  },
  {
    "id": "m27-13-3",
    "round": 13,
    "homeTeamId": "cabinda",
    "awayTeamId": "primeiromaio",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T14:00:00+00:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled"
  },
  {
    "id": "m27-13-4",
    "round": 13,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "lobito",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T14:00:00+00:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled"
  },
  {
    "id": "m27-13-5",
    "round": 13,
    "homeTeamId": "wiliete",
    "awayTeamId": "petro",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T14:00:00+00:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled"
  },
  {
    "id": "m27-13-6",
    "round": 13,
    "homeTeamId": "lundasul",
    "awayTeamId": "dago",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-13-7",
    "round": 13,
    "homeTeamId": "desphuila",
    "awayTeamId": "bravos",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T14:00:00+00:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled"
  },
  {
    "id": "m27-13-8",
    "round": 13,
    "homeTeamId": "sagrada",
    "awayTeamId": "fcluanda",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-14-1",
    "round": 14,
    "homeTeamId": "caala",
    "awayTeamId": "saosalvador",
    "homeTeam": "CR Caála",
    "awayTeam": "São Salvador",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T14:00:00+00:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled"
  },
  {
    "id": "m27-14-2",
    "round": 14,
    "homeTeamId": "interclube",
    "awayTeamId": "cabinda",
    "homeTeam": "GD Interclube",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T14:00:00+00:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled"
  },
  {
    "id": "m27-14-3",
    "round": 14,
    "homeTeamId": "libolo",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T14:00:00+00:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-14-4",
    "round": 14,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "wiliete",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T14:00:00+00:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled"
  },
  {
    "id": "m27-14-5",
    "round": 14,
    "homeTeamId": "lobito",
    "awayTeamId": "lundasul",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T14:00:00+00:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled"
  },
  {
    "id": "m27-14-6",
    "round": 14,
    "homeTeamId": "petro",
    "awayTeamId": "desphuila",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T14:00:00+00:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled"
  },
  {
    "id": "m27-14-7",
    "round": 14,
    "homeTeamId": "dago",
    "awayTeamId": "sagrada",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-14-8",
    "round": 14,
    "homeTeamId": "fcluanda",
    "awayTeamId": "bravos",
    "homeTeam": "FC Luanda",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-15-1",
    "round": 15,
    "homeTeamId": "cabinda",
    "awayTeamId": "caala",
    "homeTeam": "FC Cabinda",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T14:00:00+00:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled"
  },
  {
    "id": "m27-15-2",
    "round": 15,
    "homeTeamId": "saosalvador",
    "awayTeamId": "kabuscorp",
    "homeTeam": "São Salvador",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T14:00:00+00:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled"
  },
  {
    "id": "m27-15-3",
    "round": 15,
    "homeTeamId": "wiliete",
    "awayTeamId": "interclube",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T14:00:00+00:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled"
  },
  {
    "id": "m27-15-4",
    "round": 15,
    "homeTeamId": "lundasul",
    "awayTeamId": "libolo",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-15-5",
    "round": 15,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "desphuila",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T14:00:00+00:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled"
  },
  {
    "id": "m27-15-6",
    "round": 15,
    "homeTeamId": "sagrada",
    "awayTeamId": "lobito",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-15-7",
    "round": 15,
    "homeTeamId": "fcluanda",
    "awayTeamId": "petro",
    "homeTeam": "FC Luanda",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-15-8",
    "round": 15,
    "homeTeamId": "bravos",
    "awayTeamId": "dago",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T14:00:00+00:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-16-1",
    "round": 16,
    "homeTeamId": "caala",
    "awayTeamId": "fcluanda",
    "homeTeam": "CR Caála",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T14:00:00+00:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled"
  },
  {
    "id": "m27-16-2",
    "round": 16,
    "homeTeamId": "sagrada",
    "awayTeamId": "bravos",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-16-3",
    "round": 16,
    "homeTeamId": "desphuila",
    "awayTeamId": "dago",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T14:00:00+00:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled"
  },
  {
    "id": "m27-16-4",
    "round": 16,
    "homeTeamId": "petro",
    "awayTeamId": "lundasul",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T14:00:00+00:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled"
  },
  {
    "id": "m27-16-5",
    "round": 16,
    "homeTeamId": "lobito",
    "awayTeamId": "wiliete",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T14:00:00+00:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled"
  },
  {
    "id": "m27-16-6",
    "round": 16,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T14:00:00+00:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled"
  },
  {
    "id": "m27-16-7",
    "round": 16,
    "homeTeamId": "libolo",
    "awayTeamId": "cabinda",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T14:00:00+00:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-16-8",
    "round": 16,
    "homeTeamId": "interclube",
    "awayTeamId": "saosalvador",
    "homeTeam": "GD Interclube",
    "awayTeam": "São Salvador",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T14:00:00+00:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled"
  },
  {
    "id": "m27-17-1",
    "round": 17,
    "homeTeamId": "wiliete",
    "awayTeamId": "caala",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T14:00:00+00:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled"
  },
  {
    "id": "m27-17-2",
    "round": 17,
    "homeTeamId": "lundasul",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-17-3",
    "round": 17,
    "homeTeamId": "desphuila",
    "awayTeamId": "cabinda",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T14:00:00+00:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled"
  },
  {
    "id": "m27-17-4",
    "round": 17,
    "homeTeamId": "saosalvador",
    "awayTeamId": "sagrada",
    "homeTeam": "São Salvador",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T14:00:00+00:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled"
  },
  {
    "id": "m27-17-5",
    "round": 17,
    "homeTeamId": "fcluanda",
    "awayTeamId": "interclube",
    "homeTeam": "FC Luanda",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-17-6",
    "round": 17,
    "homeTeamId": "bravos",
    "awayTeamId": "libolo",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T14:00:00+00:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-17-7",
    "round": 17,
    "homeTeamId": "dago",
    "awayTeamId": "primeiromaio",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-17-8",
    "round": 17,
    "homeTeamId": "petro",
    "awayTeamId": "lobito",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T14:00:00+00:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled"
  },
  {
    "id": "m27-18-1",
    "round": 18,
    "homeTeamId": "caala",
    "awayTeamId": "lundasul",
    "homeTeam": "CR Caála",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T14:00:00+00:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled"
  },
  {
    "id": "m27-18-2",
    "round": 18,
    "homeTeamId": "wiliete",
    "awayTeamId": "desphuila",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T14:00:00+00:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled"
  },
  {
    "id": "m27-18-3",
    "round": 18,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "sagrada",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T14:00:00+00:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled"
  },
  {
    "id": "m27-18-4",
    "round": 18,
    "homeTeamId": "cabinda",
    "awayTeamId": "fcluanda",
    "homeTeam": "FC Cabinda",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T14:00:00+00:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled"
  },
  {
    "id": "m27-18-5",
    "round": 18,
    "homeTeamId": "saosalvador",
    "awayTeamId": "bravos",
    "homeTeam": "São Salvador",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T14:00:00+00:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled"
  },
  {
    "id": "m27-18-6",
    "round": 18,
    "homeTeamId": "interclube",
    "awayTeamId": "dago",
    "homeTeam": "GD Interclube",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T14:00:00+00:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled"
  },
  {
    "id": "m27-18-7",
    "round": 18,
    "homeTeamId": "libolo",
    "awayTeamId": "petro",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T14:00:00+00:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-18-8",
    "round": 18,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "lobito",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T14:00:00+00:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled"
  },
  {
    "id": "m27-19-1",
    "round": 19,
    "homeTeamId": "desphuila",
    "awayTeamId": "caala",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T14:00:00+00:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled"
  },
  {
    "id": "m27-19-2",
    "round": 19,
    "homeTeamId": "sagrada",
    "awayTeamId": "lundasul",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-19-3",
    "round": 19,
    "homeTeamId": "fcluanda",
    "awayTeamId": "wiliete",
    "homeTeam": "FC Luanda",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-19-5",
    "round": 19,
    "homeTeamId": "dago",
    "awayTeamId": "cabinda",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-19-6",
    "round": 19,
    "homeTeamId": "petro",
    "awayTeamId": "saosalvador",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "São Salvador",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T14:00:00+00:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled"
  },
  {
    "id": "m27-19-7",
    "round": 19,
    "homeTeamId": "lobito",
    "awayTeamId": "interclube",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T14:00:00+00:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled"
  },
  {
    "id": "m27-19-8",
    "round": 19,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "libolo",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T14:00:00+00:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled"
  },
  {
    "id": "m27-19-4",
    "round": 19,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "bravos",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-21T14:00:00+00:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled"
  },
  {
    "id": "m27-20-1",
    "round": 20,
    "homeTeamId": "bravos",
    "awayTeamId": "caala",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T14:00:00+00:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-20-2",
    "round": 20,
    "homeTeamId": "fcluanda",
    "awayTeamId": "dago",
    "homeTeam": "FC Luanda",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-20-3",
    "round": 20,
    "homeTeamId": "petro",
    "awayTeamId": "sagrada",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T14:00:00+00:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled"
  },
  {
    "id": "m27-20-4",
    "round": 20,
    "homeTeamId": "lobito",
    "awayTeamId": "desphuila",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T14:00:00+00:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled"
  },
  {
    "id": "m27-20-5",
    "round": 20,
    "homeTeamId": "lundasul",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-20-6",
    "round": 20,
    "homeTeamId": "libolo",
    "awayTeamId": "wiliete",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T14:00:00+00:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-20-7",
    "round": 20,
    "homeTeamId": "interclube",
    "awayTeamId": "kabuscorp",
    "homeTeam": "GD Interclube",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T14:00:00+00:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled"
  },
  {
    "id": "m27-20-8",
    "round": 20,
    "homeTeamId": "cabinda",
    "awayTeamId": "saosalvador",
    "homeTeam": "FC Cabinda",
    "awayTeam": "São Salvador",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T14:00:00+00:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled"
  },
  {
    "id": "m27-21-1",
    "round": 21,
    "homeTeamId": "caala",
    "awayTeamId": "petro",
    "homeTeam": "CR Caála",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T14:00:00+00:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled"
  },
  {
    "id": "m27-21-2",
    "round": 21,
    "homeTeamId": "dago",
    "awayTeamId": "lobito",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-21-3",
    "round": 21,
    "homeTeamId": "bravos",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T14:00:00+00:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-21-4",
    "round": 21,
    "homeTeamId": "libolo",
    "awayTeamId": "fcluanda",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T14:00:00+00:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-21-5",
    "round": 21,
    "homeTeamId": "sagrada",
    "awayTeamId": "interclube",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-21-6",
    "round": 21,
    "homeTeamId": "saosalvador",
    "awayTeamId": "desphuila",
    "homeTeam": "São Salvador",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T14:00:00+00:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled"
  },
  {
    "id": "m27-21-7",
    "round": 21,
    "homeTeamId": "cabinda",
    "awayTeamId": "lundasul",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T14:00:00+00:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled"
  },
  {
    "id": "m27-21-8",
    "round": 21,
    "homeTeamId": "wiliete",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T14:00:00+00:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled"
  },
  {
    "id": "m27-22-1",
    "round": 22,
    "homeTeamId": "caala",
    "awayTeamId": "sagrada",
    "homeTeam": "CR Caála",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T14:00:00+00:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled"
  },
  {
    "id": "m27-22-2",
    "round": 22,
    "homeTeamId": "desphuila",
    "awayTeamId": "fcluanda",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T14:00:00+00:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled"
  },
  {
    "id": "m27-22-3",
    "round": 22,
    "homeTeamId": "lundasul",
    "awayTeamId": "bravos",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-22-4",
    "round": 22,
    "homeTeamId": "wiliete",
    "awayTeamId": "dago",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T14:00:00+00:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled"
  },
  {
    "id": "m27-22-5",
    "round": 22,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "petro",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T14:00:00+00:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled"
  },
  {
    "id": "m27-22-6",
    "round": 22,
    "homeTeamId": "lobito",
    "awayTeamId": "cabinda",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T14:00:00+00:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled"
  },
  {
    "id": "m27-22-7",
    "round": 22,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "saosalvador",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "São Salvador",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T14:00:00+00:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled"
  },
  {
    "id": "m27-22-8",
    "round": 22,
    "homeTeamId": "interclube",
    "awayTeamId": "libolo",
    "homeTeam": "GD Interclube",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T14:00:00+00:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled"
  },
  {
    "id": "m27-23-1",
    "round": 23,
    "homeTeamId": "dago",
    "awayTeamId": "caala",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-23-2",
    "round": 23,
    "homeTeamId": "petro",
    "awayTeamId": "bravos",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T14:00:00+00:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled"
  },
  {
    "id": "m27-23-3",
    "round": 23,
    "homeTeamId": "fcluanda",
    "awayTeamId": "lobito",
    "homeTeam": "FC Luanda",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-23-4",
    "round": 23,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "sagrada",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T14:00:00+00:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled"
  },
  {
    "id": "m27-23-5",
    "round": 23,
    "homeTeamId": "libolo",
    "awayTeamId": "desphuila",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T14:00:00+00:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-23-6",
    "round": 23,
    "homeTeamId": "interclube",
    "awayTeamId": "lundasul",
    "homeTeam": "GD Interclube",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T14:00:00+00:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled"
  },
  {
    "id": "m27-23-7",
    "round": 23,
    "homeTeamId": "saosalvador",
    "awayTeamId": "wiliete",
    "homeTeam": "São Salvador",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T14:00:00+00:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled"
  },
  {
    "id": "m27-23-8",
    "round": 23,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "cabinda",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-21T14:00:00+00:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled"
  },
  {
    "id": "m27-24-1",
    "round": 24,
    "homeTeamId": "caala",
    "awayTeamId": "kabuscorp",
    "homeTeam": "CR Caála",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T14:00:00+00:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled"
  },
  {
    "id": "m27-24-2",
    "round": 24,
    "homeTeamId": "cabinda",
    "awayTeamId": "wiliete",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T14:00:00+00:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled"
  },
  {
    "id": "m27-24-3",
    "round": 24,
    "homeTeamId": "lundasul",
    "awayTeamId": "saosalvador",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "São Salvador",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-24-4",
    "round": 24,
    "homeTeamId": "desphuila",
    "awayTeamId": "interclube",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T14:00:00+00:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled"
  },
  {
    "id": "m27-24-5",
    "round": 24,
    "homeTeamId": "sagrada",
    "awayTeamId": "libolo",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-24-6",
    "round": 24,
    "homeTeamId": "fcluanda",
    "awayTeamId": "primeiromaio",
    "homeTeam": "FC Luanda",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-24-7",
    "round": 24,
    "homeTeamId": "bravos",
    "awayTeamId": "lobito",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T14:00:00+00:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-24-8",
    "round": 24,
    "homeTeamId": "petro",
    "awayTeamId": "dago",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T14:00:00+00:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled"
  },
  {
    "id": "m27-25-1",
    "round": 25,
    "homeTeamId": "lobito",
    "awayTeamId": "caala",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T14:00:00+00:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled"
  },
  {
    "id": "m27-25-2",
    "round": 25,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "petro",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T14:00:00+00:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled"
  },
  {
    "id": "m27-25-3",
    "round": 25,
    "homeTeamId": "dago",
    "awayTeamId": "libolo",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-25-4",
    "round": 25,
    "homeTeamId": "interclube",
    "awayTeamId": "bravos",
    "homeTeam": "GD Interclube",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T14:00:00+00:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled"
  },
  {
    "id": "m27-25-5",
    "round": 25,
    "homeTeamId": "saosalvador",
    "awayTeamId": "fcluanda",
    "homeTeam": "São Salvador",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T14:00:00+00:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled"
  },
  {
    "id": "m27-25-6",
    "round": 25,
    "homeTeamId": "cabinda",
    "awayTeamId": "sagrada",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T14:00:00+00:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled"
  },
  {
    "id": "m27-25-7",
    "round": 25,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "desphuila",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T14:00:00+00:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled"
  },
  {
    "id": "m27-25-8",
    "round": 25,
    "homeTeamId": "wiliete",
    "awayTeamId": "lundasul",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T14:00:00+00:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled"
  },
  {
    "id": "m27-26-1",
    "round": 26,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "caala",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T14:00:00+00:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled"
  },
  {
    "id": "m27-26-2",
    "round": 26,
    "homeTeamId": "libolo",
    "awayTeamId": "lobito",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T14:00:00+00:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-26-3",
    "round": 26,
    "homeTeamId": "petro",
    "awayTeamId": "interclube",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T14:00:00+00:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled"
  },
  {
    "id": "m27-26-4",
    "round": 26,
    "homeTeamId": "dago",
    "awayTeamId": "saosalvador",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "São Salvador",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-26-5",
    "round": 26,
    "homeTeamId": "bravos",
    "awayTeamId": "cabinda",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T14:00:00+00:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-26-6",
    "round": 26,
    "homeTeamId": "fcluanda",
    "awayTeamId": "kabuscorp",
    "homeTeam": "FC Luanda",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-26-7",
    "round": 26,
    "homeTeamId": "sagrada",
    "awayTeamId": "wiliete",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-26-8",
    "round": 26,
    "homeTeamId": "desphuila",
    "awayTeamId": "lundasul",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T14:00:00+00:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled"
  },
  {
    "id": "m27-27-1",
    "round": 27,
    "homeTeamId": "caala",
    "awayTeamId": "libolo",
    "homeTeam": "CR Caála",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T14:00:00+00:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled"
  },
  {
    "id": "m27-27-2",
    "round": 27,
    "homeTeamId": "interclube",
    "awayTeamId": "primeiromaio",
    "homeTeam": "GD Interclube",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T14:00:00+00:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled"
  },
  {
    "id": "m27-27-3",
    "round": 27,
    "homeTeamId": "saosalvador",
    "awayTeamId": "lobito",
    "homeTeam": "São Salvador",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T14:00:00+00:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled"
  },
  {
    "id": "m27-27-4",
    "round": 27,
    "homeTeamId": "cabinda",
    "awayTeamId": "petro",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T14:00:00+00:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled"
  },
  {
    "id": "m27-27-5",
    "round": 27,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "dago",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T14:00:00+00:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled"
  },
  {
    "id": "m27-27-6",
    "round": 27,
    "homeTeamId": "wiliete",
    "awayTeamId": "bravos",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T14:00:00+00:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled"
  },
  {
    "id": "m27-27-7",
    "round": 27,
    "homeTeamId": "lundasul",
    "awayTeamId": "fcluanda",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-27-8",
    "round": 27,
    "homeTeamId": "desphuila",
    "awayTeamId": "sagrada",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T14:00:00+00:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled"
  },
  {
    "id": "m27-28-1",
    "round": 28,
    "homeTeamId": "caala",
    "awayTeamId": "interclube",
    "homeTeam": "CR Caála",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T14:00:00+00:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled"
  },
  {
    "id": "m27-28-2",
    "round": 28,
    "homeTeamId": "libolo",
    "awayTeamId": "saosalvador",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "São Salvador",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T14:00:00+00:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-28-3",
    "round": 28,
    "homeTeamId": "primeiromaio",
    "awayTeamId": "cabinda",
    "homeTeam": "Estrela 1.º de Maio",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T14:00:00+00:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled"
  },
  {
    "id": "m27-28-4",
    "round": 28,
    "homeTeamId": "lobito",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Kabuscorp SC",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T14:00:00+00:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled"
  },
  {
    "id": "m27-28-5",
    "round": 28,
    "homeTeamId": "petro",
    "awayTeamId": "wiliete",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T14:00:00+00:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled"
  },
  {
    "id": "m27-28-6",
    "round": 28,
    "homeTeamId": "dago",
    "awayTeamId": "lundasul",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-28-7",
    "round": 28,
    "homeTeamId": "bravos",
    "awayTeamId": "desphuila",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T14:00:00+00:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-28-8",
    "round": 28,
    "homeTeamId": "fcluanda",
    "awayTeamId": "sagrada",
    "homeTeam": "FC Luanda",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  },
  {
    "id": "m27-29-1",
    "round": 29,
    "homeTeamId": "saosalvador",
    "awayTeamId": "caala",
    "homeTeam": "São Salvador",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T14:00:00+00:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled"
  },
  {
    "id": "m27-29-2",
    "round": 29,
    "homeTeamId": "cabinda",
    "awayTeamId": "interclube",
    "homeTeam": "FC Cabinda",
    "awayTeam": "GD Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T14:00:00+00:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled"
  },
  {
    "id": "m27-29-3",
    "round": 29,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "libolo",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T14:00:00+00:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled"
  },
  {
    "id": "m27-29-4",
    "round": 29,
    "homeTeamId": "wiliete",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T14:00:00+00:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled"
  },
  {
    "id": "m27-29-5",
    "round": 29,
    "homeTeamId": "lundasul",
    "awayTeamId": "lobito",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-29-6",
    "round": 29,
    "homeTeamId": "desphuila",
    "awayTeamId": "petro",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T14:00:00+00:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled"
  },
  {
    "id": "m27-29-7",
    "round": 29,
    "homeTeamId": "sagrada",
    "awayTeamId": "dago",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "CD 1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T14:00:00+00:00",
    "stadium": "Estádio do Sagrada Esperança",
    "status": "scheduled"
  },
  {
    "id": "m27-29-8",
    "round": 29,
    "homeTeamId": "bravos",
    "awayTeamId": "fcluanda",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T14:00:00+00:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled"
  },
  {
    "id": "m27-30-1",
    "round": 30,
    "homeTeamId": "caala",
    "awayTeamId": "cabinda",
    "homeTeam": "CR Caála",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T14:00:00+00:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled"
  },
  {
    "id": "m27-30-2",
    "round": 30,
    "homeTeamId": "kabuscorp",
    "awayTeamId": "saosalvador",
    "homeTeam": "Kabuscorp SC",
    "awayTeam": "São Salvador",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T14:00:00+00:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled"
  },
  {
    "id": "m27-30-3",
    "round": 30,
    "homeTeamId": "interclube",
    "awayTeamId": "wiliete",
    "homeTeam": "GD Interclube",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T14:00:00+00:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled"
  },
  {
    "id": "m27-30-4",
    "round": 30,
    "homeTeamId": "libolo",
    "awayTeamId": "lundasul",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T14:00:00+00:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled"
  },
  {
    "id": "m27-30-5",
    "round": 30,
    "homeTeamId": "desphuila",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Estrela 1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T14:00:00+00:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled"
  },
  {
    "id": "m27-30-6",
    "round": 30,
    "homeTeamId": "lobito",
    "awayTeamId": "sagrada",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T14:00:00+00:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled"
  },
  {
    "id": "m27-30-7",
    "round": 30,
    "homeTeamId": "petro",
    "awayTeamId": "fcluanda",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T14:00:00+00:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled"
  },
  {
    "id": "m27-30-8",
    "round": 30,
    "homeTeamId": "dago",
    "awayTeamId": "bravos",
    "homeTeam": "CD 1.º de Agosto",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T14:00:00+00:00",
    "stadium": "Estádio França N’dalu",
    "status": "scheduled"
  }
];
