// Calendário oficial publicado pelo gestor ANCAF.
// Fonte: FAF_Calendar/public/possibilidades_calendarios_com_datas.md, calendário nº 1.
// Gerado automaticamente para servir como fallback público quando o Supabase do portal está indisponível.
import type { Match } from './data';

export const PUBLISHED_ANCAF_CALENDAR_SOURCE = {
  system: 'ANCAF_CALENDAR',
  accessCode: '1',
  technicalSeed: '1',
  fingerprint: '7a60f1455f47e31a67bc6949ca705ca9fcd7cf773ae48374eb2e4330a1345830',
  season: '2026/2027',
  generatedAt: '2026-07-14T12:00:00+01:00',
  rounds: 30,
  matches: 240,
} as const;

export const PUBLISHED_MATCHES_2026_27: Match[] = [
  {
    "id": "m27-1-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "libolo",
    "homeTeam": "FC Luanda",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-22T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 1
  },
  {
    "id": "m27-1-2",
    "homeTeamId": "lundasul",
    "awayTeamId": "saosalvador",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-22T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 1
  },
  {
    "id": "m27-1-3",
    "homeTeamId": "petro",
    "awayTeamId": "desphuila",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-22T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 1
  },
  {
    "id": "m27-1-4",
    "homeTeamId": "interclube",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Interclube",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-22T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 1
  },
  {
    "id": "m27-1-5",
    "homeTeamId": "dago",
    "awayTeamId": "kabuscorp",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-22T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 1
  },
  {
    "id": "m27-1-6",
    "homeTeamId": "lobito",
    "awayTeamId": "wiliete",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-22T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 1
  },
  {
    "id": "m27-1-7",
    "homeTeamId": "cabinda",
    "awayTeamId": "caala",
    "homeTeam": "FC Cabinda",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-22T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 1
  },
  {
    "id": "m27-1-8",
    "homeTeamId": "sagrada",
    "awayTeamId": "bravos",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-22T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 1
  },
  {
    "id": "m27-2-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "lundasul",
    "homeTeam": "FC Luanda",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-29T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 2
  },
  {
    "id": "m27-2-2",
    "homeTeamId": "libolo",
    "awayTeamId": "petro",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-29T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 2
  },
  {
    "id": "m27-2-3",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "saosalvador",
    "homeTeam": "1.º de Maio",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-29T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 2
  },
  {
    "id": "m27-2-4",
    "homeTeamId": "desphuila",
    "awayTeamId": "dago",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-29T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 2
  },
  {
    "id": "m27-2-5",
    "homeTeamId": "interclube",
    "awayTeamId": "lobito",
    "homeTeam": "Interclube",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-29T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 2
  },
  {
    "id": "m27-2-6",
    "homeTeamId": "caala",
    "awayTeamId": "kabuscorp",
    "homeTeam": "CR Caála",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-29T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 2
  },
  {
    "id": "m27-2-7",
    "homeTeamId": "wiliete",
    "awayTeamId": "sagrada",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-29T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 2
  },
  {
    "id": "m27-2-8",
    "homeTeamId": "bravos",
    "awayTeamId": "cabinda",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-08-29T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 2
  },
  {
    "id": "m27-3-1",
    "homeTeamId": "petro",
    "awayTeamId": "fcluanda",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-05T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 3
  },
  {
    "id": "m27-3-2",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "lundasul",
    "homeTeam": "1.º de Maio",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-05T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 3
  },
  {
    "id": "m27-3-3",
    "homeTeamId": "libolo",
    "awayTeamId": "dago",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-05T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 3
  },
  {
    "id": "m27-3-4",
    "homeTeamId": "saosalvador",
    "awayTeamId": "lobito",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-05T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 3
  },
  {
    "id": "m27-3-5",
    "homeTeamId": "caala",
    "awayTeamId": "desphuila",
    "homeTeam": "CR Caála",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-05T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 3
  },
  {
    "id": "m27-3-6",
    "homeTeamId": "sagrada",
    "awayTeamId": "interclube",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-05T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 3
  },
  {
    "id": "m27-3-7",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "bravos",
    "homeTeam": "Kabuscorp",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-05T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 3
  },
  {
    "id": "m27-3-8",
    "homeTeamId": "cabinda",
    "awayTeamId": "wiliete",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-05T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 3
  },
  {
    "id": "m27-4-1",
    "homeTeamId": "dago",
    "awayTeamId": "fcluanda",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-12T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 4
  },
  {
    "id": "m27-4-2",
    "homeTeamId": "lobito",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-12T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 4
  },
  {
    "id": "m27-4-3",
    "homeTeamId": "petro",
    "awayTeamId": "caala",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-12T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 4
  },
  {
    "id": "m27-4-4",
    "homeTeamId": "lundasul",
    "awayTeamId": "sagrada",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-12T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 4
  },
  {
    "id": "m27-4-5",
    "homeTeamId": "bravos",
    "awayTeamId": "libolo",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-12T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 4
  },
  {
    "id": "m27-4-6",
    "homeTeamId": "saosalvador",
    "awayTeamId": "cabinda",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-12T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 4
  },
  {
    "id": "m27-4-7",
    "homeTeamId": "desphuila",
    "awayTeamId": "wiliete",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-12T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 4
  },
  {
    "id": "m27-4-8",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "interclube",
    "homeTeam": "Kabuscorp",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-12T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 4
  },
  {
    "id": "m27-5-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "primeiromaio",
    "homeTeam": "FC Luanda",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-19T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 5
  },
  {
    "id": "m27-5-2",
    "homeTeamId": "dago",
    "awayTeamId": "petro",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-19T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 5
  },
  {
    "id": "m27-5-3",
    "homeTeamId": "lundasul",
    "awayTeamId": "lobito",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-19T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 5
  },
  {
    "id": "m27-5-4",
    "homeTeamId": "caala",
    "awayTeamId": "libolo",
    "homeTeam": "CR Caála",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-19T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 5
  },
  {
    "id": "m27-5-5",
    "homeTeamId": "sagrada",
    "awayTeamId": "saosalvador",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-19T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 5
  },
  {
    "id": "m27-5-6",
    "homeTeamId": "desphuila",
    "awayTeamId": "bravos",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-19T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 5
  },
  {
    "id": "m27-5-7",
    "homeTeamId": "interclube",
    "awayTeamId": "cabinda",
    "homeTeam": "Interclube",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-19T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 5
  },
  {
    "id": "m27-5-8",
    "homeTeamId": "wiliete",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-09-19T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 5
  },
  {
    "id": "m27-6-1",
    "homeTeamId": "lobito",
    "awayTeamId": "fcluanda",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 6
  },
  {
    "id": "m27-6-2",
    "homeTeamId": "caala",
    "awayTeamId": "dago",
    "homeTeam": "CR Caála",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 6
  },
  {
    "id": "m27-6-3",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "sagrada",
    "homeTeam": "1.º de Maio",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 6
  },
  {
    "id": "m27-6-4",
    "homeTeamId": "petro",
    "awayTeamId": "bravos",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 6
  },
  {
    "id": "m27-6-5",
    "homeTeamId": "cabinda",
    "awayTeamId": "lundasul",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 6
  },
  {
    "id": "m27-6-6",
    "homeTeamId": "libolo",
    "awayTeamId": "wiliete",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 6
  },
  {
    "id": "m27-6-7",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "saosalvador",
    "homeTeam": "Kabuscorp",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 6
  },
  {
    "id": "m27-6-8",
    "homeTeamId": "interclube",
    "awayTeamId": "desphuila",
    "homeTeam": "Interclube",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-10T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 6
  },
  {
    "id": "m27-7-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "caala",
    "homeTeam": "FC Luanda",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 7
  },
  {
    "id": "m27-7-2",
    "homeTeamId": "sagrada",
    "awayTeamId": "lobito",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 7
  },
  {
    "id": "m27-7-3",
    "homeTeamId": "bravos",
    "awayTeamId": "dago",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 7
  },
  {
    "id": "m27-7-4",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "cabinda",
    "homeTeam": "1.º de Maio",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 7
  },
  {
    "id": "m27-7-5",
    "homeTeamId": "wiliete",
    "awayTeamId": "petro",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 7
  },
  {
    "id": "m27-7-6",
    "homeTeamId": "lundasul",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 7
  },
  {
    "id": "m27-7-7",
    "homeTeamId": "libolo",
    "awayTeamId": "interclube",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 7
  },
  {
    "id": "m27-7-8",
    "homeTeamId": "saosalvador",
    "awayTeamId": "desphuila",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-17T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 7
  },
  {
    "id": "m27-8-1",
    "homeTeamId": "sagrada",
    "awayTeamId": "fcluanda",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 8
  },
  {
    "id": "m27-8-2",
    "homeTeamId": "bravos",
    "awayTeamId": "caala",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 8
  },
  {
    "id": "m27-8-3",
    "homeTeamId": "cabinda",
    "awayTeamId": "lobito",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 8
  },
  {
    "id": "m27-8-4",
    "homeTeamId": "dago",
    "awayTeamId": "wiliete",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 8
  },
  {
    "id": "m27-8-5",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Kabuscorp",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 8
  },
  {
    "id": "m27-8-6",
    "homeTeamId": "petro",
    "awayTeamId": "interclube",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 8
  },
  {
    "id": "m27-8-7",
    "homeTeamId": "desphuila",
    "awayTeamId": "lundasul",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 8
  },
  {
    "id": "m27-8-8",
    "homeTeamId": "saosalvador",
    "awayTeamId": "libolo",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-24T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 8
  },
  {
    "id": "m27-9-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "bravos",
    "homeTeam": "FC Luanda",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 9
  },
  {
    "id": "m27-9-2",
    "homeTeamId": "cabinda",
    "awayTeamId": "sagrada",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 9
  },
  {
    "id": "m27-9-3",
    "homeTeamId": "caala",
    "awayTeamId": "wiliete",
    "homeTeam": "CR Caála",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 9
  },
  {
    "id": "m27-9-4",
    "homeTeamId": "lobito",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 9
  },
  {
    "id": "m27-9-5",
    "homeTeamId": "interclube",
    "awayTeamId": "dago",
    "homeTeam": "Interclube",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 9
  },
  {
    "id": "m27-9-6",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "desphuila",
    "homeTeam": "1.º de Maio",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 9
  },
  {
    "id": "m27-9-7",
    "homeTeamId": "petro",
    "awayTeamId": "saosalvador",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 9
  },
  {
    "id": "m27-9-8",
    "homeTeamId": "libolo",
    "awayTeamId": "lundasul",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-10-31T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 9
  },
  {
    "id": "m27-10-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "cabinda",
    "homeTeam": "FC Luanda",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 10
  },
  {
    "id": "m27-10-2",
    "homeTeamId": "wiliete",
    "awayTeamId": "bravos",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 10
  },
  {
    "id": "m27-10-3",
    "homeTeamId": "sagrada",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 10
  },
  {
    "id": "m27-10-4",
    "homeTeamId": "caala",
    "awayTeamId": "interclube",
    "homeTeam": "CR Caála",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 10
  },
  {
    "id": "m27-10-5",
    "homeTeamId": "desphuila",
    "awayTeamId": "lobito",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 10
  },
  {
    "id": "m27-10-6",
    "homeTeamId": "saosalvador",
    "awayTeamId": "dago",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 10
  },
  {
    "id": "m27-10-7",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "libolo",
    "homeTeam": "1.º de Maio",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 10
  },
  {
    "id": "m27-10-8",
    "homeTeamId": "lundasul",
    "awayTeamId": "petro",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-07T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 10
  },
  {
    "id": "m27-11-1",
    "homeTeamId": "wiliete",
    "awayTeamId": "fcluanda",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 11
  },
  {
    "id": "m27-11-2",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "cabinda",
    "homeTeam": "Kabuscorp",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 11
  },
  {
    "id": "m27-11-3",
    "homeTeamId": "bravos",
    "awayTeamId": "interclube",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 11
  },
  {
    "id": "m27-11-4",
    "homeTeamId": "desphuila",
    "awayTeamId": "sagrada",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 11
  },
  {
    "id": "m27-11-5",
    "homeTeamId": "saosalvador",
    "awayTeamId": "caala",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 11
  },
  {
    "id": "m27-11-6",
    "homeTeamId": "libolo",
    "awayTeamId": "lobito",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 11
  },
  {
    "id": "m27-11-7",
    "homeTeamId": "dago",
    "awayTeamId": "lundasul",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 11
  },
  {
    "id": "m27-11-8",
    "homeTeamId": "petro",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-21T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 11
  },
  {
    "id": "m27-12-1",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "fcluanda",
    "homeTeam": "Kabuscorp",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 12
  },
  {
    "id": "m27-12-2",
    "homeTeamId": "interclube",
    "awayTeamId": "wiliete",
    "homeTeam": "Interclube",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 12
  },
  {
    "id": "m27-12-3",
    "homeTeamId": "cabinda",
    "awayTeamId": "desphuila",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 12
  },
  {
    "id": "m27-12-4",
    "homeTeamId": "bravos",
    "awayTeamId": "saosalvador",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 12
  },
  {
    "id": "m27-12-5",
    "homeTeamId": "sagrada",
    "awayTeamId": "libolo",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 12
  },
  {
    "id": "m27-12-6",
    "homeTeamId": "caala",
    "awayTeamId": "lundasul",
    "homeTeam": "CR Caála",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 12
  },
  {
    "id": "m27-12-7",
    "homeTeamId": "lobito",
    "awayTeamId": "petro",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 12
  },
  {
    "id": "m27-12-8",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "dago",
    "homeTeam": "1.º de Maio",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-11-28T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 12
  },
  {
    "id": "m27-13-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "interclube",
    "homeTeam": "FC Luanda",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 13
  },
  {
    "id": "m27-13-2",
    "homeTeamId": "desphuila",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 13
  },
  {
    "id": "m27-13-3",
    "homeTeamId": "saosalvador",
    "awayTeamId": "wiliete",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 13
  },
  {
    "id": "m27-13-4",
    "homeTeamId": "libolo",
    "awayTeamId": "cabinda",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 13
  },
  {
    "id": "m27-13-5",
    "homeTeamId": "lundasul",
    "awayTeamId": "bravos",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 13
  },
  {
    "id": "m27-13-6",
    "homeTeamId": "petro",
    "awayTeamId": "sagrada",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 13
  },
  {
    "id": "m27-13-7",
    "homeTeamId": "caala",
    "awayTeamId": "primeiromaio",
    "homeTeam": "CR Caála",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 13
  },
  {
    "id": "m27-13-8",
    "homeTeamId": "dago",
    "awayTeamId": "lobito",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-05T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 13
  },
  {
    "id": "m27-14-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "desphuila",
    "homeTeam": "FC Luanda",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 14
  },
  {
    "id": "m27-14-2",
    "homeTeamId": "interclube",
    "awayTeamId": "saosalvador",
    "homeTeam": "Interclube",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 14
  },
  {
    "id": "m27-14-3",
    "homeTeamId": "libolo",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 14
  },
  {
    "id": "m27-14-4",
    "homeTeamId": "wiliete",
    "awayTeamId": "lundasul",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 14
  },
  {
    "id": "m27-14-5",
    "homeTeamId": "cabinda",
    "awayTeamId": "petro",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 14
  },
  {
    "id": "m27-14-6",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "bravos",
    "homeTeam": "1.º de Maio",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 14
  },
  {
    "id": "m27-14-7",
    "homeTeamId": "sagrada",
    "awayTeamId": "dago",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 14
  },
  {
    "id": "m27-14-8",
    "homeTeamId": "lobito",
    "awayTeamId": "caala",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-12T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 14
  },
  {
    "id": "m27-15-1",
    "homeTeamId": "saosalvador",
    "awayTeamId": "fcluanda",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 15
  },
  {
    "id": "m27-15-2",
    "homeTeamId": "desphuila",
    "awayTeamId": "libolo",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 15
  },
  {
    "id": "m27-15-3",
    "homeTeamId": "lundasul",
    "awayTeamId": "interclube",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 15
  },
  {
    "id": "m27-15-4",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "petro",
    "homeTeam": "Kabuscorp",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 15
  },
  {
    "id": "m27-15-5",
    "homeTeamId": "wiliete",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 15
  },
  {
    "id": "m27-15-6",
    "homeTeamId": "dago",
    "awayTeamId": "cabinda",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 15
  },
  {
    "id": "m27-15-7",
    "homeTeamId": "bravos",
    "awayTeamId": "lobito",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 15
  },
  {
    "id": "m27-15-8",
    "homeTeamId": "caala",
    "awayTeamId": "sagrada",
    "homeTeam": "CR Caála",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2026-12-19T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 15
  },
  {
    "id": "m27-16-1",
    "homeTeamId": "cabinda",
    "awayTeamId": "fcluanda",
    "homeTeam": "FC Cabinda",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 16
  },
  {
    "id": "m27-16-2",
    "homeTeamId": "bravos",
    "awayTeamId": "wiliete",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 16
  },
  {
    "id": "m27-16-3",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "sagrada",
    "homeTeam": "Kabuscorp",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 16
  },
  {
    "id": "m27-16-4",
    "homeTeamId": "interclube",
    "awayTeamId": "caala",
    "homeTeam": "Interclube",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 16
  },
  {
    "id": "m27-16-5",
    "homeTeamId": "lobito",
    "awayTeamId": "desphuila",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 16
  },
  {
    "id": "m27-16-6",
    "homeTeamId": "dago",
    "awayTeamId": "saosalvador",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 16
  },
  {
    "id": "m27-16-7",
    "homeTeamId": "libolo",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 16
  },
  {
    "id": "m27-16-8",
    "homeTeamId": "petro",
    "awayTeamId": "lundasul",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-01-31T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 16
  },
  {
    "id": "m27-17-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "dago",
    "homeTeam": "FC Luanda",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 17
  },
  {
    "id": "m27-17-2",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "lobito",
    "homeTeam": "1.º de Maio",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 17
  },
  {
    "id": "m27-17-3",
    "homeTeamId": "caala",
    "awayTeamId": "petro",
    "homeTeam": "CR Caála",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 17
  },
  {
    "id": "m27-17-4",
    "homeTeamId": "sagrada",
    "awayTeamId": "lundasul",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 17
  },
  {
    "id": "m27-17-5",
    "homeTeamId": "libolo",
    "awayTeamId": "bravos",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 17
  },
  {
    "id": "m27-17-6",
    "homeTeamId": "cabinda",
    "awayTeamId": "saosalvador",
    "homeTeam": "FC Cabinda",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 17
  },
  {
    "id": "m27-17-7",
    "homeTeamId": "wiliete",
    "awayTeamId": "desphuila",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 17
  },
  {
    "id": "m27-17-8",
    "homeTeamId": "interclube",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Interclube",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-06T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 17
  },
  {
    "id": "m27-18-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "lobito",
    "homeTeam": "FC Luanda",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 18
  },
  {
    "id": "m27-18-2",
    "homeTeamId": "dago",
    "awayTeamId": "caala",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 18
  },
  {
    "id": "m27-18-3",
    "homeTeamId": "sagrada",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 18
  },
  {
    "id": "m27-18-4",
    "homeTeamId": "bravos",
    "awayTeamId": "petro",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 18
  },
  {
    "id": "m27-18-5",
    "homeTeamId": "lundasul",
    "awayTeamId": "cabinda",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 18
  },
  {
    "id": "m27-18-6",
    "homeTeamId": "wiliete",
    "awayTeamId": "libolo",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 18
  },
  {
    "id": "m27-18-7",
    "homeTeamId": "saosalvador",
    "awayTeamId": "kabuscorp",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 18
  },
  {
    "id": "m27-18-8",
    "homeTeamId": "desphuila",
    "awayTeamId": "interclube",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-13T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 18
  },
  {
    "id": "m27-19-1",
    "homeTeamId": "caala",
    "awayTeamId": "fcluanda",
    "homeTeam": "CR Caála",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 19
  },
  {
    "id": "m27-19-2",
    "homeTeamId": "lobito",
    "awayTeamId": "sagrada",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 19
  },
  {
    "id": "m27-19-3",
    "homeTeamId": "dago",
    "awayTeamId": "bravos",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 19
  },
  {
    "id": "m27-19-4",
    "homeTeamId": "cabinda",
    "awayTeamId": "primeiromaio",
    "homeTeam": "FC Cabinda",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 19
  },
  {
    "id": "m27-19-5",
    "homeTeamId": "petro",
    "awayTeamId": "wiliete",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 19
  },
  {
    "id": "m27-19-6",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "lundasul",
    "homeTeam": "Kabuscorp",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 19
  },
  {
    "id": "m27-19-7",
    "homeTeamId": "interclube",
    "awayTeamId": "libolo",
    "homeTeam": "Interclube",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 19
  },
  {
    "id": "m27-19-8",
    "homeTeamId": "desphuila",
    "awayTeamId": "saosalvador",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-20T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 19
  },
  {
    "id": "m27-20-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "sagrada",
    "homeTeam": "FC Luanda",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 20
  },
  {
    "id": "m27-20-2",
    "homeTeamId": "caala",
    "awayTeamId": "bravos",
    "homeTeam": "CR Caála",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 20
  },
  {
    "id": "m27-20-3",
    "homeTeamId": "lobito",
    "awayTeamId": "cabinda",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 20
  },
  {
    "id": "m27-20-4",
    "homeTeamId": "wiliete",
    "awayTeamId": "dago",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 20
  },
  {
    "id": "m27-20-5",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "kabuscorp",
    "homeTeam": "1.º de Maio",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 20
  },
  {
    "id": "m27-20-6",
    "homeTeamId": "interclube",
    "awayTeamId": "petro",
    "homeTeam": "Interclube",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 20
  },
  {
    "id": "m27-20-7",
    "homeTeamId": "lundasul",
    "awayTeamId": "desphuila",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 20
  },
  {
    "id": "m27-20-8",
    "homeTeamId": "libolo",
    "awayTeamId": "saosalvador",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-02-27T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 20
  },
  {
    "id": "m27-21-1",
    "homeTeamId": "bravos",
    "awayTeamId": "fcluanda",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 21
  },
  {
    "id": "m27-21-2",
    "homeTeamId": "sagrada",
    "awayTeamId": "cabinda",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 21
  },
  {
    "id": "m27-21-3",
    "homeTeamId": "wiliete",
    "awayTeamId": "caala",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 21
  },
  {
    "id": "m27-21-4",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "lobito",
    "homeTeam": "Kabuscorp",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 21
  },
  {
    "id": "m27-21-5",
    "homeTeamId": "dago",
    "awayTeamId": "interclube",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 21
  },
  {
    "id": "m27-21-6",
    "homeTeamId": "desphuila",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 21
  },
  {
    "id": "m27-21-7",
    "homeTeamId": "saosalvador",
    "awayTeamId": "petro",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 21
  },
  {
    "id": "m27-21-8",
    "homeTeamId": "lundasul",
    "awayTeamId": "libolo",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-06T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 21
  },
  {
    "id": "m27-22-1",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "fcluanda",
    "homeTeam": "1.º de Maio",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 22
  },
  {
    "id": "m27-22-2",
    "homeTeamId": "petro",
    "awayTeamId": "dago",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 22
  },
  {
    "id": "m27-22-3",
    "homeTeamId": "lobito",
    "awayTeamId": "lundasul",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 22
  },
  {
    "id": "m27-22-4",
    "homeTeamId": "libolo",
    "awayTeamId": "caala",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 22
  },
  {
    "id": "m27-22-5",
    "homeTeamId": "saosalvador",
    "awayTeamId": "sagrada",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 22
  },
  {
    "id": "m27-22-6",
    "homeTeamId": "bravos",
    "awayTeamId": "desphuila",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 22
  },
  {
    "id": "m27-22-7",
    "homeTeamId": "cabinda",
    "awayTeamId": "interclube",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 22
  },
  {
    "id": "m27-22-8",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "wiliete",
    "homeTeam": "Kabuscorp",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-13T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 22
  },
  {
    "id": "m27-23-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "wiliete",
    "homeTeam": "FC Luanda",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 23
  },
  {
    "id": "m27-23-2",
    "homeTeamId": "cabinda",
    "awayTeamId": "kabuscorp",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 23
  },
  {
    "id": "m27-23-3",
    "homeTeamId": "interclube",
    "awayTeamId": "bravos",
    "homeTeam": "Interclube",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 23
  },
  {
    "id": "m27-23-4",
    "homeTeamId": "sagrada",
    "awayTeamId": "desphuila",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 23
  },
  {
    "id": "m27-23-5",
    "homeTeamId": "caala",
    "awayTeamId": "saosalvador",
    "homeTeam": "CR Caála",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 23
  },
  {
    "id": "m27-23-6",
    "homeTeamId": "lobito",
    "awayTeamId": "libolo",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 23
  },
  {
    "id": "m27-23-7",
    "homeTeamId": "lundasul",
    "awayTeamId": "dago",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 23
  },
  {
    "id": "m27-23-8",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "petro",
    "homeTeam": "1.º de Maio",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-03-20T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 23
  },
  {
    "id": "m27-24-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "kabuscorp",
    "homeTeam": "FC Luanda",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 24
  },
  {
    "id": "m27-24-2",
    "homeTeamId": "wiliete",
    "awayTeamId": "interclube",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 24
  },
  {
    "id": "m27-24-3",
    "homeTeamId": "desphuila",
    "awayTeamId": "cabinda",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 24
  },
  {
    "id": "m27-24-4",
    "homeTeamId": "saosalvador",
    "awayTeamId": "bravos",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 24
  },
  {
    "id": "m27-24-5",
    "homeTeamId": "libolo",
    "awayTeamId": "sagrada",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 24
  },
  {
    "id": "m27-24-6",
    "homeTeamId": "lundasul",
    "awayTeamId": "caala",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 24
  },
  {
    "id": "m27-24-7",
    "homeTeamId": "petro",
    "awayTeamId": "lobito",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 24
  },
  {
    "id": "m27-24-8",
    "homeTeamId": "dago",
    "awayTeamId": "primeiromaio",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-03T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 24
  },
  {
    "id": "m27-25-1",
    "homeTeamId": "interclube",
    "awayTeamId": "fcluanda",
    "homeTeam": "Interclube",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 25
  },
  {
    "id": "m27-25-2",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "desphuila",
    "homeTeam": "Kabuscorp",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 25
  },
  {
    "id": "m27-25-3",
    "homeTeamId": "wiliete",
    "awayTeamId": "saosalvador",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 25
  },
  {
    "id": "m27-25-4",
    "homeTeamId": "cabinda",
    "awayTeamId": "libolo",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 25
  },
  {
    "id": "m27-25-5",
    "homeTeamId": "bravos",
    "awayTeamId": "lundasul",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 25
  },
  {
    "id": "m27-25-6",
    "homeTeamId": "sagrada",
    "awayTeamId": "petro",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 25
  },
  {
    "id": "m27-25-7",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "caala",
    "homeTeam": "1.º de Maio",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 25
  },
  {
    "id": "m27-25-8",
    "homeTeamId": "lobito",
    "awayTeamId": "dago",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-10T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 25
  },
  {
    "id": "m27-26-1",
    "homeTeamId": "desphuila",
    "awayTeamId": "fcluanda",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 26
  },
  {
    "id": "m27-26-2",
    "homeTeamId": "saosalvador",
    "awayTeamId": "interclube",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 26
  },
  {
    "id": "m27-26-3",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "libolo",
    "homeTeam": "Kabuscorp",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 26
  },
  {
    "id": "m27-26-4",
    "homeTeamId": "lundasul",
    "awayTeamId": "wiliete",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 26
  },
  {
    "id": "m27-26-5",
    "homeTeamId": "petro",
    "awayTeamId": "cabinda",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 26
  },
  {
    "id": "m27-26-6",
    "homeTeamId": "bravos",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 26
  },
  {
    "id": "m27-26-7",
    "homeTeamId": "dago",
    "awayTeamId": "sagrada",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 26
  },
  {
    "id": "m27-26-8",
    "homeTeamId": "caala",
    "awayTeamId": "lobito",
    "homeTeam": "CR Caála",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-17T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 26
  },
  {
    "id": "m27-27-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "saosalvador",
    "homeTeam": "FC Luanda",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 27
  },
  {
    "id": "m27-27-2",
    "homeTeamId": "libolo",
    "awayTeamId": "desphuila",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 27
  },
  {
    "id": "m27-27-3",
    "homeTeamId": "interclube",
    "awayTeamId": "lundasul",
    "homeTeam": "Interclube",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 27
  },
  {
    "id": "m27-27-4",
    "homeTeamId": "petro",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 27
  },
  {
    "id": "m27-27-5",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "wiliete",
    "homeTeam": "1.º de Maio",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 27
  },
  {
    "id": "m27-27-6",
    "homeTeamId": "cabinda",
    "awayTeamId": "dago",
    "homeTeam": "FC Cabinda",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 27
  },
  {
    "id": "m27-27-7",
    "homeTeamId": "lobito",
    "awayTeamId": "bravos",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 27
  },
  {
    "id": "m27-27-8",
    "homeTeamId": "sagrada",
    "awayTeamId": "caala",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-04-24T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 27
  },
  {
    "id": "m27-28-1",
    "homeTeamId": "libolo",
    "awayTeamId": "fcluanda",
    "homeTeam": "Recreativo do Libolo",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T15:00:00+01:00",
    "stadium": "Estádio Municipal de Calulo",
    "status": "scheduled",
    "round": 28
  },
  {
    "id": "m27-28-2",
    "homeTeamId": "saosalvador",
    "awayTeamId": "lundasul",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "Desportivo da Lunda Sul",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 28
  },
  {
    "id": "m27-28-3",
    "homeTeamId": "desphuila",
    "awayTeamId": "petro",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 28
  },
  {
    "id": "m27-28-4",
    "homeTeamId": "primeiromaio",
    "awayTeamId": "interclube",
    "homeTeam": "1.º de Maio",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T15:00:00+01:00",
    "stadium": "Estádio de São Filipe",
    "status": "scheduled",
    "round": 28
  },
  {
    "id": "m27-28-5",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "dago",
    "homeTeam": "Kabuscorp",
    "awayTeam": "1.º de Agosto",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 28
  },
  {
    "id": "m27-28-6",
    "homeTeamId": "wiliete",
    "awayTeamId": "lobito",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "Académica do Lobito",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 28
  },
  {
    "id": "m27-28-7",
    "homeTeamId": "caala",
    "awayTeamId": "cabinda",
    "homeTeam": "CR Caála",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T15:00:00+01:00",
    "stadium": "Estádio dos Mártires da Canhala",
    "status": "scheduled",
    "round": 28
  },
  {
    "id": "m27-28-8",
    "homeTeamId": "bravos",
    "awayTeamId": "sagrada",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-01T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 28
  },
  {
    "id": "m27-29-1",
    "homeTeamId": "lundasul",
    "awayTeamId": "fcluanda",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "FC Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 29
  },
  {
    "id": "m27-29-2",
    "homeTeamId": "petro",
    "awayTeamId": "libolo",
    "homeTeam": "Petro de Luanda",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T15:00:00+01:00",
    "stadium": "Estádio 11 de Novembro",
    "status": "scheduled",
    "round": 29
  },
  {
    "id": "m27-29-3",
    "homeTeamId": "saosalvador",
    "awayTeamId": "primeiromaio",
    "homeTeam": "São Salvador do Kongo",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T15:00:00+01:00",
    "stadium": "Estádio Álvaro Buta",
    "status": "scheduled",
    "round": 29
  },
  {
    "id": "m27-29-4",
    "homeTeamId": "dago",
    "awayTeamId": "desphuila",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "Desportivo da Huíla",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 29
  },
  {
    "id": "m27-29-5",
    "homeTeamId": "lobito",
    "awayTeamId": "interclube",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "Interclube",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 29
  },
  {
    "id": "m27-29-6",
    "homeTeamId": "kabuscorp",
    "awayTeamId": "caala",
    "homeTeam": "Kabuscorp",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T15:00:00+01:00",
    "stadium": "Estádio dos Coqueiros",
    "status": "scheduled",
    "round": 29
  },
  {
    "id": "m27-29-7",
    "homeTeamId": "sagrada",
    "awayTeamId": "wiliete",
    "homeTeam": "Sagrada Esperança",
    "awayTeam": "Wiliete de Benguela",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T15:00:00+01:00",
    "stadium": "Estádio Sagrada Esperança",
    "status": "scheduled",
    "round": 29
  },
  {
    "id": "m27-29-8",
    "homeTeamId": "cabinda",
    "awayTeamId": "bravos",
    "homeTeam": "FC Cabinda",
    "awayTeam": "Bravos do Maquis",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-08T15:00:00+01:00",
    "stadium": "Estádio Nacional do Chiazi",
    "status": "scheduled",
    "round": 29
  },
  {
    "id": "m27-30-1",
    "homeTeamId": "fcluanda",
    "awayTeamId": "petro",
    "homeTeam": "FC Luanda",
    "awayTeam": "Petro de Luanda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T15:00:00+01:00",
    "stadium": "Campo da Cidadela",
    "status": "scheduled",
    "round": 30
  },
  {
    "id": "m27-30-2",
    "homeTeamId": "lundasul",
    "awayTeamId": "primeiromaio",
    "homeTeam": "Desportivo da Lunda Sul",
    "awayTeam": "1.º de Maio",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T15:00:00+01:00",
    "stadium": "Estádio das Mangueiras",
    "status": "scheduled",
    "round": 30
  },
  {
    "id": "m27-30-3",
    "homeTeamId": "dago",
    "awayTeamId": "libolo",
    "homeTeam": "1.º de Agosto",
    "awayTeam": "Recreativo do Libolo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T15:00:00+01:00",
    "stadium": "Estádio França Ndalu",
    "status": "scheduled",
    "round": 30
  },
  {
    "id": "m27-30-4",
    "homeTeamId": "lobito",
    "awayTeamId": "saosalvador",
    "homeTeam": "Académica do Lobito",
    "awayTeam": "São Salvador do Kongo",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T15:00:00+01:00",
    "stadium": "Estádio do Buraco",
    "status": "scheduled",
    "round": 30
  },
  {
    "id": "m27-30-5",
    "homeTeamId": "desphuila",
    "awayTeamId": "caala",
    "homeTeam": "Desportivo da Huíla",
    "awayTeam": "CR Caála",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T15:00:00+01:00",
    "stadium": "Estádio da Tundavala",
    "status": "scheduled",
    "round": 30
  },
  {
    "id": "m27-30-6",
    "homeTeamId": "interclube",
    "awayTeamId": "sagrada",
    "homeTeam": "Interclube",
    "awayTeam": "Sagrada Esperança",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T15:00:00+01:00",
    "stadium": "Estádio 22 de Junho",
    "status": "scheduled",
    "round": 30
  },
  {
    "id": "m27-30-7",
    "homeTeamId": "bravos",
    "awayTeamId": "kabuscorp",
    "homeTeam": "Bravos do Maquis",
    "awayTeam": "Kabuscorp",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T15:00:00+01:00",
    "stadium": "Estádio Mundunduleno",
    "status": "scheduled",
    "round": 30
  },
  {
    "id": "m27-30-8",
    "homeTeamId": "wiliete",
    "awayTeamId": "cabinda",
    "homeTeam": "Wiliete de Benguela",
    "awayTeam": "FC Cabinda",
    "homeScore": 0,
    "awayScore": 0,
    "date": "2027-05-15T15:00:00+01:00",
    "stadium": "Estádio Nacional de Ombaka",
    "status": "scheduled",
    "round": 30
  }
];
