-- Liga Unitel Girabola - base da integracao FIFA FCMS
-- Pode ser executado mais de uma vez no SQL Editor do Supabase.
-- Requer as tabelas public.ancaf_teams e public.ancaf_matches do portal.

create extension if not exists pgcrypto;

create table if not exists public.ancaf_fcms_team_mappings (
  id bigint generated by default as identity primary key,
  provider text not null,
  tenant text not null,
  external_team_id text not null,
  team_id text not null references public.ancaf_teams(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (provider, tenant, external_team_id)
);

create index if not exists ancaf_fcms_team_mappings_team_idx
  on public.ancaf_fcms_team_mappings(team_id);

create table if not exists public.ancaf_fcms_match_mappings (
  id bigint generated by default as identity primary key,
  provider text not null,
  tenant text not null,
  external_match_id text not null,
  match_id text not null references public.ancaf_matches(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (provider, tenant, external_match_id)
);

create index if not exists ancaf_fcms_match_mappings_match_idx
  on public.ancaf_fcms_match_mappings(match_id);

create table if not exists public.ancaf_fcms_sync_runs (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  tenant text not null,
  competition_external_id text not null,
  season_id text not null,
  request_fingerprint text not null,
  dry_run boolean not null default true,
  status text not null default 'running'
    check (status in ('running', 'validated', 'completed', 'failed')),
  matches_received integer not null default 0,
  matches_written integer not null default 0,
  events_written integer not null default 0,
  error_message text,
  created_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz
);

create index if not exists ancaf_fcms_sync_runs_created_idx
  on public.ancaf_fcms_sync_runs(created_at desc);

alter table public.ancaf_fcms_team_mappings enable row level security;
alter table public.ancaf_fcms_match_mappings enable row level security;
alter table public.ancaf_fcms_sync_runs enable row level security;

drop policy if exists "fcms service mappings" on public.ancaf_fcms_team_mappings;
create policy "fcms service mappings" on public.ancaf_fcms_team_mappings
  for all to service_role using (true) with check (true);
drop policy if exists "fcms service matches" on public.ancaf_fcms_match_mappings;
create policy "fcms service matches" on public.ancaf_fcms_match_mappings
  for all to service_role using (true) with check (true);
drop policy if exists "fcms service runs" on public.ancaf_fcms_sync_runs;
create policy "fcms service runs" on public.ancaf_fcms_sync_runs
  for all to service_role using (true) with check (true);

-- Nomes oficiais e nomes de exibicao usados nos documentos FCMS/portal.
insert into public.ancaf_fcms_team_mappings
  (provider, tenant, external_team_id, team_id)
values
  ('authorised-push', 'ang', 'Estrela Clube Primeiro de Maio', 'primeiromaio'),
  ('authorised-push', 'ang', 'Estrela 1.º de Maio', 'primeiromaio'),
  ('authorised-push', 'ang', 'Wiliete Sport Clube de Benguela', 'wiliete'),
  ('authorised-push', 'ang', 'Wiliete de Benguela', 'wiliete'),
  ('authorised-push', 'ang', 'Clube Desportivo da Huila', 'desphuila'),
  ('authorised-push', 'ang', 'Clube Desportivo da Huíla', 'desphuila'),
  ('authorised-push', 'ang', 'Desportivo da Huíla', 'desphuila'),
  ('authorised-push', 'ang', 'Clube Desportivo 1.º de Agosto', 'dago'),
  ('authorised-push', 'ang', 'CD 1.º de Agosto', 'dago'),
  ('authorised-push', 'ang', 'Kabuscorp Sport Clube do Palanca', 'kabuscorp'),
  ('authorised-push', 'ang', 'Kabuscorp SC', 'kabuscorp'),
  ('authorised-push', 'ang', 'Académica Petróleos Clube do Lobito', 'lobito'),
  ('authorised-push', 'ang', 'Académica do Lobito', 'lobito'),
  ('authorised-push', 'ang', 'Futebol Clube de Luanda', 'fcluanda'),
  ('authorised-push', 'ang', 'FC Luanda', 'fcluanda'),
  ('authorised-push', 'ang', 'Clube Recreativo e Desportivo do Libolo', 'libolo'),
  ('authorised-push', 'ang', 'Recreativo do Libolo', 'libolo'),
  ('authorised-push', 'ang', 'Clube Recreativo da Caála', 'caala'),
  ('authorised-push', 'ang', 'CR Caála', 'caala'),
  ('authorised-push', 'ang', 'Grupo Desportivo Interclube', 'interclube'),
  ('authorised-push', 'ang', 'GD Interclube', 'interclube'),
  ('authorised-push', 'ang', 'Futebol Clube Bravos do Maquis', 'bravos'),
  ('authorised-push', 'ang', 'Bravos do Maquis', 'bravos'),
  ('authorised-push', 'ang', 'Clube Desportivo Sagrada Esperança', 'sagrada'),
  ('authorised-push', 'ang', 'Sagrada Esperança', 'sagrada'),
  ('authorised-push', 'ang', 'Clube Desportivo da Lunda-Sul', 'lundasul'),
  ('authorised-push', 'ang', 'Desportivo da Lunda Sul', 'lundasul'),
  ('authorised-push', 'ang', 'São Salvador do Kongo Futebol Clube', 'saosalvador'),
  ('authorised-push', 'ang', 'São Salvador', 'saosalvador'),
  ('authorised-push', 'ang', 'Atlético Petróleos de Luanda', 'petro'),
  ('authorised-push', 'ang', 'Petro de Luanda', 'petro'),
  ('authorised-push', 'ang', 'Futebol Clube de Cabinda', 'cabinda'),
  ('authorised-push', 'ang', 'FC Cabinda', 'cabinda')
on conflict (provider, tenant, external_team_id)
do update set
  team_id = excluded.team_id,
  updated_at = timezone('utc', now());

