-- ═════════════════════════════════════════════════════════════════════
-- CLUBES
-- Gerado por scripts/generate-db-seed.ts — não editar à mão.
-- ═════════════════════════════════════════════════════════════════════

insert into public.ancaf_teams (id, name, official_name, short_name, city, stadium, stadium_capacity, founded, colors, coach, president, nickname, website, colors_hex, kits, data_status, data_updated_at, is_historical, logo_url) values
  ('petro', 'Petro de Luanda', 'Atlético Petróleos de Luanda', 'APL', 'Luanda', 'Estádio 11 de Novembro', 50000, 1980, 'Amarelo, Azul e Preto', 'João Pedro Sousa', 'Tomás Faria', 'Tricolores', 'https://www.petroatletico.co.ao', array['#F9C304','#00529B','#000000']::text[], '[{"label":"Principal","colors":["#F9C304","#00529B","#000000"]},{"label":"Secundário","colors":["#000000"]}]'::jsonb, 'Atualizado', '2026-08-30', false, '/crests/petro.png'),
  ('wiliete', 'Wiliete de Benguela', 'Wiliete Sport Clube de Benguela', 'WIL', 'Benguela', 'Estádio Nacional de Ombaka', 35000, 2018, 'Verde e Amarelo', 'Beto Bianchi', 'Wilson Faria', 'Wilietes', 'https://www.wilietesc.ao', array['#008751','#F9C304']::text[], '[{"label":"Principal","colors":["#008751","#F9C304"]},{"label":"Secundário","colors":["#FFFFFF","#008751"]}]'::jsonb, 'Atualizado', '2026-08-31', false, '/crests/wiliete.png'),
  ('dago', 'CD 1.º de Agosto', 'Clube Desportivo 1.º de Agosto', '1AG', 'Luanda', 'Estádio França Ndalu', 20000, 1977, 'Vermelho e Preto', 'Filipe Nzanza', 'Gouveia de Sá Miranda', 'D'' Agosto', null, array['#D21515','#000000']::text[], '[{"label":"Principal","colors":["#D21515","#000000"]},{"label":"Secundário","colors":["#000000","#D21515"]}]'::jsonb, 'Atualizado', '2026-08-31', false, '/crests/dago.png'),
  ('desphuila', 'Desportivo da Huíla', 'Clube Desportivo da Huíla', 'CDH', 'Lubango', 'Estádio da Tundavala', 20000, 1998, 'Vermelho e Branco', 'Paulo Torres', 'Lucas Francisco Ndjongo', 'Huilanos', null, array['#D21515','#FFFFFF']::text[], '[{"label":"Principal","colors":["#D21515","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#D21515"]}]'::jsonb, 'Atualizado', '2026-08-31', false, '/crests/desphuila.png'),
  ('bravos', 'Bravos do Maquis', 'Futebol Clube Bravos do Maquis', 'BMQ', 'Luena', 'Estádio Mundunduleno', 4300, 1983, 'Azul e Branco', 'Lourenço Nelito', 'Agrione Manuel', 'Maquisardes', 'https://www.bravosdomaquis.co.ao', array['#00529B','#FFFFFF']::text[], '[{"label":"Principal","colors":["#00529B","#FFFFFF"]},{"label":"Secundário","colors":["#F9C304","#000000"]}]'::jsonb, 'Atualizado', '2026-08-31', false, '/crests/bravos.png'),
  ('kabuscorp', 'Kabuscorp SC', 'Kabuscorp Sport Clube do Palanca', 'KAB', 'Luanda', 'Estádio 22 de Junho', 12000, 1994, 'Vermelho e Branco', 'Leonardo Martins Neiva', 'Bento Kangamba', 'Palanquinos', null, array['#D21515','#FFFFFF']::text[], '[{"label":"Principal","colors":["#D21515","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#D21515"]}]'::jsonb, 'Atualizado', '2026-08-31', false, '/crests/kabuscorp.png'),
  ('sagrada', 'Sagrada Esperança', 'Clube Desportivo Sagrada Esperança', 'SAG', 'Dundo', 'Estádio Sagrada Esperança', 8000, 1976, 'Verde e Preto', 'Hungo Francisco Moniz', 'Oliveira Gonçalves', 'Lundas', null, array['#008751','#000000']::text[], '[{"label":"Principal","colors":["#008751","#000000"]},{"label":"Secundário","colors":["#000000","#008751"]}]'::jsonb, 'Atualizado', '2026-08-31', false, '/crests/sagrada.jpg'),
  ('interclube', 'GD Interclube', 'Grupo Desportivo Interclube', 'INT', 'Luanda', 'Estádio 22 de Junho', 8000, 1976, 'Azul e Branco', 'Divaldo da Silva Teixeira Alves', 'Alexandre Canelas', 'Polícias', 'https://www.interclube.co.ao', array['#00529B','#FFFFFF']::text[], '[{"label":"Principal","colors":["#00529B","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#00529B"]}]'::jsonb, 'Atualizado', '2026-08-31', false, '/crests/interclube.png'),
  ('lundasul', 'Desportivo da Lunda Sul', 'Clube Desportivo da Lunda-Sul', 'DLS', 'Saurimo', 'Estádio Sagrada Esperança', 7000, 2020, 'Verde e Amarelo', 'Maurílio Silva', 'Miguel da Silva', 'Tchianda', null, array['#008751','#F9C304']::text[], '[{"label":"Principal","colors":["#008751","#F9C304"]},{"label":"Secundário","colors":["#F9C304","#008751"]}]'::jsonb, 'Atualizado', '2026-08-31', false, '/crests/lundasul.png'),
  ('libolo', 'Recreativo do Libolo', 'Clube Recreativo e Desportivo do Libolo', 'CRL', 'Calulo', 'Estádio Municipal de Calulo', 10000, 1942, 'Laranja e Azul', 'Osvaldo Roque Gonçalves da Cruz', 'João Pereira', 'Libolenses', null, array['#FF6600','#00529B']::text[], '[{"label":"Principal","colors":["#FF6600","#00529B"]},{"label":"Secundário","colors":["#00529B","#FF6600"]}]'::jsonb, 'Atualizado', '2026-08-31', false, '/crests/libolo.png'),
  ('lobito', 'Académica do Lobito', 'Académica Petróleos Clube do Lobito', 'ACA', 'Lobito', 'Estádio da Tundavala', 5000, 1970, 'Preto e Branco', 'José Silvestre Pereira Jorge', 'Luís Borges', 'Estudantes', null, array['#000000','#FFFFFF']::text[], '[{"label":"Principal","colors":["#000000","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#000000"]}]'::jsonb, 'Atualizado', '2026-08-31', false, '/crests/lobito.png'),
  ('saosalvador', 'São Salvador', 'São Salvador do Kongo Futebol Clube', 'SSK', 'Mbanza Kongo', 'Estádio Álvaro Buta', 5000, 1999, 'Azul e Amarelo', 'Silva Kussanda', 'Moniz Manuel', 'Kongos', null, array['#00529B','#F9C304']::text[], '[{"label":"Principal","colors":["#00529B","#F9C304"]},{"label":"Secundário","colors":["#F9C304","#00529B"]}]'::jsonb, 'Atualizado', '2026-08-10', false, '/crests/saosalvador.png'),
  ('cabinda', 'FC Cabinda', 'Futebol Clube de Cabinda', 'FCC', 'Cabinda', 'Estádio Vici António', 25000, 2005, 'Azul e Branco', 'Nzola Seca', 'Raimundo Almeida', 'Gorilas do Norte', null, array['#00529B','#FFFFFF']::text[], '[{"label":"Principal","colors":["#00529B","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#00529B"]}]'::jsonb, 'Atualizado', '2026-08-10', false, '/crests/cabinda.png'),
  ('primeiromaio', 'Estrela 1.º de Maio', 'Estrela Clube Primeiro de Maio', 'MAI', 'Benguela', 'Estádio Municipal', 10000, 1981, 'Vermelho e Branco', 'Águas da Silva', 'Tony Santos', 'Proletários', null, array['#D21515','#FFFFFF']::text[], '[{"label":"Principal","colors":["#D21515","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#D21515"]}]'::jsonb, 'Atualizado', '2026-08-31', false, '/crests/primeiromaio.png'),
  ('caala', 'CR Caála', 'Clube Recreativo da Caála', 'CRC', 'Huambo', 'Estádio Daniel Cassoma Lutucuta', 12000, 1944, 'Azul e Branco', 'Artur Benjamim Correia', 'Mi Mosquito', 'Caalenses', null, array['#00529B','#FFFFFF']::text[], '[{"label":"Principal","colors":["#00529B","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#00529B"]}]'::jsonb, 'Atualizado', '2026-08-31', false, '/crests/caala.png'),
  ('fcluanda', 'FC Luanda', 'Futebol Clube de Luanda', 'FCL', 'Luanda', 'Estádio França Ndalu', 10000, 2020, 'Azul e Branco', 'Rui Santos', 'Paulino Silva', 'Luandenses', null, array['#00529B','#FFFFFF']::text[], '[{"label":"Principal","colors":["#00529B","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#00529B"]}]'::jsonb, 'Atualizado', '2026-08-31', false, '/crests/fcluanda.png'),
  ('isaac-benguela', 'Isaac de Benguela', 'Isaac de Benguela', 'ISA', 'Benguela', 'Estádio Nacional de Ombaka', 35000, 2018, 'Azul e Branco', '—', null, null, null, '{}'::text[], '[]'::jsonb, null, null, false, null),
  ('santa-rita', 'Santa Rita de Cássia', 'Santa Rita de Cássia', 'SRC', 'Uíge', 'Estádio 4 de Janeiro', 12000, 2015, 'Verde e Branco', '—', null, null, null, '{}'::text[], '[]'::jsonb, null, null, false, null),
  ('carmona', 'Carmona Sport Clube', 'Carmona Sport Clube', 'CSC', 'Uíge', 'Estádio 4 de Janeiro', 12000, 2022, 'Azul e Branco', '—', null, null, null, '{}'::text[], '[]'::jsonb, null, null, false, null),
  ('sporting-cabinda', 'Sporting de Cabinda', 'Sporting de Cabinda', 'SCA', 'Cabinda', 'Estádio do Tafe', 9000, 1975, 'Verde e Branco', '—', null, null, null, '{}'::text[], '[]'::jsonb, null, null, false, null),
  ('uniao-malanje', 'União de Malanje', 'União de Malanje', 'USM', 'Malanje', 'Estádio 1.º de Maio', 6000, 2019, 'Vermelho e Branco', '—', null, null, null, '{}'::text[], '[]'::jsonb, null, null, false, null),
  ('ask-dragao', 'ASK Dragão', 'ASK Dragão', 'ASK', 'Uíge', 'Estádio 4 de Janeiro', 12000, 2017, 'Azul e Branco', '—', null, null, null, '{}'::text[], '[]'::jsonb, null, null, false, null),
  ('sporting-benguela', 'Sporting de Benguela', 'Sporting de Benguela', 'SBE', 'Benguela', 'Estádio de São Filipe', 5000, 1915, 'Verde e Branco', '—', null, null, null, '{}'::text[], '[]'::jsonb, null, null, false, null),
  ('redonda', 'Redonda FC', 'Redonda Futebol Clube', 'RED', 'Luanda', 'A confirmar', 0, 0, 'Vermelho e Amarelo', '—', null, null, null, '{}'::text[], '[]'::jsonb, null, null, false, null),
  ('guelson', 'Guelson FC', 'Recreativo Social Desportivo Guelson Futebol Clube', 'GFC', 'Luanda', 'A confirmar', 0, 0, 'Laranja e Preto', '—', null, null, null, '{}'::text[], '[]'::jsonb, null, null, false, null),
  ('luanda-city', 'Luanda City', 'Luanda City Football Club', 'LCF', 'Luanda', 'A confirmar', 0, 0, 'A confirmar', '—', null, null, null, '{}'::text[], '[]'::jsonb, null, null, false, null)
on conflict (id) do update set name = excluded.name, official_name = excluded.official_name, short_name = excluded.short_name, city = excluded.city, stadium = excluded.stadium, stadium_capacity = excluded.stadium_capacity, founded = excluded.founded, colors = excluded.colors, coach = excluded.coach, president = excluded.president, nickname = excluded.nickname, website = excluded.website, colors_hex = excluded.colors_hex, kits = excluded.kits, data_status = excluded.data_status, data_updated_at = excluded.data_updated_at, is_historical = excluded.is_historical, logo_url = excluded.logo_url;
