-- ═════════════════════════════════════════════════════════════════════
-- PERFIS INSTITUCIONAIS DOS CLUBES
-- Gerado por scripts/generate-db-seed.ts — não editar à mão.
-- ═════════════════════════════════════════════════════════════════════

insert into public.ancaf_team_profiles (team_id, official_name, president, website, socials, palmares, kits, board) values
  ('petro', 'Atlético Petróleos de Luanda', 'Tomás Faria', 'https://www.petroatletico.co.ao', '{"facebook":"https://www.facebook.com/atleticopetroleosluanda","instagram":"https://www.instagram.com/petro_de_luanda_oficial/","youtube":"https://www.youtube.com/@petrodeluandaoficial"}'::jsonb, '[{"title":"Liga Unitel Girabola","count":20,"seasons":["2025/26","2023/24","2022/23"]},{"title":"Taça de Angola","count":15},{"title":"Supertaça de Angola","count":10,"seasons":["2026/27","2025/26","2024/25","2023/24"]}]'::jsonb, '[{"label":"Principal","colors":["#F9C304","#00529B","#000000"]},{"label":"Secundário","colors":["#000000"]}]'::jsonb, '[{"role":"Presidente","name":"Tomás Faria"},{"role":"Vice-presidente","name":"Nuno Saraiva"},{"role":"Diretor Desportivo","name":"Love Kabungula"}]'::jsonb),
  ('wiliete', 'Wiliete Sport Clube de Benguela', 'Wilson Faria', 'https://www.wilietesc.ao', '{"facebook":"https://www.facebook.com/wscbenguela/","instagram":"https://www.instagram.com/wilietesportclubeoficial/"}'::jsonb, '[{"title":"Taça de Angola","count":1},{"title":"Gira Bola B (2.ª Divisão)","count":1,"seasons":["2021/22"]}]'::jsonb, '[{"label":"Principal","colors":["#008751","#F9C304"]},{"label":"Secundário","colors":["#FFFFFF","#008751"]}]'::jsonb, '[{"role":"Presidente","name":"Wilson Faria"}]'::jsonb),
  ('dago', 'Clube Desportivo 1.º de Agosto', 'Gouveia de Sá Miranda', null, '{"facebook":"https://www.facebook.com/clube1deagosto/","instagram":"https://www.instagram.com/clube1deagosto/"}'::jsonb, '[{"title":"Liga Unitel Girabola","count":13,"seasons":["2018/19","2017/18","2016/17"]},{"title":"Taça de Angola","count":6},{"title":"Supertaça de Angola","count":10}]'::jsonb, '[{"label":"Principal","colors":["#D21515","#000000"]},{"label":"Secundário","colors":["#000000","#D21515"]}]'::jsonb, '[{"role":"Presidente","name":"Gouveia de Sá Miranda"},{"role":"Vice-presidente","name":"Adilson Kiala"},{"role":"Diretor Desportivo","name":"Beto Almeida"}]'::jsonb),
  ('desphuila', 'Clube Desportivo da Huíla', 'Lucas Francisco Ndjongo', null, '{"facebook":"https://www.facebook.com/CDhuila/","instagram":"https://www.instagram.com/clubedesportivodahuila_/"}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#D21515","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#D21515"]}]'::jsonb, '[{"role":"Presidente","name":"Lucas Francisco Ndjongo"}]'::jsonb),
  ('bravos', 'Futebol Clube Bravos do Maquis', 'Agrione Manuel', 'https://www.bravosdomaquis.co.ao', '{"facebook":"https://www.facebook.com/p/Bravos-do-Maquis-do-Moxico-100095414350444/","instagram":"https://www.instagram.com/bravosdomaquis/"}'::jsonb, '[{"title":"Taça de Angola","count":1,"seasons":["2019/20"]}]'::jsonb, '[{"label":"Principal","colors":["#00529B","#FFFFFF"]},{"label":"Secundário","colors":["#F9C304","#000000"]}]'::jsonb, '[{"role":"Presidente","name":"Agrione Manuel"}]'::jsonb),
  ('kabuscorp', 'Kabuscorp Sport Clube do Palanca', 'Bento Kangamba', null, '{"facebook":"https://www.facebook.com/kabuscorpscp","instagram":"https://www.instagram.com/kabuscorp_sport_clube/"}'::jsonb, '[{"title":"Liga Unitel Girabola","count":1},{"title":"Taça de Angola","count":1},{"title":"Supertaça de Angola","count":1}]'::jsonb, '[{"label":"Principal","colors":["#D21515","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#D21515"]}]'::jsonb, '[{"role":"Presidente","name":"Bento Kangamba"}]'::jsonb),
  ('sagrada', 'Clube Desportivo Sagrada Esperança', 'Oliveira Gonçalves', null, '{"facebook":"https://www.facebook.com/sagradaesperancaln/","instagram":"https://www.instagram.com/cdsagradaesperanca/"}'::jsonb, '[{"title":"Liga Unitel Girabola","count":1,"seasons":["2004/05"]},{"title":"Taça de Angola","count":2}]'::jsonb, '[{"label":"Principal","colors":["#008751","#000000"]},{"label":"Secundário","colors":["#000000","#008751"]}]'::jsonb, '[{"role":"Presidente","name":"Oliveira Gonçalves"}]'::jsonb),
  ('interclube', 'Grupo Desportivo Interclube', 'Alexandre Canelas', 'https://www.interclube.co.ao', '{"facebook":"https://www.facebook.com/InterclubeAngolaGDI/","instagram":"https://www.instagram.com/interclube_angola/"}'::jsonb, '[{"title":"Taça de Angola","count":3},{"title":"Supertaça de Angola","count":1}]'::jsonb, '[{"label":"Principal","colors":["#00529B","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#00529B"]}]'::jsonb, '[{"role":"Presidente","name":"Alexandre Canelas"}]'::jsonb),
  ('lundasul', 'Clube Desportivo da Lunda-Sul', 'Miguel da Silva', null, '{"facebook":"https://www.facebook.com/p/Clube-Desportivo-Da-Lunda-Sul-100077348542835/","instagram":"https://www.instagram.com/clubedesportivodalundasul/"}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#008751","#F9C304"]},{"label":"Secundário","colors":["#F9C304","#008751"]}]'::jsonb, '[{"role":"Presidente","name":"Miguel da Silva"}]'::jsonb),
  ('libolo', 'Clube Recreativo e Desportivo do Libolo', 'João Pereira', null, '{"facebook":"https://www.facebook.com/recreativo.libolo/","instagram":"https://www.instagram.com/recreativo.libolo/"}'::jsonb, '[{"title":"Liga Unitel Girabola","count":4,"seasons":["2015/16","2014/15","2012/13"]},{"title":"Taça de Angola","count":1},{"title":"Supertaça de Angola","count":2}]'::jsonb, '[{"label":"Principal","colors":["#FF6600","#00529B"]},{"label":"Secundário","colors":["#00529B","#FF6600"]}]'::jsonb, '[{"role":"Presidente","name":"João Pereira"}]'::jsonb),
  ('lobito', 'Académica Petróleos Clube do Lobito', 'Luís Borges', null, '{"facebook":"https://www.facebook.com/academicadolobito/","instagram":"https://www.instagram.com/academicadolobito/"}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#000000","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#000000"]}]'::jsonb, '[{"role":"Presidente","name":"Luís Borges"}]'::jsonb),
  ('saosalvador', 'São Salvador do Kongo Futebol Clube', 'Moniz Manuel', null, '{"facebook":"https://www.facebook.com/saosalvadordokongo","instagram":"https://www.instagram.com/cdsaosalvador/"}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#00529B","#F9C304"]},{"label":"Secundário","colors":["#F9C304","#00529B"]}]'::jsonb, '[{"role":"Presidente","name":"Moniz Manuel"}]'::jsonb),
  ('cabinda', 'Futebol Clube de Cabinda', 'Raimundo Almeida', null, '{"facebook":"https://www.facebook.com/fccabinda","instagram":"https://www.instagram.com/fccabinda"}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#00529B","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#00529B"]}]'::jsonb, '[{"role":"Presidente","name":"Raimundo Almeida"}]'::jsonb),
  ('primeiromaio', 'Estrela Clube Primeiro de Maio', 'Tony Santos', null, '{"facebook":"https://www.facebook.com/EstrelaClub1oDeMaioDeBenguela"}'::jsonb, '[{"title":"Liga Unitel Girabola","count":2},{"title":"Taça de Angola","count":3},{"title":"Supertaça de Angola","count":1},{"title":"Gira Bola B (2.ª Divisão)","count":2}]'::jsonb, '[{"label":"Principal","colors":["#D21515","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#D21515"]}]'::jsonb, '[{"role":"Presidente","name":"Tony Santos"}]'::jsonb),
  ('caala', 'Clube Recreativo da Caála', 'Mi Mosquito', null, '{"facebook":"https://www.facebook.com/ClubeRecreativodaCaala"}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#00529B","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#00529B"]}]'::jsonb, '[{"role":"Presidente","name":"Mi Mosquito"}]'::jsonb),
  ('fcluanda', 'Futebol Clube de Luanda', 'Paulino Silva', null, '{"facebook":"https://www.facebook.com/923669860835536","instagram":"https://www.instagram.com/fcluanda_oficial/"}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#00529B","#FFFFFF"]},{"label":"Secundário","colors":["#FFFFFF","#00529B"]}]'::jsonb, '[{"role":"Presidente","name":"Paulino Silva"}]'::jsonb),
  ('isaac-benguela', 'Isaac de Benguela', null, null, '{}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#5C0F8B","#E6540F"]},{"label":"Alternativo","colors":["#E6540F","#5C0F8B"]}]'::jsonb, '[]'::jsonb),
  ('santa-rita', 'Santa Rita de Cássia', null, null, '{}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#5C0F8B","#E6540F"]},{"label":"Alternativo","colors":["#E6540F","#5C0F8B"]}]'::jsonb, '[]'::jsonb),
  ('carmona', 'Carmona Sport Clube', null, null, '{}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#5C0F8B","#E6540F"]},{"label":"Alternativo","colors":["#E6540F","#5C0F8B"]}]'::jsonb, '[]'::jsonb),
  ('sporting-cabinda', 'Sporting de Cabinda', null, null, '{}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#5C0F8B","#E6540F"]},{"label":"Alternativo","colors":["#E6540F","#5C0F8B"]}]'::jsonb, '[]'::jsonb),
  ('uniao-malanje', 'União de Malanje', null, null, '{}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#5C0F8B","#E6540F"]},{"label":"Alternativo","colors":["#E6540F","#5C0F8B"]}]'::jsonb, '[]'::jsonb),
  ('ask-dragao', 'ASK Dragão', null, null, '{}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#5C0F8B","#E6540F"]},{"label":"Alternativo","colors":["#E6540F","#5C0F8B"]}]'::jsonb, '[]'::jsonb),
  ('sporting-benguela', 'Sporting de Benguela', null, null, '{}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#5C0F8B","#E6540F"]},{"label":"Alternativo","colors":["#E6540F","#5C0F8B"]}]'::jsonb, '[]'::jsonb),
  ('redonda', 'Redonda Futebol Clube', null, null, '{}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#5C0F8B","#E6540F"]},{"label":"Alternativo","colors":["#E6540F","#5C0F8B"]}]'::jsonb, '[]'::jsonb),
  ('guelson', 'Recreativo Social Desportivo Guelson Futebol Clube', null, null, '{}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#5C0F8B","#E6540F"]},{"label":"Alternativo","colors":["#E6540F","#5C0F8B"]}]'::jsonb, '[]'::jsonb),
  ('luanda-city', 'Luanda City Football Club', null, null, '{}'::jsonb, '[]'::jsonb, '[{"label":"Principal","colors":["#5C0F8B","#E6540F"]},{"label":"Alternativo","colors":["#E6540F","#5C0F8B"]}]'::jsonb, '[]'::jsonb)
on conflict (team_id) do update set official_name = excluded.official_name, president = excluded.president, website = excluded.website, socials = excluded.socials, palmares = excluded.palmares, kits = excluded.kits, board = excluded.board;
