-- ═════════════════════════════════════════════════════════════════════
-- NOTÍCIAS
-- Gerado por scripts/generate-db-seed.ts — não editar à mão.
-- ═════════════════════════════════════════════════════════════════════

insert into public.ancaf_news (id, title, category, date, iso_date, summary, content, status, author, source_name, source_url, published_at, document_images, document_url, ai_assisted) values
  ('comunicado-oficial-006-dce-ancaf-2026', 'Publicação da 6.ª à 10.ª jornada da Liga Unitel Girabola 2026/2027', 'Comunicado Oficial', '2026-09-11T00:00:00.000Z', '2026-09-11', 'Programação corrigida: CD da Huíla x Académica do Lobito em 20/09 às 15:30 e CD da Huíla x São Salvador em 11/10 às 15:30.', 'Atualização da programação da Liga Unitel Girabola 2026/2027: na 5.ª jornada, CD da Huíla x Académica do Lobito joga-se no domingo, 20 de setembro de 2026, às 15:30, no Estádio da Tundavala.

Na 6.ª jornada, CD da Huíla x São Salvador joga-se no domingo, 11 de outubro de 2026, às 15:30, no mesmo estádio.

O PDF disponibilizado nesta notícia contém a programação do Comunicado Oficial n.º 006-DCE/ANCAF/2026 com a linha da 6.ª jornada corrigida e uma página adicional que identifica as duas alterações. Os restantes jogos mantêm a programação apresentada.', 'published', 'Direção de Competições da ANCAF', 'ANCAF — Associação Nacional dos Clubes Angolanos de Futebol', 'https://ancaf.co.ao', '2026-09-11T10:00:00+01:00', '["/comunicados/comunicado-006-2026/pagina-1.png","/comunicados/comunicado-006-2026/pagina-2.png"]'::jsonb, '/comunicados/comunicado-006-2026/comunicado-006-dce-ancaf-2026.pdf', false),
  ('comunicado-oficial-005-dce-ancaf-2026', 'Minuto de silêncio em homenagem a Eduardo Agostinho', 'Comunicado Oficial', '2026-08-26T00:00:00.000Z', '2026-08-26', 'A ANCAF autoriza um minuto de silêncio no jogo entre o Estrela 1.º de Maio de Benguela e o CD 1.º de Agosto, em homenagem a Eduardo Agostinho.', 'O Comunicado Oficial n.º 005-DCE/ANCAF/2026 autoriza o cumprimento de um minuto de silêncio em homenagem a Eduardo Agostinho, pelos seus contributos como jogador e treinador, no jogo entre o Estrela Clube 1.º de Maio de Benguela e o CD 1.º de Agosto, referente à segunda jornada da Liga Unitel Girabola 2026/2027.

O documento é dirigido aos 16 clubes participantes, foi emitido em Luanda, a 26 de agosto de 2026, pela Direção de Competições da Associação Nacional dos Clubes Angolanos de Futebol, e é assinado pelo Director de Competições, Valódia dos Santos, e pelo Presidente da ANCAF, João Lusevi Kueno.', 'published', 'Direção de Competições da ANCAF', 'ANCAF — Associação Nacional dos Clubes Angolanos de Futebol', 'https://ancaf.co.ao', '2026-08-26T21:13:40+01:00', '["/comunicados/comunicado-005-2026/pagina-1.png"]'::jsonb, '/comunicados/comunicado-005-2026/comunicado-005-dce-ancaf-2026.pdf', false),
  ('comunicado-oficial-003-dce-ancaf-2026', 'Minuto de silêncio em homenagem a Augusto Kitadica "Docas"', 'Comunicado Oficial', '2026-08-18T00:00:00.000Z', '2026-08-18', 'A ANCAF determina o cumprimento de um minuto de silêncio em todos os jogos da primeira jornada da Liga Unitel Girabola 2026/2027.', 'O Comunicado Oficial n.º 003-DCE/ANCAF/2026 determina o cumprimento de um minuto de silêncio em homenagem a Augusto Kitadica "Docas" em todos os jogos da primeira jornada da Liga Unitel Girabola 2026/2027.

O comunicado é dirigido aos 16 clubes participantes, foi emitido em Luanda, a 18 de agosto de 2026, pela Direção de Competições da Associação Nacional dos Clubes Angolanos de Futebol, e assinado pelo Presidente da ANCAF, João Lusevi Kueno.', 'published', 'Direção de Competições da ANCAF', 'ANCAF — Associação Nacional dos Clubes Angolanos de Futebol', 'https://ancaf.co.ao', '2026-08-18T00:00:00+01:00', '["/comunicados/comunicado-003-2026/pagina-1.png"]'::jsonb, '/comunicados/comunicado-003-2026/comunicado-003-dce-ancaf-2026.pdf', false),
  ('comunicado-oficial-004-dce-ancaf-2026', 'ANCAF esclarece o modelo de calendarização e programação do Girabola 2026/2027', 'Comunicado Oficial', '2026-08-15T00:00:00.000Z', '2026-08-15', 'A Direção de Competições esclarece aos 16 clubes os critérios de calendarização, transmissão televisiva e programação dos jogos da Liga Unitel Girabola.', 'O Comunicado Oficial n.º 004-DCE/ANCAF/2026 esclarece que a calendarização e a programação dos jogos passam a ser uma responsabilidade exclusiva da liga organizadora, em resposta às exigências comerciais, televisivas e regulamentares da competição. Segundo a ANCAF, a distribuição dos encontros ao longo de cada jornada permitirá a transmissão de dois a cinco jogos e apoiará a monetização do campeonato.

As jornadas serão disputadas à sexta-feira, sábado, domingo e segunda-feira. Também poderá haver antecipação de jogos para terça, quarta ou quinta-feira devido à participação das equipas angolanas nas competições da CAF.

A programação poderá ainda considerar datas FIFA, jogos da seleção nacional, competições da CAF, questões políticas ou religiosas, segurança pública, condições climáticas e grandes clássicos internacionais que possam afetar a audiência da Liga Unitel Girabola.

Na mensagem final, a ANCAF defende um campeonato moderno, sustentável e respeitado, apelando à disciplina, cooperação e adaptação dos clubes ao novo modelo. O documento é assinado pelo Director de Competições, Valódia dos Santos, e pelo Presidente da ANCAF, João Lusevi Kueno.', 'published', 'Direção de Competições da ANCAF', 'ANCAF — Associação Nacional dos Clubes Angolanos de Futebol', 'https://ancaf.co.ao', '2026-08-19T14:35:09+01:00', '["/comunicados/comunicado-004-2026/pagina-1.png","/comunicados/comunicado-004-2026/pagina-2.png"]'::jsonb, '/comunicados/comunicado-004-2026/comunicado-004-dce-ancaf-2026.pdf', false),
  ('mensagem-presidente-ancaf-liga-unitel-girabola-2026-27', 'Mensagem do Presidente da ANCAF sobre a Liga Unitel Girabola 2026/2027', 'Comunicado Oficial', '2026-08-19T00:00:00.000Z', '2026-08-19', 'O Presidente da ANCAF esclarece as razões e os benefícios do novo modelo centralizado de calendarização e programação dos jogos da Liga Unitel Girabola.', 'A mensagem dirigida aos presidentes dos clubes explica que a centralização das datas e dos horários procura proteger o interesse coletivo, aumentar a visibilidade da competição e criar melhores condições para a transmissão televisiva. A posição resulta de consulta interna da ANCAF e conta com o apoio e alinhamento da Federação Angolana de Futebol.

O documento apresenta como benefícios o crescimento progressivo das receitas comerciais, a melhor preparação dos representantes angolanos nas competições da CAF, a valorização dos jogadores, o reforço da credibilidade perante investidores e a adoção de práticas utilizadas pelas principais ligas profissionais.

As jornadas poderão decorrer entre sexta-feira e segunda-feira. A programação continuará a considerar datas FIFA, competições da CAF, disponibilidade das infraestruturas, segurança pública, condições climáticas e eventos nacionais, políticos, religiosos ou culturais relevantes.

A ANCAF apela à compreensão, colaboração e responsabilidade dos clubes, defendendo que um Girabola mais organizado, visível e sustentável criará oportunidades e benefícios para todos os participantes. A mensagem foi emitida em Luanda, a 19 de agosto de 2026, e assinada pelo Presidente da ANCAF, João Lusevi Kueno.', 'published', 'João Lusevi Kueno — Presidente da ANCAF', 'ANCAF — Associação Nacional dos Clubes Angolanos de Futebol', 'https://ancaf.co.ao', '2026-08-19T13:36:21+01:00', '["/comunicados/mensagem-presidente-ancaf-2026/pagina-1.png","/comunicados/mensagem-presidente-ancaf-2026/pagina-2.png","/comunicados/mensagem-presidente-ancaf-2026/pagina-3.png","/comunicados/mensagem-presidente-ancaf-2026/pagina-4.png"]'::jsonb, '/comunicados/mensagem-presidente-ancaf-2026/mensagem-presidente-ancaf-19-agosto-2026.pdf', false),
  ('comunicado-oficial-002-dce-ancaf-2026', 'Publicação da 1.ª à 5.ª jornada da Liga Unitel Girabola 2026/2027', 'Comunicado Oficial', '2026-08-15T00:00:00.000Z', '2026-08-15', 'A ANCAF publica a programação oficial das cinco primeiras jornadas da Liga Unitel Girabola na época 2026/2027.', 'O Comunicado Oficial n.º 002-DCE/ANCAF/2026 publica a programação da 1.ª à 5.ª jornada da Liga Unitel Girabola 2026/2027 para conhecimento dos 16 clubes participantes.

O documento reúne, num único mapa oficial, os confrontos, as datas, os horários e os jogos com transmissão em direto pela Zsports. A programação nele apresentada passa a orientar os cartões de jogos, o calendário e os restantes módulos informativos do portal.

Sincronizado! Qualquer actualização por parte da Zap será comunicada atempadamente.

O comunicado foi emitido em Luanda, a 15 de agosto de 2026, pela Direção de Competições da Associação Nacional dos Clubes Angolanos de Futebol.', 'published', 'Direção de Competições da ANCAF', 'ANCAF — Associação Nacional dos Clubes Angolanos de Futebol', 'https://ancaf.co.ao', '2026-08-15T00:00:00+01:00', '["/comunicados/comunicado-002-2026/pagina-1.png"]'::jsonb, '/comunicados/comunicado-002-2026/comunicado-002-dce-ancaf-2026.pdf', false),
  ('comunicado-oficial-001-dce-ancaf-2026', 'Gestão Equitativa de Jogos, Transparência Financeira e Condições Operacionais na Época 2026/2027', 'Comunicado Oficial', '2026-08-15T00:00:00.000Z', '2026-08-15', 'A ANCAF estabelece diretrizes operacionais e financeiras para os 16 clubes participantes da Liga Unitel Girabola na época 2026/2027.', 'O Comunicado Oficial n.º 001-DCE/ANCAF/2026 estabelece orientações sobre a gestão operacional e a equidade dos jogos, a transparência financeira e a distribuição de dividendos, as condições operacionais e de colaboração, o licenciamento e as vistorias dos estádios, bem como recomendações administrativas finais.

O documento determina o cumprimento integral do calendário oficial, reforça a aplicação igualitária dos regulamentos e a não discriminação, e define princípios de transparência para receitas comerciais, direitos televisivos e distribuição de dividendos.

Os clubes devem colaborar com a empresa detentora dos direitos televisivos, assegurar condições para conferências de imprensa e para o trabalho dos delegados da Liga. O licenciamento compete à Federação Angolana de Futebol, e os jogos serão realizados apenas em estádios aprovados pela FAF.

O comunicado foi emitido em Luanda, a 15 de agosto de 2026, pela Direção de Competições da ANCAF, e assinado pelo Director de Competições, Valódia dos Santos, e pelo Presidente, João Lusevi Kueno.', 'published', 'Direção de Competições da ANCAF', 'ANCAF — Associação Nacional dos Clubes Angolanos de Futebol', 'https://ancaf.co.ao', '2026-08-15T00:00:00+01:00', '["/comunicados/comunicado-001-2026/pagina-1.png","/comunicados/comunicado-001-2026/pagina-2.png","/comunicados/comunicado-001-2026/pagina-3.png"]'::jsonb, null, false),
  ('draft-arranque-girabola-2026-27', 'ANCAF aponta 22 de agosto para o arranque do Girabola 2026/2027', 'Competição', '2026-08-06T00:00:00.000Z', '2026-08-06', 'A nova temporada do principal campeonato nacional tem início previsto para 22 de agosto, segundo informação divulgada pela Rádio Nacional de Angola.', 'A Liga Unitel Girabola 2026/2027 tem o arranque previsto para 22 de agosto. A informação foi divulgada pela Rádio Nacional de Angola, que atribui a definição do calendário à Associação Nacional dos Clubes Angolanos de Futebol.

A data orienta a preparação dos clubes participantes e o planeamento das jornadas da nova época. A confirmação editorial final deverá considerar qualquer atualização posterior publicada pela organização da competição.', 'pending_review', 'Redação Liga Unitel Girabola', 'Rádio Nacional de Angola', 'https://rna.ao/rna.ao/2026/07/17/ancaf-define-data-de-arranque-da-liga-unitel-girabola-2026-2027/', null, '[]'::jsonb, null, true),
  ('draft-deybi-flores-petro', 'Deybi Flores reforça o meio-campo do Petro de Luanda', 'Mercado', '2026-08-06T00:00:00.000Z', '2026-08-06', 'O médio internacional hondurenho surge como reforço do campeão nacional para a preparação da temporada 2026/2027.', 'O Petro de Luanda reforçou o meio-campo com o internacional hondurenho Deybi Flores, segundo informação publicada pelo Jornal de Angola. A contratação integra a preparação do plantel tricolor para os desafios da temporada 2026/2027.

Antes da publicação definitiva, a redação deverá confirmar os dados contratuais e a apresentação do atleta nos canais oficiais do clube.', 'pending_review', 'Redação Liga Unitel Girabola', 'Jornal de Angola', 'https://jornaldeangola.ao/noticias/6/desporto/678493/deybi-flores-refor%C3%A7a-petro-de-luanda', null, '[]'::jsonb, null, true),
  ('draft-fc-luanda-promocao', 'FC Luanda alcança apuramento inédito ao Girabola', 'Clubes', '2026-08-06T00:00:00.000Z', '2026-08-06', 'O clube da capital garantiu presença na edição 2026/2027 e prepara a primeira participação no principal campeonato nacional.', 'O FC Luanda garantiu o apuramento para a Liga Unitel Girabola 2026/2027, num marco descrito como inédito na história do clube. A promoção coloca a formação de Luanda entre os participantes da próxima edição do principal campeonato nacional.

A equipa deverá agora concluir o processo de preparação desportiva e administrativa para a estreia entre a elite do futebol angolano.', 'pending_review', 'Redação Liga Unitel Girabola', 'Jornal O País', 'https://www.opais.ao/desporto/inedito-fc-luanda-garante-apuramento-ao-girabola-2026-2027/', null, '[]'::jsonb, null, true),
  ('draft-huila-plantel-renovado', 'Desportivo da Huíla abre temporada com plantel renovado', 'Pré-época', '2026-08-06T00:00:00.000Z', '2026-08-06', 'A formação huilana inicia a preparação para a nova época com uma renovação próxima de metade do plantel.', 'O Desportivo da Huíla iniciou a temporada com uma renovação significativa do plantel. Segundo a ANGOP, cerca de 47 por cento do grupo foi renovado para a preparação da Liga Unitel Girabola 2026/2027.

A reformulação procura dar novas opções à equipa técnica e criar condições para uma campanha competitiva no campeonato nacional.', 'pending_review', 'Redação Liga Unitel Girabola', 'ANGOP', 'https://angop.ao/noticias/desporto/desportivo-da-huila-abre-temporada-com-quase-metade-do-plantel-renovado/', null, '[]'::jsonb, null, true),
  ('draft-academica-lobito-financiamento', 'Académica do Lobito procura apoios para disputar a nova época', 'Clubes', '2026-08-06T00:00:00.000Z', '2026-08-06', 'A direção da Briosa alerta para necessidades financeiras antes da participação no Girabola 2026/2027.', 'A Académica do Lobito procura mobilizar apoios financeiros para assegurar a participação na Liga Unitel Girabola 2026/2027. De acordo com o Jornal de Angola, o clube indicou uma necessidade de 300 milhões de kwanzas no quadro da preparação para a competição.

Por se tratar de informação financeira sensível, o conteúdo deverá receber confirmação direta da direção do clube antes da publicação definitiva.', 'pending_review', 'Redação Liga Unitel Girabola', 'Jornal de Angola', 'https://jornaldeangola.ao/noticias/6/desporto/680778/acad%C3%A9mica-do-lobito-precisa-de-300-milh%C3%B5es', null, '[]'::jsonb, null, true),
  ('n1', 'Petro de Luanda vence o clássico no 11 de Novembro contra 1.º de Agosto', 'Liga Unitel Girabola', '2026-06-13T00:00:00.000Z', '2026-06-13', 'Com golo solitário de Tiago Azulão aos 88 minutos, os tricolores asseguraram a liderança da tabela.', 'O clássico dos clássicos do futebol angolano terminou com a vitória tangencial do Petro de Luanda sobre o rival Primeiro de Agosto. Num jogo tenso e disputado taticamente, o avançado brasileiro Tiago Azulão voltou a ser decisivo, finalizando de cabeça um cruzamento milimétrico de Jaredi aos 88 minutos, despoletando a loucura no Estádio 11 de Novembro. Esta vitória consolida a liderança isolada dos tricolores na presente campanha de preparação da liga.', 'published', null, null, null, null, '[]'::jsonb, null, false),
  ('n2', 'Manuel Keliano destaca subida de rendimento no meio-campo', 'Entrevista', '2026-06-12T00:00:00.000Z', '2026-06-12', 'O internacional angolano analisou a fase positiva da equipa e o próximo jogo contra o Kabuscorp.', 'Em conferência de imprensa após os treinos do Primeiro de Agosto no complexo França Ndalu, o jovem virtuoso Manuel Keliano analisou a rápida transição da equipa para novos esquemas táticos. Keliano expressou que a intensidade imposta nos treinos começa a traduzir-se em exibições de classe, sublinhando que o grupo está altamente focado em garantir a vitória no próximo desafio contra o Kabuscorp do Palanca.', 'published', null, null, null, null, '[]'::jsonb, null, false),
  ('n3', 'Wiliete de Benguela garante histórico 2º lugar e vaga nas competições africanas', 'Competição', '2026-05-09T00:00:00.000Z', '2026-05-09', 'A formação de Benguela venceu o Interclube por 2-0 e garantiu uma participação histórica na Liga dos Campeões da CAF para a próxima época.', 'Benguela está em festa. O Wiliete de Benguela bateu o Interclube por duas bolas a zero no Estádio Nacional de Ombaka e carimbou a sua vaga oficial na Liga dos Campeões da CAF da próxima época. Com golos de Mano Mano e Karanga, a formação dirigida por Lito Vidigal coroou uma campanha fenomenal no Liga Unitel Girabola, consagrando-se como a grande surpresa do futebol nacional angolano.', 'published', null, null, null, null, '[]'::jsonb, null, false),
  ('n4', 'Dagó Tshibamba conquista Troféu de Melhor Marcador do Liga Unitel Girabola', 'Individual', '2026-05-10T00:00:00.000Z', '2026-05-10', 'O avançado congolês do 1.º de Agosto finalizou a temporada com 17 golos marcados, consagrando-se o principal goleador do futebol nacional angolano.', 'O troféu de artilheiro do futebol angolano tem novo dono. O avançado congolês Dagó Tshibamba fechou a época de ouro do 1.º de Agosto com 17 golos apontados na prova. Tshibamba demonstrou regularidade notável, sendo coroado oficialmente como o melhor marcador e grande estrela ofensiva do Liga Unitel Girabola.', 'published', null, null, null, null, '[]'::jsonb, null, false),
  ('n5', 'Requalificação do Estádio França Ndalu recebe luz verde da FAF', 'Infraestrutura', '2026-06-24T00:00:00.000Z', '2026-06-24', 'A comissão técnica vistoriou as obras e aprovou o relvado para as competições nacionais e internacionais da próxima época.', 'O Estádio França Ndalu, casa do 1.º de Agosto, recebeu luz verde da federação para acolher jogos de alto nível na próxima temporada. Após profundas obras de requalificação no relvado e nos balneários, a vistoria técnica da FAF confirmou que o recinto reúne todos os requisitos regulamentares, trazendo grande alento aos adeptos militares que poderão apoiar a equipa no seu reduto principal.', 'published', null, null, null, null, '[]'::jsonb, null, false),
  ('n6', 'FAF anuncia sorteio do calendário oficial para o Liga Unitel Girabola 2026/2027', 'Federação', '2026-06-20T00:00:00.000Z', '2026-06-20', 'O sorteio oficial definiu as 30 jornadas da nova época desportiva, sob o novo código de verificação unificado.', 'A Federação Angolana de Futebol (FAF) realizou o sorteio da nova edição do campeonato nacional no edifício-sede em Luanda. O sorteio estabeleceu um calendário emocionante a duas voltas para as 16 equipas concorrentes. Os jogos terão início a 12 de Setembro de 2026, com o Petro de Luanda a iniciar a defesa do título em casa contra o Desportivo da Lunda Sul.', 'published', null, null, null, null, '[]'::jsonb, null, false)
on conflict (id) do update set title = excluded.title, category = excluded.category, date = excluded.date, iso_date = excluded.iso_date, summary = excluded.summary, content = excluded.content, status = excluded.status, author = excluded.author, source_name = excluded.source_name, source_url = excluded.source_url, published_at = excluded.published_at, document_images = excluded.document_images, document_url = excluded.document_url, ai_assisted = excluded.ai_assisted;
