-- ═════════════════════════════════════════════════════════════════════
-- ESCALAÇÕES, EVENTOS E ESTATÍSTICAS DE JOGO PUBLICADAS
-- Gerado por scripts/generate-db-seed.ts — não editar à mão.
-- ═════════════════════════════════════════════════════════════════════

-- Tabelas necessárias (idempotentes)
create table if not exists public.ancaf_match_lineups (
    id           uuid primary key default gen_random_uuid(),
    match_id     text references public.ancaf_matches(id) on delete cascade,
    team_id      text references public.ancaf_teams(id) on delete cascade,
    side         text check (side in ('home', 'away')),
    players      jsonb not null default '[]'::jsonb,
    coach        text,
    confirmed_by text default 'admin',
    confirmed_at timestamptz not null default timezone('utc', now()),
    created_at   timestamptz not null default timezone('utc', now()),
    updated_at   timestamptz not null default timezone('utc', now()),
    unique (match_id, team_id)
);
create index if not exists ancaf_lineups_match_idx on public.ancaf_match_lineups(match_id);
alter table public.ancaf_match_lineups enable row level security;
drop policy if exists "ancaf public read lineups" on public.ancaf_match_lineups;
create policy "ancaf public read lineups" on public.ancaf_match_lineups for select using (true);

create table if not exists public.ancaf_match_events (
    id           uuid primary key default gen_random_uuid(),
    match_id     text references public.ancaf_matches(id) on delete cascade,
    minute       integer not null,
    type         text not null,
    team         text not null,
    player       text not null,
    player_id    text,
    assist       text,
    player_out   text,
    detail       text,
    sort_order   integer not null default 0,
    created_at   timestamptz not null default timezone('utc', now())
);
create index if not exists ancaf_events_match_idx on public.ancaf_match_events(match_id);
alter table public.ancaf_match_events enable row level security;
drop policy if exists "ancaf public read events" on public.ancaf_match_events;
create policy "ancaf public read events" on public.ancaf_match_events for select using (true);

create table if not exists public.ancaf_match_stats (
    id         uuid primary key default gen_random_uuid(),
    match_id   text references public.ancaf_matches(id) on delete cascade,
    side       text check (side in ('home', 'away')),
    stat_key   text not null,
    value      numeric not null,
    official   boolean default false,
    updated_at timestamptz not null default timezone('utc', now()),
    unique (match_id, side, stat_key)
);
create index if not exists ancaf_stats_match_idx on public.ancaf_match_stats(match_id);
alter table public.ancaf_match_stats enable row level security;
drop policy if exists "ancaf public read stats" on public.ancaf_match_stats;
create policy "ancaf public read stats" on public.ancaf_match_stats for select using (true);

insert into public.ancaf_match_lineups (match_id, team_id, side, players, coach, confirmed_by) values
  ('m27-1-4', 'lundasul', 'home', '[{"playerId":"cacusso","name":"Kacusso","number":12,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"fred","name":"Singongo","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"dieu","name":"David","number":25,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"kibuata","name":"Kibuata","number":28,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"platini","name":"Paulino","number":6,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"vado-lunda-sul","name":"Vado","number":8,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"maranata","name":"Sicuba Vunge","number":10,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"magrinho","name":"Magrinho","number":11,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"manucho-lunda-sul","name":"Cachindele","number":19,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"mussa-lunda-sul","name":"Mussá","number":20,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"joca-lunda-sul","name":"Joca","number":27,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"nono","name":"Nonó","number":2,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"yuri","name":"Yuri","number":4,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"neymar-lunda-sul","name":"Neymar","number":7,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"ximba","name":"Ximba","number":16,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"jepson","name":"Ngulu","number":17,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"mongadie","name":"Monga Dié","number":23,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"sozito","name":"Keta","number":26,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"zonzo","name":"Caluvili","number":33,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"nicon","name":"Nicon","number":34,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fuca","name":"Zau","number":35,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"angola-gr","name":"Angola","number":41,"position":"GK","isStarter":false,"isCaptain":false}]'::jsonb, 'Pedro Barros', 'seed'),
  ('m27-1-4', 'petro', 'away', '[{"playerId":"neblu","name":"Neblú","number":22,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"ruben-aderito","name":"Rúben Adérito","number":4,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"leo-bolgado","name":"Léo Bolgado","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"berna","name":"Berna","number":13,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"eddie-afonso","name":"Eddie Afonso","number":25,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"mario-balburdia","name":"Mário Balbúrdia","number":6,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"jonathan-toro","name":"Jonathan Toro","number":8,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"pedro-aparicio","name":"Pedro Aparício","number":10,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"deybi-flores","name":"Deybi Flores","number":12,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"ivan-cavaleiro","name":"Ivan Cavaleiro","number":7,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"tiago-azulao","name":"Tiago Azulão","number":26,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"hugo-marques","name":"Hugo Marques","number":1,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"nurio-fortuna","name":"Núrio Fortuna","number":2,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"helder-costa","name":"Hélder Costa","number":11,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"vidinho","name":"Vidinho","number":18,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"jorge-pereira","name":"Jorge Pereira","number":20,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"tiago-reis","name":"Tiago Reis","number":23,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"antonio-hossi","name":"António Hossi","number":27,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"depu","name":"Depú","number":29,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"ilidio-panda","name":"Ilídio Panda","number":33,"position":"FWD","isStarter":false,"isCaptain":false}]'::jsonb, 'João Pedro Sousa', 'seed'),
  ('m27-1-2', 'bravos', 'home', '[{"playerId":"nathan-bravos","name":"Nathan","number":22,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"manico-bravos","name":"Manico","number":26,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"denilson-bravos","name":"Denilson","number":2,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"caprego-bravos","name":"Caprego","number":24,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"dabanda-bravos","name":"Dabanda","number":27,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"abrao-bravos","name":"Abrão","number":6,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"cueta-bravos","name":"Cueta","number":7,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"ju-cabral-bravos","name":"Ju Cabral","number":8,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"jorginho-bravos","name":"Jorginho","number":19,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"lito-bravos","name":"Lito","number":23,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"bani-bravos","name":"Bani","number":20,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"agnaldo-bravos","name":"Agnaldo","number":3,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"higino-bravos","name":"Higino Kaptingo Epalanga","number":10,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"tiago-bravos","name":"Fota","number":15,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"eduwine-bravos","name":"Eduwine","number":17,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"gladilson-bravos","name":"Gladilson","number":28,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"tony-bravos","name":"Tony","number":25,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"saidi-bravos","name":"Lionardo","number":12,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"bruno-bravos","name":"Bruno","number":4,"position":"DEF","isStarter":false,"isCaptain":false}]'::jsonb, 'Sandro Mendes', 'seed'),
  ('m27-1-2', 'sagrada', 'away', '[{"playerId":"leonardo-sagrada","name":"Leonardo","number":13,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"miguel-sagrada","name":"Miguel","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"tobias-sagrada","name":"Tobias","number":14,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"gogoro-sagrada","name":"Muanha","number":17,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"luis-tati-sagrada","name":"Tati","number":20,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"cahilo-sagrada","name":"Cahilo","number":32,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"afonso-sagrada","name":"Afonso","number":24,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"lepua-sagrada","name":"Miranda","number":10,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"pimpao-sagrada","name":"Pimpão","number":16,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"dabanda-sagrada","name":"Sebastiao","number":7,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"jorge-sagrada","name":"Francisco Lucussa","number":9,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"nsesani-sagrada","name":"Simão","number":12,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"silvano-sagrada","name":"Silvano","number":18,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"barreira-sagrada","name":"Barreira","number":28,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"sapalo-sagrada","name":"Maurício André","number":31,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"melono-sagrada","name":"Dala","number":11,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"guilherme-sagrada","name":"Cabuço","number":8,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"evaristo-sagrada","name":"Evaristo","number":4,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"manuel-sagrada","name":"Manuel","number":3,"position":"DEF","isStarter":false,"isCaptain":false}]'::jsonb, 'Francisco Moniz', 'seed'),
  ('m27-1-3', 'dago', 'home', '[{"playerId":"nuno-dago","name":"Nuno","number":1,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"bonifacio-dago","name":"Bonifácio","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"simao-dianzenza","name":"Simao Dianzenza","number":3,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"macaia-dago","name":"Macaia","number":16,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"milton-dago","name":"Milton","number":2,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"calebi-dago","name":"Calebi","number":10,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"venancio-dago","name":"Venâncio","number":15,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"mabilson-dago","name":"Mabilson","number":7,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fernando-dago","name":"Fernando","number":11,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"rupson-dago","name":"Rupson","number":9,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"dago-tshibamba","name":"Dagó Tshibamba","number":17,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"anselmo-dago","name":"Anselmo","number":22,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"bencao-dago","name":"Benção","number":36,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"bulaya-dago","name":"Bulaya","number":28,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"castro-dago","name":"Castro","number":27,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"tombe-dago","name":"Tombé","number":20,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"cliver-dago","name":"Clíver","number":18,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"obed-dago","name":"Obed","number":14,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"axel-dago","name":"Axel","number":8,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"bruno-dago","name":"Bruno","number":6,"position":"FWD","isStarter":false,"isCaptain":false}]'::jsonb, 'Filipe Nzanza', 'seed'),
  ('m27-1-3', 'desphuila', 'away', '[{"playerId":"ndulo-huila","name":"Ndulo","number":1,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"lucas-elias-huila","name":"Ludy","number":13,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"dos-santos-huila","name":"Dos Santos","number":4,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"katendi-huila","name":"Katendi","number":2,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"jeremias-huila","name":"Jeremias","number":26,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"elias-huila","name":"Elias","number":15,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"angelo-cangu-huila","name":"Angelo Cangu (Tchutchu)","number":21,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"tchicundico-huila","name":"Tchicundico Cassoma Tchitunda (Constantino)","number":32,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"milton-suca-huila","name":"Milton","number":18,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"milagre-simba-huila","name":"Milagre Carlos Simba","number":25,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"mendes-huila","name":"Mendes","number":10,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"passy-huila","name":"Passy","number":12,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"joao-milagre-huila","name":"Jo","number":6,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"leonardo-isola-huila","name":"Cabibi","number":7,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"mauricio-pedro-huila","name":"Mauricio Pedro (Jeizi)","number":8,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"toyzinho-huila","name":"Toyzinho","number":20,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"antonio-huila","name":"António","number":27,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"pequenino-castro-huila","name":"Pequenino Castro (Cagodo)","number":29,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"joao-samazanga-huila","name":"João Baptista Ferraz Samazanga Juny (Jony)","number":34,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"geovany-huila","name":"Geovany","number":35,"position":"FWD","isStarter":false,"isCaptain":false}]'::jsonb, 'Paulo Torres', 'seed'),
  ('m27-1-7', 'cabinda', 'home', '[{"playerId":"francisco-cabinda","name":"Francisco","number":12,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"rodrigo-cabinda","name":"Rodrigo","number":2,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"frederico-cabinda","name":"Frederico Zau","number":20,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"marcos-cabinda","name":"Marcos","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"antonio-cabinda","name":"António","number":16,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"julio-cabinda","name":"Júlio Mavungo André","number":17,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"cristiano-cabinda","name":"Cristiano Malonda","number":8,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fernando-cabinda","name":"Fernando","number":21,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"gedeon-cabinda","name":"Gedeon","number":3,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"jose-cabinda","name":"José","number":18,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"ariclenis-cabinda","name":"Ariclenis Afonso Araújo Lede","number":29,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"arsenio-cabinda","name":"Arsénio","number":31,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"luis-cabinda","name":"Luís","number":27,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"jaime-cabinda","name":"Jaime","number":26,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"bras-cabinda","name":"José Brás","number":23,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"cornelio-cabinda","name":"Cornélio","number":15,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"costa-cabinda","name":"Costa","number":7,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"mario-cabinda","name":"Mário","number":6,"position":"DEF","isStarter":false,"isCaptain":false}]'::jsonb, 'Luciano Capoco', 'seed'),
  ('m27-1-7', 'libolo', 'away', '[{"playerId":"beny-libolo","name":"Beny","number":12,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"marcos-libolo","name":"Marcos","number":3,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"toti-libolo","name":"Toti","number":4,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"maninho-libolo","name":"Maninho","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"tchube-libolo","name":"Tchube","number":8,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"chimito-libolo","name":"Chimito","number":6,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"andeloy-libolo","name":"Andeloy","number":10,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"nelo-libolo","name":"Nelo","number":14,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"pedro-libolo","name":"Pedro","number":17,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"tubarao-libolo","name":"Tubarão","number":30,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"cuxixima-libolo","name":"Cuxixima","number":27,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"mario-libolo","name":"Mário","number":20,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"jamanta-libolo","name":"Jamanta","number":19,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"jorgito-libolo","name":"Jorgito","number":15,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"zidane-libolo","name":"Zidane","number":22,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"catraio-libolo","name":"Catraio","number":24,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"miro-libolo","name":"Miro","number":25,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"lara-libolo","name":"Lara","number":28,"position":"FWD","isStarter":false,"isCaptain":false}]'::jsonb, 'Osvaldo Roque', 'seed'),
  ('m27-1-6', 'primeiromaio', 'home', '[{"playerId":"fifa-1k1sg53","name":"António Pascoal","number":1,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jyn4k6","name":"Márcio Luvambo","number":7,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1k1hkv2","name":"Moises Domingos","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1k0c7s4","name":"Jose Tchivinga","number":15,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jz4j23","name":"Paulo Mutossi","number":24,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jxhxl1","name":"Eliseu Varela","number":6,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1mqvbd5","name":"Odenir Jorge","number":14,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1k2pey7","name":"Muila Congolo","number":16,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1kztk20","name":"Luis Escovalo","number":19,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1nb4bp9","name":"Simão Gonga","number":22,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jsrcp9","name":"Deco","number":9,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"fifa-1nb4dq1","name":"Joaquim Tchingombe","number":56,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"fifa-1malez5","name":"Vicente Domingos","number":34,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fifa-1nb49x0","name":"Francisco Tchitane","number":33,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"fifa-1k1m4e0","name":"Malebani Rabby","number":31,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"fifa-1nd4nn2","name":"Kijungu Francisco","number":25,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fifa-1ljh1x4","name":"Fernando Duarte","number":20,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"fifa-1jzjeu2","name":"Gelson Teles","number":18,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fifa-1k176e0","name":"Rodrigues Muehombo","number":8,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fifa-1m9iby1","name":"Miguel Dey","number":2,"position":"DEF","isStarter":false,"isCaptain":false}]'::jsonb, 'Águas da Silva', 'seed'),
  ('m27-1-6', 'kabuscorp', 'away', '[{"playerId":"fifa-1jrtva7","name":"Augusto Mualucano","number":22,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"fifa-1mppsb5","name":"Henock Mangindula","number":16,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1k4a836","name":"Zamorano Lopes","number":2,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jyp8v8","name":"Eliseu","number":3,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1lgpgy7","name":"Adair Domingos","number":4,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1snb179","name":"Saombe Jorge","number":5,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1n3uhm6","name":"Bayala Nsimba","number":7,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1k2pk58","name":"José Vunge","number":10,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jm7zr2","name":"Daniel Kilola","number":15,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jrku39","name":"Mankoka Afonso","number":18,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"fifa-1js6m05","name":"Alberto Xavier","number":29,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"fifa-1lgpb81","name":"Teodoro Correia","number":11,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"fifa-1jriue5","name":"João de Nascimento","number":12,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"fifa-1k1sen7","name":"Artur Malungo","number":14,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"fifa-1jxicb5","name":"Mona Maleco","number":17,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"fifa-1jm8hd7","name":"Joaquim Paciencia","number":19,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"fifa-1pnr1r0","name":"Aluízio Cacharamba","number":27,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fifa-1qxnl72","name":"Mvemba Kuanzambi","number":28,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"fifa-1jrtxh4","name":"Diógenes João","number":32,"position":"MID","isStarter":false,"isCaptain":false}]'::jsonb, 'Léo Neiva', 'seed'),
  ('m27-2-8', 'lobito', 'home', '[{"playerId":"guilherme-lobito","name":"Muhango","number":12,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"joel-lobito","name":"Joel","number":2,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"rosario-lobito","name":"Rosário","number":4,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"jorge-28-lobito","name":"Jorge","number":28,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"leonel-lobito","name":"José Gonga","number":38,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"lourenco-lobito","name":"Lourenço","number":5,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"manuel-lobito","name":"Manuel","number":6,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"januario-lobito","name":"Januário","number":7,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"joaquim-lobito","name":"Joaquim","number":16,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"ezequiel-lobito","name":"Ezequiel","number":10,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"antonio-lobito","name":"António","number":19,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"marcos-lobito","name":"Marcos","number":40,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"carlos-lobito","name":"Carlos","number":35,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"aurelio-lobito","name":"Aurélio","number":33,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"valerio-lobito","name":"Valério","number":29,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"jorge-enio-lobito","name":"Jorge Enio","number":27,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"wilson-david-lobito","name":"Wilson","number":25,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"miguel-lobito","name":"Miguel","number":24,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"geraldo-lobito","name":"Geraldo Ndjela","number":21,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"nanga-lobito","name":"Nanga","number":3,"position":"DEF","isStarter":false,"isCaptain":false}]'::jsonb, 'Silvestre Pelé', 'seed'),
  ('m27-2-8', 'petro', 'away', '[{"playerId":"hugo-marques","name":"Hugo Marques","number":1,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"nurio-fortuna","name":"Núrio Fortuna","number":2,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"kinito","name":"Kinito","number":24,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"ruben-aderito","name":"Rúben Adérito","number":4,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"antonio-hossi","name":"António Hossi","number":27,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"mario-balburdia","name":"Mário Balbúrdia","number":6,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"deybi-flores","name":"Deybi Flores","number":12,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"jonathan-toro","name":"Jonathan Toro","number":8,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"helder-costa","name":"Hélder Costa","number":11,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"ilidio-panda","name":"Ilídio Panda","number":33,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"tiago-azulao","name":"Tiago Azulão","number":26,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"neblu","name":"Neblú","number":22,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"leo-bolgado","name":"Léo Bolgado","number":5,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"ivan-cavaleiro","name":"Ivan Cavaleiro","number":7,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"pedro-aparicio","name":"Pedro Aparício","number":10,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"vanilson","name":"Vanilson","number":17,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"jorge-pereira","name":"Jorge Pereira","number":20,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"tiago-reis","name":"Tiago Reis","number":23,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"eddie-afonso","name":"Eddie Afonso","number":25,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"depu","name":"Depú","number":29,"position":"FWD","isStarter":false,"isCaptain":false}]'::jsonb, 'João Pedro Sousa', 'seed'),
  ('m27-3-7', 'petro', 'home', '[{"playerId":"hugo-marques","name":"Hugo Marques","number":1,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"nurio-fortuna","name":"Núrio Fortuna","number":2,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"leo-bolgado","name":"Léo Bolgado","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"ruben-aderito","name":"Rúben Adérito","number":4,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"eddie-afonso","name":"Eddie Afonso","number":25,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"jonathan-toro","name":"Jonathan Toro","number":8,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"deybi-flores","name":"Deybi Flores","number":12,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"pedro-aparicio","name":"Pedro Aparício","number":10,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"ivan-cavaleiro","name":"Ivan Cavaleiro","number":7,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"helder-costa","name":"Hélder Costa","number":11,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"depu","name":"Depú","number":29,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"neblu","name":"Neblú","number":22,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"mario-balburdia","name":"Mário Balbúrdia","number":6,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"vanilson","name":"Vanilson","number":17,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"vidinho","name":"Vidinho","number":18,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"jorge-pereira","name":"Jorge Pereira","number":20,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"tiago-reis","name":"Tiago Reis","number":23,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"tiago-azulao","name":"Tiago Azulão","number":26,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"antonio-hossi","name":"António Hossi","number":27,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"ilidio-panda","name":"Ilídio Panda","number":33,"position":"FWD","isStarter":false,"isCaptain":false}]'::jsonb, 'João Pedro Sousa', 'seed'),
  ('m27-3-7', 'libolo', 'away', '[{"playerId":"beny-libolo","name":"Beny","number":12,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"maninho-libolo","name":"Maninho","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"marcos-libolo","name":"Marcos","number":3,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"toti-libolo","name":"Toti","number":4,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"nelo-libolo","name":"Nelo","number":14,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"chimito-libolo","name":"Chimito","number":6,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"tchube-libolo","name":"Tchube","number":8,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"andeloy-libolo","name":"Andeloy","number":10,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1qhqtd1","name":"Amado Haidara","number":18,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"tubarao-libolo","name":"Tubarão","number":30,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"cuxixima-libolo","name":"Cuxixima","number":27,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"mario-libolo","name":"Mário","number":20,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"miro-libolo","name":"Miro","number":25,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"jorgito-libolo","name":"Jorgito","number":15,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"pedro-libolo","name":"Pedro","number":17,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"jamanta-libolo","name":"Jamanta","number":19,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"zidane-libolo","name":"Zidane","number":22,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"catraio-libolo","name":"Catraio","number":24,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"miro-libolo","name":"Miro","number":25,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"lara-libolo","name":"Lara","number":28,"position":"FWD","isStarter":false,"isCaptain":false}]'::jsonb, 'Osvaldo Roque', 'seed'),
  ('m27-3-2', 'desphuila', 'home', '[{"playerId":"ndulo-huila","name":"Ndulo","number":1,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"lucas-elias-huila","name":"Ludy","number":13,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"dos-santos-huila","name":"Dos Santos","number":4,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"katendi-huila","name":"Katendi","number":2,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"jeremias-huila","name":"Jeremias","number":26,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"elias-huila","name":"Elias","number":15,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"pequenino-castro-huila","name":"Pequenino Castro (Cagodo)","number":29,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"tchicundico-huila","name":"Tchicundico Cassoma Tchitunda (Constantino)","number":32,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"milton-suca-huila","name":"Milton","number":18,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"milagre-simba-huila","name":"Milagre Carlos Simba","number":25,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"mendes-huila","name":"Mendes","number":10,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"passy-huila","name":"Passy","number":12,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"joao-milagre-huila","name":"Jo","number":6,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"leonardo-isola-huila","name":"Cabibi","number":7,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"angelo-cangu-huila","name":"Angelo Cangu (Tchutchu)","number":21,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"toyzinho-huila","name":"Toyzinho","number":20,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"antonio-huila","name":"António","number":27,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"joao-samazanga-huila","name":"João Baptista Ferraz Samazanga Juny (Jony)","number":34,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"fifa-1k176v9","name":"Florentino António","number":23,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"fifa-1pq2jf4","name":"Jose Camati","number":28,"position":"FWD","isStarter":false,"isCaptain":false}]'::jsonb, 'Paulo Torres', 'seed'),
  ('m27-3-2', 'wiliete', 'away', '[{"playerId":"fifa-1pkwt84","name":"Nayan Gomes","number":1,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jwu6z0","name":"Giovani Chipopolo","number":17,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1pnmj53","name":"Emanoel Júnior","number":27,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jsrpl0","name":"Arão Lologi","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jsjbh0","name":"Jorge Carneiro","number":7,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1m95s64","name":"Celio Zua","number":32,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jru7c5","name":"Armindo Canji","number":10,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1qvfjm7","name":"Bocar Sidibé","number":30,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jsj8t3","name":"Gibele","number":11,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jrxs05","name":"Camilo Ngongue","number":28,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"bello-lukman-wiliete","name":"Bello Lukman","number":18,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jm7y97","name":"Elber Delgado","number":31,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"fifa-1ljz6e0","name":"Silva António","number":3,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"fifa-1pu18x2","name":"Guilherme Neto","number":4,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"fifa-1k39nk6","name":"António Chitongo","number":8,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fifa-1uxfl56","name":"Cristovão Paciência","number":9,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"fifa-1ni87h8","name":"Filomeno Giloso","number":21,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"fifa-1jwu0l8","name":"Rodino Jose","number":25,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"fifa-1k36hf0","name":"Cesar Jeremias","number":34,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"fifa-1kzr1v5","name":"Zeferino Lussati","number":33,"position":"FWD","isStarter":false,"isCaptain":false}]'::jsonb, 'Beto Bianchi', 'seed'),
  ('m27-3-4', 'fcluanda', 'home', '[{"playerId":"fifa-1l7wk59","name":"Ludiakueno","number":12,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"fifa-1k2wth5","name":"Filipe Malanda","number":17,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1ljvmr0","name":"Jonilson Manuel","number":6,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1liwnq8","name":"Pedro","number":7,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1ljudk2","name":"Gelson André","number":8,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1l7lph0","name":"Denilson","number":10,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"fifa-1t6b2z2","name":"Ruben Luwawa","number":15,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1m8xdu3","name":"Arnaldo Dielo","number":16,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1l064e1","name":"Miguel Matos","number":23,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1qw3z14","name":"Celio Nimi","number":26,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1qw9vb1","name":"Jaime","number":30,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1maldz0","name":"Hamilton","number":2,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fifa-1qhqn96","name":"Joel Diaku","number":4,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"fifa-1mtndt1","name":"Euclides dos Santos","number":5,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fifa-1l11132","name":"Francisco","number":9,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"fifa-1mall47","name":"Domingos","number":14,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fifa-1l7w9k9","name":"Deo","number":22,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"fifa-1l08hy2","name":"Domingos","number":25,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fifa-1v0ca42","name":"Batista Kachama","number":27,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fifa-1maldr2","name":"Pedro","number":28,"position":"DEF","isStarter":false,"isCaptain":false}]'::jsonb, null, 'seed'),
  ('m27-3-4', 'cabinda', 'away', '[{"playerId":"cabinda-player-1","name":"João Eduardo","number":1,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"rodrigo-cabinda","name":"Rodrigo","number":2,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"gedeon-cabinda","name":"Gedeon","number":3,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"fifa-1qtzy92","name":"Francisco Luemba","number":4,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"cristiano-cabinda","name":"Cristiano Malonda","number":8,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"luyeye-cabinda","name":"Luyeye Tomás","number":13,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"frederico-cabinda","name":"Frederico Zau","number":20,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1ljjyh4","name":"Mário da Silva","number":24,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"joao-cambo-cabinda","name":"João Cambo","number":25,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"ariclenis-cabinda","name":"Ariclenis Afonso Araújo Lede","number":29,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"pedro-da-silva-cabinda","name":"Pedro da Silva","number":30,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"marcos-cabinda","name":"Marcos","number":5,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"mario-cabinda","name":"Mário","number":6,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"francisco-cabinda","name":"Francisco","number":12,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"simao-gomes-cabinda","name":"Simão Gomes","number":14,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"cornelio-cabinda","name":"Cornélio","number":15,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"julio-cabinda","name":"Júlio Mavungo André","number":17,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"domingos-paixao-cabinda","name":"Domingos Paixão Paulino Lourenço","number":19,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fernando-cabinda","name":"Fernando","number":21,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":null,"name":"Crichano Diacango","number":28,"position":"FWD","isStarter":false,"isCaptain":false}]'::jsonb, null, 'seed'),
  ('m27-4-5', 'cabinda', 'home', '[{"playerId":"cabinda-player-1","name":"João Eduardo","number":1,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"rodrigo-cabinda","name":"Rodrigo","number":2,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1qtzy92","name":"Francisco Luemba","number":4,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"marcos-cabinda","name":"Marcos","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"luyeye-cabinda","name":"Luyeye Tomás","number":13,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"cornelio-cabinda","name":"Cornélio","number":15,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"julio-cabinda","name":"Júlio Mavungo André","number":17,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fernando-cabinda","name":"Fernando","number":21,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1ljjyh4","name":"Mário da Silva","number":24,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"ariclenis-cabinda","name":"Ariclenis Afonso Araújo Lede","number":29,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"pedro-da-silva-cabinda","name":"Pedro da Silva","number":30,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"francisco-cabinda","name":"Francisco","number":12,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"gedeon-cabinda","name":"Gedeon","number":3,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"mario-cabinda","name":"Mário","number":6,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"cristiano-cabinda","name":"Cristiano Malonda","number":8,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"simao-gomes-cabinda","name":"Simão Gomes","number":14,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"domingos-paixao-cabinda","name":"Domingos Paixão Paulino Lourenço","number":19,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"frederico-cabinda","name":"Frederico Zau","number":20,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"jaime-cabinda","name":"Jaime","number":26,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":null,"name":"Crichano Diacango","number":28,"position":"FWD","isStarter":false,"isCaptain":false}]'::jsonb, 'Luciano Capoco', 'seed'),
  ('m27-4-5', 'dago', 'away', '[{"playerId":"nuno-dago","name":"Nuno","number":1,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"bruno-dago","name":"Bruno","number":6,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"axel-dago","name":"Axel","number":8,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"rupson-dago","name":"Rupson","number":9,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"venancio-dago","name":"Venâncio","number":15,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1pxu511","name":"Afonso Paxe","number":19,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":null,"name":"Paulo de Sousa Lopes Da Costa","number":21,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1pxwmn6","name":"Erique de Jesus","number":24,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1v12ek6","name":"Luciano dos Santos","number":25,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"castro-dago","name":"Castro","number":27,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"bencao-dago","name":"Benção","number":36,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"milton-dago","name":"Milton","number":2,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"obed-dago","name":"Obed","number":14,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"macaia-dago","name":"Macaia","number":16,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"dago-tshibamba","name":"Dagó Tshibamba","number":17,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"cliver-dago","name":"Clíver","number":18,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"tombe-dago","name":"Tombé","number":20,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fifa-1pwaay2","name":"Enoque Kabesa","number":23,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"bulaya-dago","name":"Bulaya","number":28,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":null,"name":"Justo Pucusso","number":31,"position":"GK","isStarter":false,"isCaptain":false}]'::jsonb, 'Filipe Nanza', 'seed'),
  ('m27-4-7', 'interclube', 'home', '[{"playerId":"fifa-1jtvf71","name":"Ru","number":22,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jtv4k9","name":"Salomão","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jtv3g3","name":"Além","number":6,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"patrick-banza-interclube","name":"Patrick Banza","number":7,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"fifa-1kz4cq5","name":"Alcides","number":14,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jtuys4","name":"Jamanta","number":18,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jsrqx5","name":"Nandinho","number":25,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1lzlzp0","name":"Moisés","number":28,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1k0sa99","name":"Betinho","number":29,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"fifa-1k26vw6","name":"Caneta","number":32,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1m92d85","name":"Paulo Gaspar","number":33,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jz6pv1","name":"Panzo","number":12,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"fifa-1qfxvu3","name":"Gaby","number":8,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fifa-1uz41e0","name":"Walter","number":20,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"fifa-1m7hyz3","name":"Altura","number":23,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"fifa-1t9mip7","name":"Toy","number":26,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"fifa-1k1ket3","name":"Bey","number":27,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"fifa-1jzyk44","name":"Boiado","number":30,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"fifa-1ni2dp9","name":"Afonso","number":36,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"fifa-1jrkqx3","name":"Sandro","number":37,"position":"MID","isStarter":false,"isCaptain":false}]'::jsonb, 'Divaldo Alves', 'seed'),
  ('m27-4-7', 'lobito', 'away', '[{"playerId":"guilherme-lobito","name":"Muhango","number":12,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"januario-lobito","name":"Januário","number":7,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"rosario-lobito","name":"Rosário","number":4,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"lourenco-lobito","name":"Lourenço","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"quiteque-lobito","name":"Quiteque","number":8,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"ezequiel-lobito","name":"Ezequiel","number":10,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"fifa-1jrj1l5","name":"Calela","number":13,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"pinto-lobito","name":"Pinto","number":14,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"fifa-1m79nl1","name":"Leonel","number":22,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"jorge-28-lobito","name":"Jorge","number":28,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"valerio-lobito","name":"Valério","number":29,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"marcos-lobito","name":"Marcos","number":40,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"kaporal","name":"Florentino","number":11,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"fifa-1l13q80","name":"Serafim","number":15,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"joaquim-lobito","name":"Joaquim","number":16,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"sabones-lobito","name":"Sabones","number":17,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"antonio-lobito","name":"António","number":19,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"miguel-lobito","name":"Miguel","number":24,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"wilson-david-lobito","name":"Wilson","number":25,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"fifa-1nyjxj8","name":"Fernando","number":36,"position":"DEF","isStarter":false,"isCaptain":false}]'::jsonb, 'Silvestre Pelé', 'seed'),
  ('m27-4-2', 'lundasul', 'home', '[{"playerId":"cacusso","name":"Kacusso","number":12,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"fifa-1k2wai2","name":"Agostinho","number":30,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fred","name":"Singongo","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"platini","name":"Paulino","number":6,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"vado-lunda-sul","name":"Vado","number":8,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"magrinho","name":"Magrinho","number":11,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"manucho-lunda-sul","name":"Cachindele","number":19,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"mussa-lunda-sul","name":"Mussá","number":20,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"dieu","name":"David","number":25,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"sozito","name":"Keta","number":26,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"joca-lunda-sul","name":"Joca","number":27,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":null,"name":"Ervinecio Daniel","number":1,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"fifa-1k1k2v2","name":"Nguala","number":3,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"maranata","name":"Sicuba Vunge","number":10,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"nacavuza-lunda-sul","name":"Bernardo Raimundo Nacavuza","number":14,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"ximba","name":"Ximba","number":16,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"jepson","name":"Ngulu","number":17,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"kibuata","name":"Kibuata","number":28,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"zonzo","name":"Caluvili","number":33,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"fuca","name":"Zau","number":35,"position":"FWD","isStarter":false,"isCaptain":false}]'::jsonb, 'Cleverson Silva', 'seed'),
  ('m27-4-2', 'sagrada', 'away', '[{"playerId":"nsesani-sagrada","name":"Simão","number":12,"position":"GK","isStarter":true,"isCaptain":false},{"playerId":"luis-tati-sagrada","name":"Tati","number":20,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"fifa-1v1a1u9","name":"Alexandre Fernando","number":2,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"manuel-sagrada","name":"Manuel","number":3,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"miguel-sagrada","name":"Miguel","number":5,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"jorge-sagrada","name":"Francisco Lucussa","number":9,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"lepua-sagrada","name":"Miranda","number":10,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"melono-sagrada","name":"Dala","number":11,"position":"FWD","isStarter":true,"isCaptain":false},{"playerId":"fifa-1v0z7l2","name":"Neves","number":21,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"afonso-sagrada","name":"Afonso","number":24,"position":"MID","isStarter":true,"isCaptain":false},{"playerId":"barreira-sagrada","name":"Barreira","number":28,"position":"DEF","isStarter":true,"isCaptain":false},{"playerId":"dabanda-sagrada","name":"Sebastiao","number":7,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"guilherme-sagrada","name":"Cabuço","number":8,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":"leonardo-sagrada","name":"Leonardo","number":13,"position":"GK","isStarter":false,"isCaptain":false},{"playerId":"tobias-sagrada","name":"Tobias","number":14,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"pimpao-sagrada","name":"Pimpão","number":16,"position":"FWD","isStarter":false,"isCaptain":false},{"playerId":"gogoro-sagrada","name":"Muanha","number":17,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":null,"name":"Paulo Catumbila","number":23,"position":"MID","isStarter":false,"isCaptain":false},{"playerId":null,"name":"Manuel Cunha","number":25,"position":"DEF","isStarter":false,"isCaptain":false},{"playerId":"sapalo-sagrada","name":"Maurício André","number":31,"position":"MID","isStarter":false,"isCaptain":false}]'::jsonb, 'Clemente Martins Mendonça', 'seed')
on conflict (match_id,team_id) do update set side = excluded.side, players = excluded.players, coach = excluded.coach, confirmed_by = excluded.confirmed_by;

delete from public.ancaf_match_events where match_id in ('m27-1-4', 'm27-1-2', 'm27-1-3', 'm27-1-7', 'm27-1-1', 'm27-1-6', 'm27-1-8', 'm27-1-5', 'm27-2-3', 'm27-2-7', 'm27-2-1', 'm27-2-5', 'm27-2-4', 'm27-2-2', 'm27-2-8', 'm27-2-6', 'm27-3-7', 'm27-3-2', 'm27-3-6', 'm27-3-1', 'm27-3-4', 'm27-3-8', 'm27-3-5', 'm27-4-5', 'm27-4-7', 'm27-4-2', 'm27-4-8');
insert into public.ancaf_match_events (match_id, minute, type, team_side, player, player_id, assist, player_out, detail, sort) values
  ('m27-1-4', 28, 'yellow', 'home', 'Sicuba Vunge', 'maranata', null, null, 'Rasteirou o adversário', 0),
  ('m27-1-4', 37, 'yellow', 'home', 'Paulino', 'platini', null, null, 'Rasteirou o adversário', 1),
  ('m27-1-4', 45, 'sub', 'away', 'Ilídio Panda', 'ilidio-panda', null, 'Ivan Cavaleiro', null, 2),
  ('m27-1-4', 45, 'sub', 'home', 'Neymar', 'neymar-lunda-sul', null, 'Sicuba Vunge', null, 3),
  ('m27-1-4', 53, 'yellow', 'away', 'Deybi Flores', 'deybi-flores', null, null, 'Rasteirou o adversário', 4),
  ('m27-1-4', 60, 'sub', 'away', 'António Hossi', 'antonio-hossi', null, 'Eddie Afonso', null, 5),
  ('m27-1-4', 60, 'sub', 'away', 'Hélder Costa', 'helder-costa', null, 'Pedro Aparício', null, 6),
  ('m27-1-4', 63, 'yellow', 'away', 'António Hossi', 'antonio-hossi', null, null, 'Protestou a decisão do árbitro', 7),
  ('m27-1-4', 65, 'sub', 'home', 'Nicon', 'nicon', null, 'Joca', null, 8),
  ('m27-1-4', 65, 'sub', 'home', 'Ngulu', 'jepson', null, 'Mussá', null, 9),
  ('m27-1-4', 73, 'sub', 'away', 'Depú', 'depu', null, 'Tiago Azulão', null, 10),
  ('m27-1-4', 73, 'sub', 'away', 'Tiago Reis', 'tiago-reis', null, 'Jonathan Toro', null, 11),
  ('m27-1-4', 73, 'sub', 'home', 'Caluvili', 'zonzo', null, 'Magrinho', null, 12),
  ('m27-1-4', 76, 'yellow', 'away', 'Berna', 'berna', null, null, 'Agarrou o adversário', 13),
  ('m27-1-4', 86, 'yellow', 'home', 'Ximba', 'ximba', null, null, 'Protestar a decisão do árbitro', 14),
  ('m27-1-4', 95, 'yellow', 'home', 'Kibuata', 'kibuata', null, null, '90''+5 - Agarrou o adversário', 15),
  ('m27-1-2', 6, 'yellow', 'away', 'Cahilo', 'cahilo-sagrada', null, null, 'Rasteirar o adversário', 0),
  ('m27-1-2', 23, 'goal', 'home', 'Ju Cabral', 'ju-cabral-bravos', null, null, '1-0', 1),
  ('m27-1-2', 33, 'goal', 'home', 'Lito', 'lito-bravos', null, null, '2-0', 2),
  ('m27-1-2', 45, 'sub', 'home', 'Higino Kaptingo Epalanga', 'higino-bravos', null, 'Cueta', null, 3),
  ('m27-1-2', 45, 'sub', 'home', 'Tony', 'tony-bravos', null, 'Bani', null, 4),
  ('m27-1-2', 45, 'sub', 'away', 'Dala', 'melono-sagrada', null, 'Sebastiao', null, 5),
  ('m27-1-2', 45, 'sub', 'away', 'Cabuço', 'guilherme-sagrada', null, 'Cahilo', null, 6),
  ('m27-1-2', 48, 'yellow', 'away', 'Miguel', 'miguel-sagrada', null, null, 'Não respeitar a decisão do árbitro', 7),
  ('m27-1-2', 49, 'yellow', 'home', 'Ju Cabral', 'ju-cabral-bravos', null, null, 'Tentar enganar o árbitro na área de penálte', 8),
  ('m27-1-2', 51, 'yellow', 'away', 'Pimpão', 'pimpao-sagrada', null, null, 'Jogar à bola depois do árbitro apitar', 9),
  ('m27-1-2', 60, 'sub', 'home', 'Gladilson', 'gladilson-bravos', null, 'Lito', null, 10),
  ('m27-1-2', 69, 'sub', 'away', 'Silvano', 'silvano-sagrada', null, 'Pimpão', null, 11),
  ('m27-1-2', 75, 'sub', 'home', 'Fota', 'tiago-bravos', null, 'Ju Cabral', null, 12),
  ('m27-1-2', 78, 'goal', 'home', 'Gladilson', 'gladilson-bravos', null, null, '3-0', 13),
  ('m27-1-2', 86, 'yellow', 'home', 'Dabanda', 'dabanda-bravos', null, null, 'Rasteirar o adversário', 14),
  ('m27-1-2', 88, 'sub', 'home', 'Eduwine', 'eduwine-bravos', null, 'Jorginho', null, 15),
  ('m27-1-3', 6, 'sub', 'away', 'Jo', 'joao-milagre-huila', null, 'Mendes', null, 0),
  ('m27-1-3', 30, 'yellow', 'home', 'Dagó Tshibamba', 'dago-tshibamba', null, null, null, 1),
  ('m27-1-3', 40, 'yellow', 'home', 'Simao Dianzenza', 'simao-dianzenza', null, null, null, 2),
  ('m27-1-3', 52, 'yellow', 'away', 'Ludy', 'lucas-elias-huila', null, null, null, 3),
  ('m27-1-3', 55, 'sub', 'away', 'Mauricio Pedro (Jeizi)', 'mauricio-pedro-huila', null, 'Angelo Cangu (Tchutchu)', null, 4),
  ('m27-1-3', 55, 'sub', 'away', 'António', 'antonio-huila', null, 'Milton', null, 5),
  ('m27-1-3', 60, 'sub', 'home', 'Obed', 'obed-dago', null, 'Rupson', null, 6),
  ('m27-1-3', 60, 'sub', 'home', 'Bulaya', 'bulaya-dago', null, 'Fernando', null, 7),
  ('m27-1-3', 60, 'sub', 'home', 'Axel', 'axel-dago', null, 'Simao Dianzenza', null, 8),
  ('m27-1-3', 68, 'sub', 'away', 'Cabibi', 'leonardo-isola-huila', null, 'Milagre Carlos Simba', null, 9),
  ('m27-1-3', 78, 'sub', 'away', 'Pequenino Castro (Cagodo)', 'pequenino-castro-huila', null, 'Tchicundico Cassoma Tchitunda (Constantino)', null, 10),
  ('m27-1-3', 87, 'yellow', 'home', 'Venâncio', 'venancio-dago', null, null, null, 11),
  ('m27-1-3', 90, 'sub', 'home', 'Tombé', 'tombe-dago', null, 'Mabilson', null, 12),
  ('m27-1-3', 92, 'goal', 'home', 'Dagó Tshibamba', 'dago-tshibamba', null, null, '90''+2 (1-0)', 13),
  ('m27-1-7', 14, 'yellow', 'home', 'Marcos', 'marcos-cabinda', null, null, null, 0),
  ('m27-1-7', 27, 'sub', 'home', 'José Brás', 'bras-cabinda', null, 'José', null, 1),
  ('m27-1-7', 34, 'goal', 'away', 'Cuxixima', 'cuxixima-libolo', null, null, '0-1', 2),
  ('m27-1-7', 55, 'yellow', 'home', 'António', 'antonio-cabinda', null, null, null, 3),
  ('m27-1-7', 56, 'sub', 'home', 'Cornélio', 'cornelio-cabinda', null, 'Gedeon', null, 4),
  ('m27-1-7', 66, 'sub', 'home', 'Costa', 'costa-cabinda', null, 'Júlio Mavungo André', null, 5),
  ('m27-1-7', 68, 'goal', 'away', 'Pedro', 'pedro-libolo', null, null, '0-2', 6),
  ('m27-1-7', 70, 'sub', 'away', 'Zidane', 'zidane-libolo', null, 'Pedro', null, 7),
  ('m27-1-7', 74, 'goal', 'away', 'Andeloy', 'andeloy-libolo', null, null, '0-3', 8),
  ('m27-1-7', 76, 'sub', 'away', 'Miro', 'miro-libolo', null, 'Chimito', null, 9),
  ('m27-1-7', 76, 'sub', 'away', 'Catraio', 'catraio-libolo', null, 'Maninho', null, 10),
  ('m27-1-7', 85, 'sub', 'away', 'Jamanta', 'jamanta-libolo', null, 'Andeloy', null, 11),
  ('m27-1-1', 5, 'sub', 'away', 'José Manuel Raul', null, null, 'Manuel Zange Miguel', null, 0),
  ('m27-1-1', 40, 'yellow', 'away', 'Lisneu Emanuel Neto Simao', 'lisneu-caala', null, null, 'Rasteirou o adversário', 1),
  ('m27-1-1', 63, 'sub', 'home', 'Estêvão Cahoko', null, null, 'Miguel Nzau Manuel Matos', null, 2),
  ('m27-1-1', 63, 'sub', 'home', 'Pedro Paulo', null, null, 'Jaime Caetano', null, 3),
  ('m27-1-1', 65, 'sub', 'away', 'Timóteo Sambissa', null, null, 'Domingos Lourenço Cuxixima', null, 4),
  ('m27-1-1', 65, 'sub', 'away', 'Benvindo Miguel André Afonso', null, null, 'Arilson de Ceita Pereira Jorge', null, 5),
  ('m27-1-1', 79, 'sub', 'away', 'Osvaldo José', null, null, 'Benedito Antunes', null, 6),
  ('m27-1-1', 79, 'sub', 'away', 'Gabriel Venâncio', null, null, 'Hermenegildo Sandumbo', null, 7),
  ('m27-1-1', 81, 'sub', 'home', 'Domingos André', null, null, 'Arnaldo Dielo', null, 8),
  ('m27-1-1', 81, 'sub', 'home', 'Batista João Kachama', null, null, 'Domingos Bangula', null, 9),
  ('m27-1-1', 87, 'sub', 'home', 'Francisco Chiquinho', null, null, 'Denilson Makokisa', null, 10),
  ('m27-1-6', 21, 'goal', 'home', 'Odenir Jorge', 'fifa-1mqvbd5', null, null, '1-0', 0),
  ('m27-1-6', 45, 'yellow', 'away', 'Daniel Kilola', 'fifa-1jm7zr2', null, null, null, 1),
  ('m27-1-6', 45, 'yellow', 'away', 'Saombe Jorge', 'fifa-1snb179', null, null, null, 2),
  ('m27-1-6', 45, 'yellow', 'away', 'Zamorano Lopes', 'fifa-1k4a836', null, null, null, 3),
  ('m27-1-6', 46, 'yellow', 'home', 'Deco', 'fifa-1jsrcp9', null, null, 'Falta táctica', 4),
  ('m27-1-6', 46, 'sub', 'away', 'Mona Maleco', 'fifa-1jxicb5', null, 'Eliseu', null, 5),
  ('m27-1-6', 59, 'sub', 'away', 'Joaquim Paciencia', 'fifa-1jm8hd7', null, 'Alberto Xavier', null, 6),
  ('m27-1-6', 59, 'sub', 'away', 'Diógenes João', 'fifa-1jrtxh4', null, 'Daniel Kilola', null, 7),
  ('m27-1-6', 65, 'goal', 'away', 'Mankoka Afonso', 'fifa-1jrku39', null, null, '1-1', 8),
  ('m27-1-6', 69, 'sub', 'home', 'Fernando Duarte', 'fifa-1ljh1x4', null, 'Luis Escovalo', null, 9),
  ('m27-1-6', 69, 'sub', 'home', 'Rodrigues Muehombo', 'fifa-1k176e0', null, 'Odenir Jorge', null, 10),
  ('m27-1-6', 69, 'sub', 'home', 'Vicente Domingos', 'fifa-1malez5', null, 'Muila Congolo', null, 11),
  ('m27-1-6', 70, 'yellow', 'home', 'Simão Gonga', 'fifa-1nb4bp9', null, null, null, 12),
  ('m27-1-6', 73, 'yellow', 'away', 'Diógenes João', 'fifa-1jrtxh4', null, null, null, 13),
  ('m27-1-6', 73, 'sub', 'away', 'Teodoro Correia', 'fifa-1lgpb81', null, 'Bayala Nsimba', null, 14),
  ('m27-1-6', 80, 'sub', 'away', 'Aluízio Cacharamba', 'fifa-1pnr1r0', null, 'José Vunge', null, 15),
  ('m27-1-6', 86, 'sub', 'home', 'Kijungu Francisco', 'fifa-1nd4nn2', null, 'Simão Gonga', null, 16),
  ('m27-1-6', 90, 'sub', 'home', 'Malebani Rabby', 'fifa-1k1m4e0', null, 'Fernando Duarte', null, 17),
  ('m27-1-8', 70, 'goal', 'away', 'Além', 'alem-interclube', null, null, '0-1', 0),
  ('m27-1-5', 11, 'goal', 'home', 'Kabelo Dlamini', 'kabelo-dlamini', null, null, '1-0', 0),
  ('m27-1-5', 16, 'yellow', 'away', 'Manuel Pereira Londaka', 'manuel-lobito', null, null, 'Comportamento antidesportivo', 1),
  ('m27-1-5', 47, 'goal', 'home', 'Valter Monteiro', 'valter-monteiro', null, null, '45''+2 (2-0)', 2),
  ('m27-2-3', 5, 'yellow', 'home', 'Pedro da Silva', 'pedro-da-silva-cabinda', null, null, null, 0),
  ('m27-2-3', 20, 'yellow', 'home', 'João Cambo', 'joao-cambo-cabinda', null, null, null, 1),
  ('m27-2-3', 24, 'goal', 'away', 'Milagre Carlos Simba', 'milagre-simba-huila', null, null, '0-1', 2),
  ('m27-2-3', 45, 'sub', 'away', 'João Milagre Chiva Simões', 'joao-milagre-huila', null, 'Lucas Elias Antonio Paulo', null, 3),
  ('m27-2-3', 45, 'sub', 'away', 'Angelo Cangu', 'angelo-cangu-huila', null, 'Tchicundico Cassoma Tchitunda', null, 4),
  ('m27-2-3', 45, 'sub', 'away', 'Leonardo Manuel Isola Ramos', 'leonardo-isola-huila', null, 'Milagre Carlos Simba', null, 5),
  ('m27-2-3', 45, 'sub', 'away', 'Pequenino Castro', 'pequenino-castro-huila', null, 'Mauricio Pedro', null, 6),
  ('m27-2-3', 47, 'yellow', 'away', 'Lucas Elias Antonio Paulo', 'lucas-elias-huila', null, null, null, 7),
  ('m27-2-3', 49, 'goal', 'home', 'Luyeye Tomás', 'luyeye-cabinda', null, null, 'Grande penalidade · 45''+4 (1-1)', 8),
  ('m27-2-3', 60, 'yellow', 'home', 'Luyeye Tomás', 'luyeye-cabinda', null, null, null, 9),
  ('m27-2-3', 62, 'yellow', 'away', 'João Milagre Chiva Simões', 'joao-milagre-huila', null, null, null, 10),
  ('m27-2-3', 67, 'yellow', 'home', 'Cipriano Cumba Rafael', 'cipriano-cumba-cabinda', null, null, null, 11),
  ('m27-2-3', 67, 'sub', 'home', 'Júlio Mavungo André', 'julio-cabinda', null, 'Domingos Paixão Paulino Lourenço', null, 12),
  ('m27-2-3', 67, 'sub', 'away', 'João Baptista Ferraz Samazanga Juny', 'joao-samazanga-huila', null, 'Milton Alberto de Oliveira Suca', null, 13),
  ('m27-2-3', 69, 'yellow', 'home', 'Luciano Capoco', 'luciano-capoco-cabinda', null, null, null, 14),
  ('m27-2-3', 71, 'yellow', 'home', 'Ariclenis Afonso Araújo Lede', 'ariclenis-cabinda', null, null, null, 15),
  ('m27-2-3', 74, 'sub', 'home', 'Simão Gomes', 'simao-gomes-cabinda', null, 'Ariclenis Afonso Araújo Lede', null, 16),
  ('m27-2-3', 75, 'yellow', 'away', 'Angelo Cangu', 'angelo-cangu-huila', null, null, null, 17),
  ('m27-2-3', 76, 'yellow', 'home', 'Simão Gomes', 'simao-gomes-cabinda', null, null, null, 18),
  ('m27-2-3', 79, 'yellow', 'home', 'Cristiano Malonda', 'cristiano-cabinda', null, null, null, 19),
  ('m27-2-3', 80, 'goal', 'away', 'Leonardo Manuel Isola Ramos', 'leonardo-isola-huila', null, null, '1-2', 20),
  ('m27-2-3', 82, 'sub', 'home', 'António Kapata', 'antonio-kapata-cabinda', null, 'Frederico Zau', null, 21),
  ('m27-2-7', 24, 'goal', 'away', 'Axel', 'axel-dago', null, null, '0-1', 0),
  ('m27-2-7', 43, 'yellow', 'away', 'Axel', 'axel-dago', null, null, 'Agarrou o adversário', 1),
  ('m27-2-7', 44, 'yellow', 'home', 'Paulo Mutossi', 'fifa-1jz4j23', null, null, null, 2),
  ('m27-2-7', 45, 'yellow', 'away', 'Milton', 'milton-dago', null, null, 'Rasteirou o adversário', 3),
  ('m27-2-7', 72, 'goal', 'home', 'Luís Profi', 'luis-profi-primeiromaio', null, null, '1-1', 4),
  ('m27-2-7', 75, 'goal', 'away', 'Dagó Tshibamba', 'dago-tshibamba', null, null, '1-2', 5),
  ('m27-2-7', 81, 'yellow', 'home', 'Moisés Domingos', 'fifa-1k1hkv2', null, null, 'Agarrar o adversário', 6),
  ('m27-2-1', 32, 'goal', 'home', 'Valegol', 'valegol-caala', null, null, 'Grande penalidade · 1-0', 0),
  ('m27-2-1', 34, 'goal', 'away', 'Bello Lukman', 'bello-lukman-wiliete', null, null, '1-1', 1),
  ('m27-2-1', 44, 'red', 'home', 'Valegol', 'valegol-caala', null, null, null, 2),
  ('m27-2-1', 49, 'goal', 'away', 'Ning', 'ning-wiliete', null, null, '1-2', 3),
  ('m27-2-5', 10, 'yellow', 'away', 'Gelson dos Santos André', 'fifa-1ljudk2', null, null, 'Rasteirou o adversário', 0),
  ('m27-2-5', 36, 'yellow', 'home', 'Paulo Gaspar', 'fifa-1m92d85', null, null, null, 1),
  ('m27-2-5', 45, 'sub', 'away', 'Francisco Chiquinho', null, null, 'Domingos Bangula', null, 2),
  ('m27-2-5', 45, 'sub', 'away', 'Pedro Paulo', null, null, 'Miguel Nzau Manuel Matos', null, 3),
  ('m27-2-5', 49, 'goal', 'home', 'Silvano da Cruz', 'silvano-da-cruz-interclube', null, null, '1-0', 4),
  ('m27-2-5', 52, 'goal', 'home', 'Alberto Alves', 'alberto-alves-interclube', null, null, '2-0', 5),
  ('m27-2-5', 58, 'sub', 'home', 'Afonso Baptista', null, null, 'Edivaldo Quinanga', null, 6),
  ('m27-2-5', 72, 'yellow', 'away', 'Sebastião Palavra Ngola', 'sebastiao-palavra', null, null, 'Protestar as decisões do árbitro', 7),
  ('m27-2-5', 72, 'yellow', 'away', 'Adriano Manuel Pedro', 'adriano-pedro', null, null, 'Protestar as decisões do árbitro', 8),
  ('m27-2-5', 79, 'sub', 'away', 'Ricardo Batista', 'ricardo-batista-fcluanda', null, 'Gelson dos Santos André', null, 9),
  ('m27-2-5', 79, 'sub', 'away', 'Domingos André', null, null, 'Denilson Makokisa', null, 10),
  ('m27-2-5', 80, 'sub', 'home', 'Alexandre Domingos Ngunza Caculo', null, null, 'Pedro Ganga', null, 11),
  ('m27-2-5', 82, 'yellow', 'away', 'Ricardo Batista', 'ricardo-batista-fcluanda', null, null, 'Impediu uma jogada prometedora de golo', 12),
  ('m27-2-5', 85, 'sub', 'away', 'Jonilson José Manuel', null, null, 'Arnaldo Dielo', null, 13),
  ('m27-2-5', 90, 'sub', 'home', 'Bartolomeu Taivando Anacleto Sachimala', null, null, 'Felisberto Tchacuiva', null, 14),
  ('m27-2-5', 91, 'goal', 'away', 'Ricardo Batista', 'ricardo-batista-fcluanda', null, null, '90''+1 · 2-1', 15),
  ('m27-2-4', 25, 'sub', 'away', 'Anderson de Jesus Luís Mputa', null, null, 'Samuel Chissapa Cachimbombo', null, 0),
  ('m27-2-4', 36, 'yellow', 'home', 'Alexandre Abel Fernando', 'fifa-1v1a1u9', null, null, 'Segurar a bola com as mãos, simulando falta', 1),
  ('m27-2-4', 45, 'goal', 'home', 'Mafuta', 'mafuta-sagrada', null, null, '1-0', 2),
  ('m27-2-4', 46, 'sub', 'home', 'Felisberto Dala Sebastião', null, null, 'Barreira Paulo', null, 3),
  ('m27-2-4', 46, 'sub', 'away', 'Justino Tchitepa César', null, null, 'Lucas Filemon Cassule', null, 4),
  ('m27-2-4', 49, 'goal', 'away', 'Anderson Mputa', 'anderson-mputa-saosalvador', null, null, '1-1', 5),
  ('m27-2-4', 60, 'sub', 'home', 'Guilherme Francisco Saiendo Cabuço', null, null, 'Afonso Marques', null, 6),
  ('m27-2-4', 64, 'goal', 'home', 'Augusto Fecayamale', null, null, null, 'A confirmar · 2-1', 7),
  ('m27-2-4', 71, 'yellow', 'away', 'Manuel de Matos', 'fifa-1jzirz7', null, null, 'Protestar constantemente as decisões do árbitro', 8),
  ('m27-2-4', 81, 'sub', 'away', 'Afonso Lukombo António', null, null, 'Caetano Gomes', null, 9),
  ('m27-2-4', 81, 'sub', 'away', 'João André Vemba', null, null, 'Fernando Lizandro Firmino Camuege', null, 10),
  ('m27-2-4', 89, 'sub', 'away', 'Wilson Gonçalves Tenete', null, null, 'Batomene de Sousa', null, 11),
  ('m27-2-4', 91, 'sub', 'home', 'Hahilo Sapalo Alberto', null, null, 'Jorge Txando Francisco Lucussa', null, 12),
  ('m27-2-4', 92, 'goal', 'home', 'M. Dala', 'm-dala-sagrada', null, null, '90''+2 · 3-1', 13),
  ('m27-2-2', 11, 'sub', 'away', 'Domingos Ximba', 'ximba', null, 'Felix Honjo', null, 0),
  ('m27-2-2', 21, 'yellow', 'away', 'Joaquim Teixeira', 'mussa-lunda-sul', null, null, null, 1),
  ('m27-2-2', 26, 'goal', 'home', 'Henock Mangindula', 'fifa-1mppsb5', null, null, '1-0', 2),
  ('m27-2-2', 45, 'sub', 'home', 'Mbali Mongbongo Sem', null, null, 'Joaquim Paciência', null, 3),
  ('m27-2-2', 45, 'sub', 'away', 'António Ngola Ngulu', null, null, 'Osvaldo Miguel', null, 4),
  ('m27-2-2', 46, 'yellow', 'home', 'Adair Garcia Domingos', 'fifa-1lgpgy7', null, null, null, 5),
  ('m27-2-2', 46, 'yellow', 'away', 'Frederico Singongo', 'fred', null, null, null, 6),
  ('m27-2-2', 57, 'goal', 'away', 'Dieu Maquissossila David', 'dieu', null, null, '1-1', 7),
  ('m27-2-2', 60, 'sub', 'home', 'Alberto Elizeu Xavier', null, null, 'Celestino Luís Maleco', null, 8),
  ('m27-2-2', 72, 'sub', 'home', 'Tresor Kuyu Nona', null, null, 'Bayala Nsimba', null, 9),
  ('m27-2-2', 74, 'yellow', 'away', 'Adalberto Wacamba', 'cacusso', null, null, null, 10),
  ('m27-2-2', 84, 'yellow', 'home', 'Mbali Mongbongo Sem', 'fifa-1v363a9', null, null, null, 11),
  ('m27-2-2', 86, 'sub', 'away', 'Mário Bernardo Keta', null, null, 'João Baptista Cassicote', null, 12),
  ('m27-2-2', 90, 'yellow', 'away', 'Dieu David', 'dieu', null, null, null, 13),
  ('m27-2-2', 90, 'sub', 'home', 'Artur Malungo', null, null, 'Zamorano Lopes', null, 14),
  ('m27-2-2', 90, 'sub', 'home', 'Aluízio Joel André Cacharamba', null, null, 'Mankoka Hegene Afonso', null, 15),
  ('m27-2-2', 90, 'sub', 'away', 'João Bivoba Zau', null, null, 'Joaquim Teixeira', null, 16),
  ('m27-2-8', 29, 'yellow', 'away', 'Kinito', 'kinito', null, null, 'Rasteirar o adversário', 0),
  ('m27-2-8', 47, 'goal', 'away', 'Tiago Azulão', 'tiago-azulao', null, null, '0-1', 1),
  ('m27-2-8', 59, 'sub', 'away', 'Depú', 'depu', null, 'Tiago Azulão', null, 2),
  ('m27-2-8', 59, 'sub', 'away', 'Ivan Cavaleiro', 'ivan-cavaleiro', null, 'Ilídio Panda', null, 3),
  ('m27-2-8', 70, 'sub', 'home', 'Valério', 'valerio-lobito', null, 'Joaquim', null, 4),
  ('m27-2-8', 74, 'sub', 'away', 'Jorge Pereira', 'jorge-pereira', null, 'Jonathan Toro', null, 5),
  ('m27-2-8', 77, 'yellow', 'home', 'Januário', 'januario-lobito', null, null, 'Agarrou o adversário', 6),
  ('m27-2-8', 80, 'sub', 'home', 'Miguel', 'miguel-lobito', null, 'Januário', null, 7),
  ('m27-2-8', 87, 'sub', 'away', 'Eddie Afonso', 'eddie-afonso', null, 'António Hossi', null, 8),
  ('m27-2-8', 87, 'sub', 'away', 'Vanilson', 'vanilson', null, 'Hélder Costa', null, 9),
  ('m27-2-8', 89, 'sub', 'home', 'Aurélio', 'aurelio-lobito', null, 'Ezequiel', null, 10),
  ('m27-2-8', 89, 'sub', 'home', 'Geraldo Ndjela', 'geraldo-lobito', null, 'António', null, 11),
  ('m27-2-8', 91, 'goal', 'away', 'Depú', 'depu', null, null, '90''+1 · 0-2', 12),
  ('m27-2-6', 85, 'goal', 'away', 'Higino Kaptingo Epalanga', 'higino-bravos', null, null, '0-1', 0),
  ('m27-3-7', 17, 'yellow', 'away', 'Marcos', 'marcos-libolo', null, null, null, 0),
  ('m27-3-7', 22, 'goal', 'home', 'Rúben Adérito', 'ruben-aderito', null, null, '1-0', 1),
  ('m27-3-7', 61, 'yellow', 'home', 'Núrio Fortuna', 'nurio-fortuna', null, null, null, 2),
  ('m27-3-7', 65, 'sub', 'home', 'Ilídio Panda', 'ilidio-panda', null, 'Ivan Cavaleiro', null, 3),
  ('m27-3-7', 65, 'sub', 'home', 'António Hossi', 'antonio-hossi', null, 'Núrio Fortuna', null, 4),
  ('m27-3-7', 65, 'sub', 'away', 'Pedro', 'pedro-libolo', null, 'Cuxixima', null, 5),
  ('m27-3-7', 73, 'sub', 'home', 'Mário Balbúrdia', 'mario-balburdia', null, 'Pedro Aparício', null, 6),
  ('m27-3-7', 76, 'sub', 'away', 'Zidane', 'zidane-libolo', null, 'Amado Haidara', null, 7),
  ('m27-3-7', 76, 'sub', 'away', 'Catraio', 'catraio-libolo', null, 'Tchube', null, 8),
  ('m27-3-7', 80, 'sub', 'home', 'Tiago Azulão', 'tiago-azulao', null, 'Depú', null, 9),
  ('m27-3-7', 80, 'sub', 'home', 'Vanilson', 'vanilson', null, 'Hélder Costa', null, 10),
  ('m27-3-7', 84, 'goal', 'home', 'Tiago Azulão', 'tiago-azulao', null, null, '2-0', 11),
  ('m27-3-7', 87, 'yellow', 'away', 'Andeloy', 'andeloy-libolo', null, null, null, 12),
  ('m27-3-7', 90, 'sub', 'away', 'Jorgito', 'jorgito-libolo', null, 'Aristóteles', null, 13),
  ('m27-3-7', 90, 'sub', 'away', 'Jamanta', 'jamanta-libolo', null, 'Maninho', null, 14),
  ('m27-3-7', 95, 'goal', 'home', 'Deybi Flores', 'deybi-flores', null, null, '90''+5 (3-0)', 15),
  ('m27-3-2', 42, 'yellow', 'home', 'Elias', 'elias-huila', null, null, null, 0),
  ('m27-3-2', 57, 'sub', 'home', 'Jo', 'joao-milagre-huila', null, 'Elias', null, 1),
  ('m27-3-2', 60, 'sub', 'away', 'Cristovão Paciência', 'fifa-1uxfl56', null, 'Bello Lukman', null, 2),
  ('m27-3-2', 60, 'sub', 'away', 'Zeferino Lussati', 'fifa-1kzr1v5', null, 'Camilo Ngongue', null, 3),
  ('m27-3-2', 68, 'sub', 'away', 'Rodino Jose', 'fifa-1jwu0l8', null, 'Celio Zua', null, 4),
  ('m27-3-2', 70, 'sub', 'home', 'Leonardo Ramos', null, null, 'Milagre Carlos Simba', null, 5),
  ('m27-3-2', 75, 'goal', 'away', 'Rodino Jose', 'fifa-1jwu0l8', null, null, '0-1', 6),
  ('m27-3-2', 77, 'sub', 'away', 'António Chitongo', 'fifa-1k39nk6', null, 'Bocar Sidibé', null, 7),
  ('m27-3-2', 77, 'sub', 'away', 'Cesar Jeremias', 'fifa-1k36hf0', null, 'Gibele', null, 8),
  ('m27-3-2', 80, 'sub', 'home', 'Angelo Cangu (Tchutchu)', 'angelo-cangu-huila', null, 'Pequenino Castro (Cagodo)', null, 9),
  ('m27-3-2', 80, 'sub', 'home', 'António', 'antonio-huila', null, 'Tchicundico Cassoma Tchitunda (Constantino)', null, 10),
  ('m27-3-2', 80, 'sub', 'home', 'Jose Camati', 'fifa-1pq2jf4', null, 'Mendes', null, 11),
  ('m27-3-2', 84, 'yellow', 'away', 'António Chitongo', 'fifa-1k39nk6', null, null, null, 12),
  ('m27-3-6', 34, 'yellow', 'home', 'Venâncio', 'venancio-dago', null, null, 'Rasteirar o adversário', 0),
  ('m27-3-6', 45, 'goal', 'away', 'Alexandre Fernando', 'alexandre-fernando-interclube', null, null, 'Grande penalidade · 45''+5 (0-1)', 1),
  ('m27-3-6', 56, 'yellow', 'away', 'Edivaldo Quinanga', 'fifa-1jtuys4', null, null, 'Rasteirar o adversário', 2),
  ('m27-3-6', 77, 'yellow', 'home', 'Felix Bulaya', 'bulaya-dago', null, null, 'Rasteirar o adversário', 3),
  ('m27-3-6', 79, 'goal', 'home', 'Dagó Tshibamba', 'dago-tshibamba', null, null, '1-1', 4),
  ('m27-3-6', 90, 'goal', 'home', 'Calebi Yanda', 'fifa-1jm8058', null, null, '2-1', 5),
  ('m27-3-1', 1, 'yellow', 'home', 'Cachindele', 'fifa-1jz48i2', null, null, null, 0),
  ('m27-3-1', 15, 'goal', 'home', 'Mariano da Costa Vidal', 'fifa-1jsrqb0', null, null, 'Autogolo · 1-0', 1),
  ('m27-3-1', 44, 'yellow', 'home', 'Platiny', 'platini', null, null, null, 2),
  ('m27-3-1', 45, 'sub', 'home', 'João Bivoba Zau', 'fifa-1kzthb4', null, 'Joaquim Teixeira', null, 3),
  ('m27-3-1', 52, 'goal', 'away', 'Benvindo Miguel André Afonso', 'fifa-1jz4pi8', null, null, '1-1', 4),
  ('m27-3-1', 57, 'sub', 'home', 'Bernardo Raimundo Nacavuza', null, null, 'Félix Honjo', null, 5),
  ('m27-3-1', 57, 'sub', 'home', 'António Ngola Ngulu', 'fifa-1jwt8s6', null, 'João Baptista Cassicote', null, 6),
  ('m27-3-1', 61, 'sub', 'away', 'Benedito Antunes', 'fifa-1lda172', null, 'Benvindo Miguel André Afonso', null, 7),
  ('m27-3-1', 61, 'sub', 'away', 'Ernesto Vieira', 'fifa-1qvfe29', null, 'Gabriel Venâncio', null, 8),
  ('m27-3-1', 64, 'yellow', 'away', 'Arilson de Ceita Pereira Jorge', 'fifa-1jwgzb2', null, null, null, 9),
  ('m27-3-1', 68, 'sub', 'away', 'José Manuel Raul', 'fifa-1r8lp51', null, 'Timóteo Sambissa', null, 10),
  ('m27-3-1', 72, 'yellow', 'home', 'Singongo', 'fifa-1k2pgl3', null, null, null, 11),
  ('m27-3-1', 75, 'sub', 'home', 'João Silvano Caluvili', 'fifa-1kf4fa8', null, 'Platiny', null, 12),
  ('m27-3-1', 82, 'sub', 'away', 'Tiago Jamba Adelino', 'fifa-1uy6ar6', null, 'Cuxixima', null, 13),
  ('m27-3-1', 82, 'sub', 'away', 'Osvaldo José', 'fifa-1kz4es4', null, 'Arilson de Ceita Pereira Jorge', null, 14),
  ('m27-3-1', 83, 'yellow', 'away', 'Ernesto Vieira', 'fifa-1qvfe29', null, null, null, 15),
  ('m27-3-1', 90, 'sub', 'home', 'Mário Bernardo Keta', 'fifa-1jzmgd3', null, 'Kibuata', null, 16),
  ('m27-3-1', 90, 'goal', 'away', 'Tiago Jamba Adelino', 'fifa-1uy6ar6', null, null, '90''+4'' · 1-2', 17),
  ('m27-3-1', 90, 'yellow', 'away', 'Tiago Jamba Adelino', 'fifa-1uy6ar6', null, null, '90''+5'' · celebração excessiva', 18),
  ('m27-3-4', 1, 'goal', 'home', 'Jaime', 'fifa-1qw9vb1', null, null, '1-0', 0),
  ('m27-3-4', 19, 'yellow', 'home', 'Denilson', 'fifa-1l7lph0', null, null, 'Comportamento antidesportivo', 1),
  ('m27-3-4', 21, 'yellow', 'away', 'Francisco Luemba', 'fifa-1qtzy92', null, null, 'Protestou a decisão do árbitro', 2),
  ('m27-3-4', 26, 'sub', 'home', 'Hamilton', 'fifa-1maldz0', null, 'Celio Nimi', null, 3),
  ('m27-3-4', 29, 'goal', 'away', 'Ariclenis Afonso Araújo Lede', 'ariclenis-cabinda', null, null, '1-1', 4),
  ('m27-3-4', 29, 'yellow', 'away', 'Rodrigo', 'rodrigo-cabinda', null, null, 'Rasteirou o adversário', 5),
  ('m27-3-4', 33, 'yellow', 'home', 'Jaime', 'fifa-1qw9vb1', null, null, 'Rasteirou o adversário', 6),
  ('m27-3-4', 45, 'sub', 'home', 'Francisco', 'fifa-1l11132', null, 'Pedro', null, 7),
  ('m27-3-4', 45, 'sub', 'away', 'Fernando', 'fernando-cabinda', null, 'Cristiano Malonda', null, 8),
  ('m27-3-4', 45, 'sub', 'away', 'Crichano Diacango', null, null, 'Gedeon', null, 9),
  ('m27-3-4', 45, 'sub', 'away', 'Júlio Mavungo André', 'julio-cabinda', null, 'Frederico Zau', null, 10),
  ('m27-3-4', 47, 'yellow', 'away', 'Luyeye Tomás', 'luyeye-cabinda', null, null, 'Rasteirou o adversário', 11),
  ('m27-3-4', 67, 'goal', 'home', 'Jaime', 'fifa-1qw9vb1', null, null, '2-1', 12),
  ('m27-3-4', 72, 'sub', 'home', 'Pedro', 'fifa-1maldr2', null, 'Miguel Matos', null, 13),
  ('m27-3-4', 72, 'sub', 'home', 'Batista Kachama', 'fifa-1v0ca42', null, 'Denilson', null, 14),
  ('m27-3-4', 78, 'sub', 'away', 'Simão Gomes', 'simao-gomes-cabinda', null, 'Mário da Silva', null, 15),
  ('m27-3-4', 83, 'sub', 'home', 'Domingos', 'fifa-1l08hy2', null, 'Jaime', null, 16),
  ('m27-3-4', 83, 'sub', 'away', 'Cornélio', 'cornelio-cabinda', null, 'Crichano Diacango', null, 17),
  ('m27-3-8', 47, 'goal', 'away', 'Moisés', 'moises-primeiromaio', null, null, '45''+2 · 0-1', 0),
  ('m27-3-8', 81, 'goal', 'away', 'Kessie Messi', 'kessie-messi-primeiromaio', null, null, '0-2', 1),
  ('m27-3-5', 27, 'goal', 'away', 'Beni Papel', 'beni-papel-saosalvador', null, null, '0-1', 0),
  ('m27-4-5', 25, 'goal', 'home', 'Luyeye Tomás', 'luyeye-cabinda', null, null, '25'' (1-0)', 0),
  ('m27-4-5', 45, 'sub', 'away', 'Dagó Tshibamba', 'dago-tshibamba', null, 'Castro', null, 1),
  ('m27-4-5', 45, 'sub', 'away', 'Bulaya', 'bulaya-dago', null, 'Erique de Jesus', null, 2),
  ('m27-4-5', 45, 'sub', 'away', 'Macaia', 'macaia-dago', null, 'Benção', null, 3),
  ('m27-4-5', 46, 'goal', 'away', 'Axel', 'axel-dago', null, null, '46'' (1-1)', 4),
  ('m27-4-5', 57, 'sub', 'home', 'Crichano Diacango', null, null, 'Ariclenis Afonso Araújo Lede', null, 5),
  ('m27-4-5', 57, 'sub', 'home', 'Domingos Paixão Paulino Lourenço', 'domingos-paixao-cabinda', null, 'Fernando', null, 6),
  ('m27-4-5', 57, 'sub', 'home', 'Gedeon', 'gedeon-cabinda', null, 'Cornélio', null, 7),
  ('m27-4-5', 64, 'sub', 'away', 'Clíver', 'cliver-dago', null, 'Luciano dos Santos', null, 8),
  ('m27-4-5', 66, 'sub', 'home', 'Cristiano Malonda', 'cristiano-cabinda', null, 'Mário da Silva', null, 9),
  ('m27-4-5', 66, 'yellow', 'home', 'Mário da Silva', 'fifa-1ljjyh4', null, null, 'Jogo perigoso', 10),
  ('m27-4-5', 71, 'sub', 'away', 'Tombé', 'tombe-dago', null, 'Rupson', null, 11),
  ('m27-4-5', 75, 'sub', 'home', 'Simão Gomes', 'simao-gomes-cabinda', null, 'Crichano Diacango', null, 12),
  ('m27-4-5', 75, 'yellow', 'home', 'Marcos', 'marcos-cabinda', null, null, 'Falta tática', 13),
  ('m27-4-5', 79, 'yellow', 'away', 'Bruno', 'bruno-dago', null, null, 'Falta tática', 14),
  ('m27-4-5', 86, 'yellow', 'home', 'João Eduardo', 'cabinda-player-1', null, null, 'Simulou lesão para retardar o jogo.', 15),
  ('m27-4-5', 93, 'yellow', 'home', 'Cristiano Malonda', 'cristiano-cabinda', null, null, 'Falta temerária', 16),
  ('m27-4-7', 26, 'goal', 'home', 'Patrick Banza', 'patrick-banza-interclube', null, null, '26'' (1-0)', 0),
  ('m27-4-7', 39, 'goal', 'home', 'Pedro Manuel', null, null, null, '39'' (2-0)', 1),
  ('m27-4-2', 21, 'goal', 'away', 'Alexandre Fernando', 'fifa-1v1a1u9', null, null, '21'' (0-1)', 0),
  ('m27-4-2', 29, 'yellow', 'home', 'Cachindele', 'manucho-lunda-sul', null, null, 'Falta táctica', 1),
  ('m27-4-2', 35, 'yellow', 'home', 'Cleverson Silva', null, null, null, 'Treinador · Persistir em desobedecer às instruções do árbitro', 2),
  ('m27-4-2', 44, 'yellow', 'home', 'Keta', 'sozito', null, null, 'Prática de jogo perigoso', 3),
  ('m27-4-2', 45, 'goal', 'home', 'Mussá', 'mussa-lunda-sul', null, null, '45''+4'' (1-1)', 4),
  ('m27-4-2', 45, 'yellow', 'away', 'Alexandre Fernando', 'fifa-1v1a1u9', null, null, '45''+3'' · Agarrar adversário', 5),
  ('m27-4-2', 45, 'yellow', 'away', 'Miguel', 'miguel-sagrada', null, null, '45''+3'' · Discordar da decisão do árbitro', 6),
  ('m27-4-2', 45, 'sub', 'home', 'Bernardo Raimundo Nacavuza', 'nacavuza-lunda-sul', null, 'Vado', null, 7),
  ('m27-4-2', 51, 'yellow', 'away', 'Dala', 'melono-sagrada', null, null, 'Empurrar adversário', 8),
  ('m27-4-2', 53, 'goal', 'home', 'Magrinho', 'magrinho', null, null, '53'' (2-1)', 9),
  ('m27-4-2', 56, 'sub', 'away', 'Cabuço', 'guilherme-sagrada', null, 'Barreira', null, 10),
  ('m27-4-2', 56, 'sub', 'away', 'Sebastiao', 'dabanda-sagrada', null, 'Francisco Lucussa', null, 11),
  ('m27-4-2', 60, 'sub', 'home', 'Ngulu', 'jepson', null, 'Mussá', null, 12),
  ('m27-4-2', 63, 'yellow', 'home', 'Joca', 'joca-lunda-sul', null, null, 'Falta táctica', 13),
  ('m27-4-2', 67, 'yellow', 'home', 'Nguala', 'fifa-1k1k2v2', null, null, 'Entrar para o terreno sem autorização', 14),
  ('m27-4-2', 67, 'sub', 'home', 'Kibuata', 'kibuata', null, 'Keta', null, 15),
  ('m27-4-2', 67, 'sub', 'home', 'Nguala', 'fifa-1k1k2v2', null, 'Joca', null, 16),
  ('m27-4-2', 70, 'yellow', 'home', 'Kibuata', 'kibuata', null, null, 'Rastrear adversário', 17),
  ('m27-4-2', 71, 'yellow', 'home', 'Agostinho', 'fifa-1k2wai2', null, null, 'Falta táctica', 18),
  ('m27-4-2', 75, 'yellow', 'home', 'Paulino', 'platini', null, null, 'Falta tática', 19),
  ('m27-4-2', 76, 'sub', 'away', 'Muanha', 'gogoro-sagrada', null, 'Manuel', null, 20),
  ('m27-4-2', 76, 'sub', 'away', 'Pimpão', 'pimpao-sagrada', null, 'Afonso', null, 21),
  ('m27-4-2', 80, 'sub', 'home', 'Ximba', 'ximba', null, 'Agostinho', null, 22),
  ('m27-4-2', 83, 'yellow', 'home', 'Bernardo Raimundo Nacavuza', 'nacavuza-lunda-sul', null, null, 'Falta táctica', 23),
  ('m27-4-2', 92, 'sub', 'away', 'Tobias', 'tobias-sagrada', null, 'Miranda', null, 24),
  ('m27-4-2', 93, 'yellow', 'home', 'Magrinho', 'magrinho', null, null, 'Falta táctica', 25),
  ('m27-4-8', 7, 'goal', 'away', 'Tchutchu', 'fifa-1nb4bp9', null, null, '7'' (0-1)', 0),
  ('m27-4-8', 17, 'goal', 'home', 'Mestre Gui', 'mestre-gui-libolo', null, null, '17'' (1-1)', 1),
  ('m27-4-8', 38, 'goal', 'home', 'Pedro Mendes', 'pedro-libolo', null, null, '38'' (2-1)', 2);

insert into public.ancaf_match_stats (match_id, side, stat_key, value, published) values
  ('m27-1-4', 'home', 'yellowCards', 4, true),
  ('m27-1-4', 'away', 'yellowCards', 3, true),
  ('m27-1-4', 'home', 'redCards', 0, true),
  ('m27-1-4', 'away', 'redCards', 0, true),
  ('m27-1-2', 'home', 'yellowCards', 2, true),
  ('m27-1-2', 'away', 'yellowCards', 3, true),
  ('m27-1-2', 'home', 'redCards', 0, true),
  ('m27-1-2', 'away', 'redCards', 0, true),
  ('m27-1-3', 'home', 'corners', 0, true),
  ('m27-1-3', 'away', 'corners', 1, true),
  ('m27-1-3', 'home', 'yellowCards', 3, true),
  ('m27-1-3', 'away', 'yellowCards', 1, true),
  ('m27-1-3', 'home', 'redCards', 0, true),
  ('m27-1-3', 'away', 'redCards', 0, true),
  ('m27-1-7', 'home', 'yellowCards', 2, true),
  ('m27-1-7', 'away', 'yellowCards', 0, true),
  ('m27-1-7', 'home', 'redCards', 0, true),
  ('m27-1-7', 'away', 'redCards', 0, true),
  ('m27-1-1', 'home', 'corners', 1, true),
  ('m27-1-1', 'away', 'corners', 0, true),
  ('m27-1-1', 'home', 'yellowCards', 0, true),
  ('m27-1-1', 'away', 'yellowCards', 1, true),
  ('m27-1-1', 'home', 'redCards', 0, true),
  ('m27-1-1', 'away', 'redCards', 0, true),
  ('m27-1-6', 'home', 'corners', 1, true),
  ('m27-1-6', 'away', 'corners', 0, true),
  ('m27-1-6', 'home', 'yellowCards', 2, true),
  ('m27-1-6', 'away', 'yellowCards', 4, true),
  ('m27-1-5', 'home', 'corners', 0, true),
  ('m27-1-5', 'away', 'corners', 0, true),
  ('m27-1-5', 'home', 'yellowCards', 0, true),
  ('m27-1-5', 'away', 'yellowCards', 1, true),
  ('m27-2-3', 'home', 'fouls', 8, true),
  ('m27-2-3', 'away', 'fouls', 3, true),
  ('m27-2-3', 'home', 'yellowCards', 8, true),
  ('m27-2-3', 'away', 'yellowCards', 3, true),
  ('m27-2-3', 'home', 'redCards', 0, true),
  ('m27-2-3', 'away', 'redCards', 0, true),
  ('m27-2-7', 'home', 'corners', 0, true),
  ('m27-2-7', 'away', 'corners', 0, true),
  ('m27-2-7', 'home', 'saves', 0, true),
  ('m27-2-7', 'away', 'saves', 0, true),
  ('m27-2-7', 'home', 'yellowCards', 2, true),
  ('m27-2-7', 'away', 'yellowCards', 2, true),
  ('m27-2-7', 'home', 'redCards', 0, true),
  ('m27-2-7', 'away', 'redCards', 0, true),
  ('m27-2-1', 'home', 'redCards', 1, true),
  ('m27-2-1', 'away', 'redCards', 0, true),
  ('m27-2-5', 'home', 'yellowCards', 1, true),
  ('m27-2-5', 'away', 'yellowCards', 4, true),
  ('m27-2-5', 'home', 'redCards', 0, true),
  ('m27-2-5', 'away', 'redCards', 0, true),
  ('m27-2-4', 'home', 'yellowCards', 1, true),
  ('m27-2-4', 'away', 'yellowCards', 1, true),
  ('m27-2-4', 'home', 'redCards', 0, true),
  ('m27-2-4', 'away', 'redCards', 0, true),
  ('m27-2-2', 'home', 'yellowCards', 2, true),
  ('m27-2-2', 'away', 'yellowCards', 4, true),
  ('m27-2-2', 'home', 'redCards', 0, true),
  ('m27-2-2', 'away', 'redCards', 0, true),
  ('m27-2-8', 'home', 'possession', 50, true),
  ('m27-2-8', 'away', 'possession', 50, true),
  ('m27-2-8', 'home', 'corners', 1, true),
  ('m27-2-8', 'away', 'corners', 0, true),
  ('m27-2-8', 'home', 'yellowCards', 1, true),
  ('m27-2-8', 'away', 'yellowCards', 1, true),
  ('m27-2-8', 'home', 'saves', 0, true),
  ('m27-2-8', 'away', 'saves', 0, true),
  ('m27-3-7', 'home', 'yellowCards', 1, true),
  ('m27-3-7', 'away', 'yellowCards', 2, true),
  ('m27-3-7', 'home', 'redCards', 0, true),
  ('m27-3-7', 'away', 'redCards', 0, true),
  ('m27-3-6', 'home', 'corners', 4, true),
  ('m27-3-6', 'away', 'corners', 4, true),
  ('m27-3-6', 'home', 'yellowCards', 2, true),
  ('m27-3-6', 'away', 'yellowCards', 1, true),
  ('m27-3-6', 'home', 'redCards', 0, true),
  ('m27-3-6', 'away', 'redCards', 0, true),
  ('m27-3-1', 'home', 'yellowCards', 3, true),
  ('m27-3-1', 'away', 'yellowCards', 3, true),
  ('m27-3-1', 'home', 'redCards', 0, true),
  ('m27-3-1', 'away', 'redCards', 0, true),
  ('m27-3-4', 'home', 'yellowCards', 2, true),
  ('m27-3-4', 'away', 'yellowCards', 3, true),
  ('m27-3-4', 'home', 'redCards', 0, true),
  ('m27-3-4', 'away', 'redCards', 0, true),
  ('m27-3-8', 'home', 'corners', 1, true),
  ('m27-3-8', 'away', 'corners', 0, true),
  ('m27-3-8', 'home', 'yellowCards', 6, true),
  ('m27-3-8', 'away', 'yellowCards', 3, true),
  ('m27-4-5', 'home', 'yellowCards', 4, true),
  ('m27-4-5', 'away', 'yellowCards', 1, true),
  ('m27-4-5', 'home', 'redCards', 0, true),
  ('m27-4-5', 'away', 'redCards', 0, true),
  ('m27-4-7', 'home', 'corners', 4, true),
  ('m27-4-7', 'away', 'corners', 4, true),
  ('m27-4-7', 'home', 'yellowCards', 2, true),
  ('m27-4-7', 'away', 'yellowCards', 1, true),
  ('m27-4-7', 'home', 'redCards', 0, true),
  ('m27-4-7', 'away', 'redCards', 0, true),
  ('m27-4-2', 'home', 'yellowCards', 10, true),
  ('m27-4-2', 'away', 'yellowCards', 3, true),
  ('m27-4-2', 'home', 'redCards', 0, true),
  ('m27-4-2', 'away', 'redCards', 0, true)
on conflict (match_id,side,stat_key) do update set value = excluded.value, published = excluded.published;
