-- Integracao FIFA FCMS / Genius Sports
-- Estrutura aditiva: nao apaga nem substitui dados existentes.

create table if not exists public.ancaf_fcms_team_mappings (
  id bigint generated by default as identity primary key,
  provider text not null,
  tenant text not null,
  external_team_id text not null,
  team_id text not null references public.ancaf_teams(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (provider, tenant, external_team_id)
);

create index if not exists ancaf_fcms_team_mappings_team_idx
  on public.ancaf_fcms_team_mappings(team_id);

create table if not exists public.ancaf_fcms_match_mappings (
  id bigint generated by default as identity primary key,
  provider text not null,
  tenant text not null,
  external_match_id text not null,
  match_id text not null references public.ancaf_matches(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (provider, tenant, external_match_id)
);

create index if not exists ancaf_fcms_match_mappings_match_idx
  on public.ancaf_fcms_match_mappings(match_id);

create table if not exists public.ancaf_fcms_sync_runs (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  tenant text not null,
  competition_external_id text not null,
  season_id text not null,
  request_fingerprint text not null,
  dry_run boolean not null default true,
  status text not null default 'running'
    check (status in ('running', 'validated', 'completed', 'failed')),
  matches_received integer not null default 0,
  matches_written integer not null default 0,
  events_written integer not null default 0,
  error_message text,
  created_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz
);

create index if not exists ancaf_fcms_sync_runs_created_idx
  on public.ancaf_fcms_sync_runs(created_at desc);

alter table public.ancaf_fcms_team_mappings enable row level security;
alter table public.ancaf_fcms_match_mappings enable row level security;
alter table public.ancaf_fcms_sync_runs enable row level security;

-- Nenhuma politica publica: estas tabelas sao utilizadas exclusivamente
-- no servidor atraves da service_role e da sessao administrativa.

insert into public.ancaf_fcms_team_mappings
  (provider, tenant, external_team_id, team_id)
values
  ('authorised-push', 'ang', 'Estrela Clube Primeiro de Maio', 'primeiromaio'),
  ('authorised-push', 'ang', 'Wiliete Sport Clube de Benguela', 'wiliete'),
  ('authorised-push', 'ang', 'Clube Desportivo da Huila', 'desphuila'),
  ('authorised-push', 'ang', 'Clube Desportivo 1.º de Agosto', 'dago'),
  ('authorised-push', 'ang', 'Kabuscorp Sport Clube do Palanca', 'kabuscorp'),
  ('authorised-push', 'ang', 'Académica Petróleos Clube do Lobito', 'lobito'),
  ('authorised-push', 'ang', 'Futebol Clube de Luanda', 'fcluanda'),
  ('authorised-push', 'ang', 'Clube Recreativo e Desportivo do Libolo', 'libolo'),
  ('authorised-push', 'ang', 'Clube Recreativo da Caála', 'caala'),
  ('authorised-push', 'ang', 'Grupo Desportivo Interclube', 'interclube'),
  ('authorised-push', 'ang', 'Futebol Clube Bravos do Maquis', 'bravos'),
  ('authorised-push', 'ang', 'Clube Desportivo Sagrada Esperança', 'sagrada'),
  ('authorised-push', 'ang', 'Clube Desportivo da Lunda-Sul', 'lundasul'),
  ('authorised-push', 'ang', 'São Salvador do Kongo Futebol Clube', 'saosalvador'),
  ('authorised-push', 'ang', 'Atlético Petróleos de Luanda', 'petro'),
  ('authorised-push', 'ang', 'Futebol Clube de Cabinda', 'cabinda')
on conflict (provider, tenant, external_team_id)
do update set
  team_id = excluded.team_id,
  updated_at = timezone('utc', now());
